### ISSUE TITLE
Add subtitles automatically to the player

### ISSUE THREAD

**Issue by xalaros** [Tikipeter/repository.tikipeter#1]
Congratulations on the continued development of the "Furk It" add-on, only if you can add subtitles automatically to the player, as it existed from the beginning in the exodus forks.

**Comment by Tikipeter** [comment]
Hi xalaros.

Thank you for the kind words and for using the add-on. I only knew of one person using Furk It except for me, so I suppose there may be more out there.

Furk It is not a fork of Exodus code, it is by and large fresh code (with certain code taken from other add-ons including Exodus forks). It does however support Exodus style scrapers using modified code from Exodus forks. I'm mainly saying this because my player module is completely different from Exodus forks, and this is where the subtitle implementation is.

Let me have a look at the subtitle code, and see how well it performs because I've never used it before myself when I used Exodus forks. It always seemed redundant since Kodi can do this internally, and there are add-ons available to automate this.

If there is something extra this brings that the Kodi internal subtitle implementation is lacking, I may add it if I can get it to work. If you have any views on why it is better, feel free to let me know. :)

**Comment by xalaros** [comment]
Nothing more than the possibility of simplifying the subtitle selection process by people less familiar with the player and its functions. Keep going your work sir...

**Comment by Tikipeter** [comment]
OK. I'll give it a look and see if I can add it.
