### ISSUE TITLE
Fen Watched section

### ISSUE THREAD

**Issue by techecoyote** [Tikipeter/repository.tikipeter#105]
Previously to last update, Watched section, from main screen only worked for watched movies, did not work for tvshows. This last update, trakt issues, i believe with the Fen addon. Now I check Watched section, nothing. Just checked the Trakt Watchlist, nothing, keeps asking to re authenticate. And never authenticates, giving trakt response timeout error. Been getting the Timeout error for awhile now with the addon, seemed to work up til now. So I don't know what to think or say....

**Comment by brentonv** [comment]
Not sure if it's a Trakt issue but I can't get any Trakt tv watched lists ATM not just Fen

**Comment by techecoyote** [comment]
I saw your response, edited my initial issue. Trakt does have lots of issues at times... But Fen displaying the trakt timeout error (but trakt working) was not a big deal for me. I don't complain about free stuff. Lol... Now I'm having more issues, letting Tiki know about them helps him & us. He does an excellent job with his work & is very helpful... Hope this helps you out some....

**Comment by techecoyote** [comment]
Update:: Just did some more testing in Fen. Trakt seems to be having issues right now....

But I do believe the Watched section (TVshows) does have a bug. Watched movies displays the movies I watched. TVshows displays nothing...

I guess more to come...

**Comment by Tikipeter** [comment]
OK. There's a bit to go through here.

* Watched TV Shows is fine. There is no bug except for the Trakt errors. Fen doesn't do one great big Trakt cache like Seren does. It caches info from Trakt on demand. Movie and TV Show watched statuses are 2 different calls to Trakt. So it's not a sign of a bug when one works and the other doesn't when Trakt is having issues. The current issues wiith Trakt are abnormal somewhat in behavior. The failed responses are not consistent. i.e. one time I may be able to mark something as watched, but not get the new list of watched movies, the next time I try that works fine but I cannot get the new Watchlist to come through.

* The missing movie pics are a bit harder to explain. Tikimeta (which Fen uses for metadata) uses TMDb for all movie metadata. TMDb list ALL production companies (studios) that are associated with a movie's production. Therefore, Fen often (usually) feeds a LIST of studios to Kodi for display. This does not work well with skins that like to do fancy 'studio icons', because their logic relies on 1 studio being set. I will push an update for tikimeta to only return the first studio in the list of studio results.
Furthermore, if no studio is assigned by an add-on, then the Movie's poster is displayed by the skin instead. The problem comes when a studio is assigned, but the skin doesn't have an icon for it. Then, it won't fall back to the movie's poster, it will just have a blank space.
So, I can improve this situation, but not fix it entirely unless i did something like Venom does and not set a studio at all for any movies, meaning the movie's poster is always displayed as the fallback. But, I'm not going to do that.
