### ISSUE TITLE
AllDebrid

### ISSUE THREAD

**Issue by Sovilor** [Tikipeter/repository.tikipeter#11]
Hello, Fen doesn't find AllDebrid torrents, only showing web-links.
Thank you.

**Comment by Tikipeter** [comment]
Hi Sovilor.

Make sure you don't have 'Show Cached Torrents Only' enabled, as I haven't implemented that for All-Debrid.

Otherwise, I'll look into it.

**Comment by Tikipeter** [comment]
@Sovilor, can you tell me if you have any other debrid services enabled and authorized in ResolveURL (other than All-Debrid)?

**Comment by edb64** [comment]
I have RD and Link Snappy and cached torrents are there for RD but not for LS. FYI

**Comment by edb64** [comment]
Turned off "cached only" and now seeing torrents from both RD & LS.

**Comment by Tikipeter** [comment]
Yeah, I'm checking only RD and PM at the moment. So if they aren't cached on either of those, I remove them from the results. It looks like I'll have to support ALL the debrid services that ResolveURL supports. I was planning on adding other debrid services over time, but I'll have to get this sorted out sooner rather than later.

**Comment by edb64** [comment]
Not worried about it, whenever you have time bro 👊

**Comment by edb64** [comment]
I think the primary ones are just RD, AD, PM & LS. That would be a great start and would cover 99.9% of debrid users.

**Comment by Tikipeter** [comment]
True. Definitely AD and LS next.

**Comment by Sovilor** [comment]
@Tikipeter Hello, yes i have Real-debrid and AllDebrid enabled and authorized in ResolveURL both Cached torrents only = no AllDebrid torrents.
Now i tried:

1. in ResolveURL, Real-debrid (cached only) ON + AllDebrid (cached only) Off = no AllDebrid torrents.

2. in ResolveURL, Real-debrid (cached only) Off + AllDebrid (cached only) Off = no AllDebrid torrents.

3. In Fen Settings (cached only) Off = AllDebrid torrents.

Yes, when you have time please make Fen support at least the popular Debrid services like AllDebrid LS. Thanks

**Comment by Tikipeter** [comment]
Unfortunately, I have a lot of bad news and only a little good news.

The bad news is neither AllDebrid or LinkSnappy have a function in their API to test multiple torrent hashes in one call (RD and PM do this). This means to check 100 torrent results, I would have to send 100 calls to each of their APIs. This is not something that should be done. It's probably why Seren hasn't added support for these debrid services. Long story short, I cannot add cached only support for these debrid providers. If they add a multiple hash check to their API, then I will add these. (If you know an add-on that DOES check these providers BEFORE picking one for playback, let me know and I can look at it and see what it does.) I'm sorry all. :( :(

The slightly good news is I can, of course, display the 'unchecked' torrents for these debrid services.

If I code that in, then in results you will have only cached torrents for RD and PM, and all torrents for the other debrid services.

Alternatively, I can leave it as it is so the 'Uncached Only' setting truly does what it says, and only shows torrent results it KNOWS is cached through RD and PM.

Lastly, I could add a setting so you could choose whether to show the 'unchecked' results from other debrid services, or ignore them and only return cached results from RD and PM.

I feel the last option is the way to go, as you can choose to only receive cached results, or also receive unchecked results from other debrid providers.

Mostly bad news though. :( :( :( :( 

Let me know what you think....

**Comment by edb64** [comment]
"Lastly, I could add a setting so you could choose whether to show the 'unchecked' results from other debrid services, or ignore them and only return cached results from RD and PM."
I agree that this would probably be the best way to go until AD and/or LS can support multiple hash check.
I will look at some other scraper addons and see if any of them have found a way with AD/LS...not getting my hopes up :)
Will definitely let you know if I find anything. 
Thanks for everything you've been doing so far, great addon my friend!

**Comment by Sovilor** [comment]
Is it possible to add an option to show the ResolveURL results only i mean away of Real-debrid pairing option?
Before you added the pairing option, Fen was like most the other add-ons (but the fastest) showing results of ResolveURL.
Would you please tell me what the advantage of the pairing option? And are you saying that ResolveURL doesn't show a real catched torrents when the (catched only ON)?

Lastly, i would like to donate a premium AllDebrid account if you need to run some tests "consider it as a small box of beer :) ".

**Comment by Tikipeter** [comment]
@Sovilor 

I appreciate the offer Sovilor, but I purchased a small subscription to check. I'll use it while I have it. :) :)

Firstly, the 'cached torrents only' settings in Fen and ResolveURL are for different purposes. In Fen, it decides whether to SHOW the result at all. In ResolveURL, it decides whether it will PLAY the result you choose. They are independent of each other. (Unless you want to wait for a torrent to be downloaded by your debrid provider through ResolveURL, you should have 'cached only' ENABLED in ResolveURL for each of your debrid accounts.)

I'll explain to you the process of getting/showing results.

Fen will check different websites that supply links, and get those links and add them to the sources it is going to show. (ResolveURL is not involved at this time.)

Fen then checks with ResolveURL to see if you have Authorized any debrid providers through it. If you have, it will make another listing of that result with 'RD', 'AD' etc if that link can be resolved through that debrid service.

If you have cached torrents only enabled in Fen, then Fen will check with RD/PM (whichever you have paired with Fen) to see if that torrent is cached on their server. If not, it will remove it from the search results. (ResolveURL is not involved in this process.)

I'll be pushing an update later (after testing), that will give you the option to also show torrents for debrid providers outside of RD/PM when you have cached only enabled. These are for All-Debrid, Linksnappy etc. (This is what this issue ticket is about. You currently can't see your All-Debrid torrent links because Fen filters them out because it can't check All-Debrid for cached status of the torrent.)

So... If you want Fen to check RD and/or PM for whether a torrent is cached, but also to show your All-Debrid torrent links, then you will be able to after the next update.

If you simply want Fen to show all torrent links, cached or not, then just disable 'Show Uncached Torrents Only' in settings, and Fen will behave like it used to. Then it is up to ResolveURL as to whether it can PLAY the result you choose immediately (i.e. whether it is cached).

The only reason to pair RD/PM with Fen is if you want Fen to check for cached torrents through those services. There is nothing else Fen currently does with RD/PM once authorized.

I need to test the update before pushing it through (roughly 24hrs from now), so turn off cached torrents only in Fen until then if you want your All-Debrid torrent links to show.

**Comment by Sovilor** [comment]
Thank you for the information, it's very clear.

"will give you the option to also show torrents for debrid providers outside of RD/PM when you have cached only enabled." 
That's exactly what i meant, i just typed it in a different way. 
It's the best solution.

Thank you.

**Comment by Tikipeter** [comment]
Fixed in v.1.5.29.
Closing this...
