### ISSUE TITLE
Plays wrong episode from season pack when selecting source but when browse pack and manually select file, correct episode plays

### ISSUE THREAD

**Issue by ambulancePilot** [Tikipeter/repository.tikipeter#119]
**Log:** https://paste.kodi.tv/xawobozeje
**Debug Log:** https://paste.kodi.tv/ilisufifeq

This is a weird one. I haven't tried any other shows but it happens with the show Friends. In particular, season 5, and possibly other seasons/episodes as well.

**Background:** I only have pack capable scrapers enabled in cocoscrapers. The issue happens with or without auto play enabled. The issue occurs at the point where Fen automatically investigates the season pack (without manually going into browse pack) and selects the file to play. Manual selection of the file (for ex: S05E01) results in the correct episode (if I went into browe pack first). However if you do not browse pack and you instead simply select the source from the initial source select screen, it plays S01E02 instead of E01. This is confirmed by looking at the RD site and it shows S05E02 playing, even though Fen thinks it's playing S05E01.

The worst thing is this only happens with one particular torrent/hash that is VERY popular and shows up on ALL the torrent sites. It's not as simple as disabling sources in cocoscrapers because then I won't be left with any sources since the torrent is literally everywhere on every tracker.

Even worse, the torrent provides the highest file size for each episode, so with auto-play enabled, I will always be playing the wrong episode no matter what.

Even worse than that, I'm not able to use the undesirables list to filter out any of the problematic results (the torrent with same hash is found with about 2 or 3 different tiles and I have entered each one verbatim into the undesirables list, replacing all separators with dots, and clearing scraper cache afterword along with a restart of Kodi and still, it shows up int he source list as if I haven't made any change at all).

**To recreate the problem:** Enable pack capable scrapers in cocoscrapers. Scrape for Friends S05E01. Play the largest file. It will play E02 instead (the opening scene is Chandler and Monica in the bathtub). The correct episode (E01) should have a wedding as an opening scene. Using the same source, if I manually select E01 in browse pack, it is the correct episode (the wedding scene).

If I use source select and select any other source other than the largest one, the correct episode plays without having to go into browse pack.

Log included. Thank you so very much for the fantastic add-on! Recent speed upgrade with reuselanguageinvoker is phenomenal.

**Comment by ambulancePilot** [comment]
Updated with debug log!

**Comment by Tikipeter** [comment]
Well isn't that a strange one! I have no idea how that could possibly happen. I do believe it will only happen on episode one. Is that right? I played S05E02 and S05E03 from the same pack and the correct file was chosen.

My short term advice (which I'm sure you already know) would be to just manually select this first episode. The rest should play fine after that.

I will look into exactly what's happening and hopefully get it sorted out. I'm just limited on time at the moment.

**Comment by ambulancePilot** [comment]
Thanks so much for replying! I don't know any python, but I wish I could help. If you require any troubleshooting or testing, just let me know and I will happily oblige.

It's extremely weird that it only happens with that specific torrent. Something about that particular torrent is unexpected and throwing a wrench into it all.

**Comment by Tikipeter** [comment]
I appreciate the offer of help but I'm in a good situation because I can replicate this myself. Nothing worse than something working fine for me but not for a user. Then it's logs..test..logs..test. I'll be able to test this myself thankfully.

The most likely causes are not present... The file is named correctly, and it's not a combined release i.e. S05E01E02. The combined release was what I had it pegged for when I read your Issue, but that's not the case.

Anyway, we'll get to the bottom of it. It's just very, very strange.

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by ambulancePilot** [comment]
You're awesome! Just because I'm curious, what was the issue?

**Comment by Tikipeter** [comment]
It was a combination of 2 things. But I'll need to finish my first coffee of the day to explain it properly.....

OK, if you're REALLY interested, I'll post a short answer and a long answer.

**SHORT ANSWER:** There was no S05E01 file in the first cached pack result from RD, and when the code went to the second file to check it's name, the `5.1` sound tag tripped it up and it accepted it as the correct S05E01 episode. And then of course played it.

**LONG ANSWER:** On the RD website, it allows you to choose which files in a cache pack are transferred to it's servers. You can choose any combination of files from the pack. If a pack has 10 items in it, and someone chooses to leave out the 5th item, RD then downloads the other 9 items from the pack and assigns that 9 item pack a place on it's servers.

If the next person wants the same pack, but has chosen not to download the 2nd item in the pack, RD again downloads the entire contents of the torrent pack to it's servers, assigning it a place. This means RD now has 2 instances of this torrent pack on it's servers, one missing the 5th file, one missing the 2nd file. Add to this the amount of combinations possible of files included/excluded from a simple torrent pack of 10 items, and we can see straight away that this method is not ideal.

Now onto the addons interaction with RD.....

Once the scrapers have found torrents relevant to your search, Fen will get the HASHES from those results, and send them to RD so that RD can reply as to whether it has that torrent cached on it's servers. At this point it is a simple true or false, there is no other relevant info received from RD.

If true, Fen will include that as a cached source. That in itself can prove troublesome, although it rarely happens, as there may only be one instance of that torrent cached on RD's servers, and the person who initiated the caching MAY have chosen to leave out of the cache request the very episode you are going to want to play. Those are the main situations where a cached torrent will fail to play. Rare but it happens.

In the case of this particular torrent pack, there were 2 unique instances of this particular torrent pack on RD's servers. It just so happens the first instance in the list of 2 did NOT contain S05E01. This means it SHOULD have failed to play, and Fen should have moved onto the second instance of the cached torrent. But because the file's name had `5.1` in it, and because there have been accommodations made to catch naming conventions outside of the norm (mainly for anime watchers), then this instance of `5.1` in the filename was ACCEPTED by the check as being the correct episode.

If the first cached pack had indeed included the correct file of S05E01, then this would not have happened as it would have been accepted as the correct season/episode before the check ever moved onto the second file in the pack.

What SHOULD have happened in this scenario is that ALL files in that first torrent pack should have failed the checking of their names for correct season/episode, then Fen would have moved to the second torrent pack and found S05E01 within. Then the correct episode would have played.

**Long story short (too late):**
RD has a terrible way of caching torrents from users, and I relented somewhat in trying to accommodate anime watchers some time in the distant past and added season/episode checks that tripped up the title checker into accepting a 5.1. Audio file as being S05E01. There is also an issue in how CocoScrapers formats certain data that's returned, making it less reliable. But that's something I have to get the CCS dev to fix. It's caused another issue in the current issues tab.


I know, I know....... but, you asked for an explanation. :)

To be honest, it's good for users to know how an addon operates certain functions. It really makes using them more tolerable. 

Addons running like they're using "voodoo" is not an ideal perspective to have of them. It is (generally) fairly simple code running logic based determinations. Just like any other code.
