### ISSUE TITLE
Feature request for categories 

### ISSUE THREAD

**Issue by edb64** [Tikipeter/repository.tikipeter#12]
The default number of titles listed per page seems to be set at 20. If view mode is set to thumbnail at 5 thumbs per row you get 5 rows with 3 empty spots on the last row. This is because the up/back takes up the 1st slot and the next page takes up the last slot. If this could be changed to a number ending in 3 or 8 the whole thumbnail page will be utilized. My personal preference would be at least 38, which would give 8 rows or 48 for 10 rows.
Not sure if this is something that you would need to hard code or add as a user adjustable option. I checked a few other addons and the default seems to be 40 in most. This is why I was thinking the pages in Fen seemed kinda short :) 
Thanks in advance for your help with this!
P. S. In Seren general settings there's an option for Page Item Limit. I set this to 48 and I get 10 full rows per page when browsing movie and TV categories.

**Comment by Tikipeter** [comment]
Unfortunately not possible in Fen. Most lists in Fen come from TMDb, which has a 20 item limit per page. It's not even a limit per se, you cannot even choose a lower amount if you wanted. It's 20 and that's it.

Personal lists from Trakt (Watchlist, other lists etc) I have set to 40 because that is the max number of calls I can make to TMDb (who also supply the metadata for Movies/TV Shows in Fen) every 10 seconds. Any over that and it makes you wait the remainder of the 10 seconds before accepting new queries. Even changing these lists to 42 items could add 1-9 seconds onto the time before they show.

So, unfortunately, it's stuck at 20 and 40 for Trakt lists. :( :( :(

I can't even think of any suggestions I could give to help you with this issue...

Sorry edb64. :( :(
