### ISSUE TITLE
Set views (enhancement) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#121]
Set view for discover, is that possible to add?
 It shows 'list' in Aeon nox silvo mod skin, personally I like 'shift', so all other options in Fen I have set to 'shift' (movies, shows, trakt lists etc). 

Would be great if I can force it to 'shift' also for 'Discovery' results in Fen also (just a idea)

**Comment by Tikipeter** [comment]
Hi Tinuz97. :) :)

Do you mean when the results show, or the discovery filter menus screen itself?

If you mean the page with the movie/tv show results, then it SHOULD honor the movie/tv show views already set.

You may need to increase your "Delay for Setting View Type" in Settings->General->Navigation. On my main computer I have it set at 500, for a slower device I have it set at 800. The slower the device, the higher the number you have to set it.

To test if that is the problem, temporarily set it very high (say, 1500), and see if the view changes once you bring up the results from Discover. Otherwise, there may be a bug.....

**Comment by Tinuz97** [comment]
I will try it asap, but the problem (aeon nox 'problem') is that you can't lock the views, the addons have to do that, with allot of skins you can set the view (I need it for the results, not the menu's) and then it will stick because in most skins you can set the view and lock it, that option is not available for Aeon nox silvo mod skin.

So in Fen I have set the the views (the options that are available at the moment) all to 'shift', like movies, TV shows, trakt lists (all the set views options in Fen). 

In this way all get forced to use shift (works great).
So 'honor already set' is the issue for me with aeon nox silvo mod, because there is no locking a view option in aeon nox. :)

**Comment by Tinuz97** [comment]
Ps:
Speed is not a issue for me (nvidia shield tv pro 2017, modified with a Samsung 860 EVO 500GB SSD internally, removed the SSHD).

**Comment by Tikipeter** [comment]
Trust me, you don't have to set all the views the same, FEN will change the view for each media. The problem lies with Kodi 18. They changed the way containers were loaded (each page basically), so all of a sudden addons' view settings weren't working anymore; or working sporadically. I eventually found the answer was to leave a pause AFTER loading the page before FEN sets the view.

The amount of pause you have to tinker with until it sets the view properly all the time. If you raise that setting ("Delay for Setting View Type" in Settings->General->Navigation), I promise you FEN will set the viewtypes properly.  You'll probably need somewhere between 500-800 ms for a Shield.

To show yourself that it works ,change one of the View Settings in Tools to something other than Shift, set the delay to 1500,  and then load up the media you changed and watch FEN set the view (the delay will be too much at 1500, but it will show you what is happening).

**Comment by Tinuz97** [comment]
Thx, I will try that later today (not a home at the moment), and play with the delay settings.

**Comment by Tinuz97** [comment]
Tryed it, but the view for discovery won't stick.
If I set all view options that are available in Fen no issues (they work 100%), is it possible to add a set view for discovery as a test? Like the buttons in the screenshot? 
![Screenshot_20200203-075751](https://user-images.githubusercontent.com/47715606/73632120-31d17400-465b-11ea-89e1-71474a5eed31.jpg)

**Comment by Tikipeter** [comment]
> ...is it possible to add a set view for discovery as a test? Like the buttons in the screenshot?

It's not possible because when making the items for the results of discover, it is in with the same batch of code as the other movie/tvshow items:
![discover](https://user-images.githubusercontent.com/28930002/73637963-96251f80-46bd-11ea-9691-848b308044fc.jpg)

So you've already set the view for Discover when you've set the general view for Movies/TV Shows.

**Please** up the delay for setting the views, it's going to solve this problem, I promise. Set it to 1000 and see what happens.

**Comment by Tinuz97** [comment]
Thx, little late, but it did work, thx.

**Comment by Tinuz97** [comment]
I did report it did work, but sometimes I did have issues for 'Discover' only, sometimes it jumped back again from 'shift' view to 'List' view.
Now with the new 'set view' code the issue is realy gone for me with Aeon nox silvo mod skin,great 🎉

**Comment by Tikipeter** [comment]
That's great news Tinuz97. It always bothered me that I had to introduce a delay just to get it to work.

The new code is a bit hacky as well, and does have the ability to hang for up to 30 seconds if something goes wrong, but I think I've covered any issues and I haven't had any reports of trouble yet.

It's also true that some menus may now load a bit slower, as the code waits for Kodi to tell it accurately what the content is of the current container, and then makes sure the view type is correct for that content. Kodi is not quick at doing this unfortunately.
