### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Sanjjay** [Tikipeter/repository.tikipeter#125]
Thank you for bringing back local FEN Favourites like Genesis addon as I don't like using trakt. I would like to make a few requests, hopefully you can add them in your addon.

1. In Favourites when you add a Movies or TV Show with "A" or "The" in the beginning it is ignored and it's sorted by the second word. e.g A Discovery of Witches comes under "D" or The Blacklist comes under "B", same with movie names. would like it to be in alphabetical order with the first word like in Genesis addon. 

2. "FAVOURITES: Episodes" in Favourites menu for local saved FEN Favourites easier to access. Also if this can show all episodes unwatched within the last 4 weeks like in Genesis addon. I know you have next episodes it doesn't work in there or I might be doing it wrong and also I have to add TV Shows manually in Favourites and Next Episodes and I got over 300 TV Shows which is alot. 

3. Also in Favourites you have "Jump to" it would be nice to have "Main Menu" above "Jump to" to go back to main navigation page because when you scroll few pages your have to click a few times to get back to the main page can be slow at times. Same in all Movies and TV Shows navigation would make it quicker going back to the main menu when you have scrolled alot of pages.

4. "FAVOURITES: Music" would like to have an option to hide this if possible in tools or settings.

5. Important request! Backup and Restore local FEN Favourites in tools or settings. It took me ages to add all my favourites.

Many Thanks!!!

**Comment by Tikipeter** [comment]
Hi @Sanjjay 
1. This will be available for next update. New setting found in Settings->General->Navigation->Ignore Articles When Sorting Lists. Default will be False (Off) so go in there and select it.

2. I'm going to have to think about this one more......

3. The **context menu** has "Exit Movie List" or "Exit TV Show List" already which does what you want.
As a companion to that, you can also enable Settings->General->Navigation->"Resume List Browsing from Last Viewed Page" so that when you re-enter a previously browsed list of any kind, you will be taken to page you last visited i.e. you browse 4 pages into 'Trending' movies, then Exit out of the list. When you browse into that list again, FEN will start you at Page 4.

4. I think I'll get rid of Music Favorites all together. It's only for Furk users.

5. Let me think of the best way to do this...... (In the meantime, you can navigate to your Kodi 'user_data' folder, find 'plugin.video.fen', and copy the 'favourites.db' file to somewhere safe. You can paste this file into another Kodi install's Fen user_data folder to replicate your favorites on another device.)

**Comment by Sanjjay** [comment]
Hi Tikipeter

Thank you for the quick response and same again for 1,3 and 4 requests much appreciated.

2. "Episodes" if you want to try out my fork below I copied the code from genesis addon to make it work in exodus. I couldn't add web channels like netflix , prime and other on demand episodes, only the one's on network providers would be good to have that also.

Code :- https://pastebin.com/raw/WMSaTUja

5. Backup favourites same again if have a look in my fork I copied and added it from another exodus fork awhile back. I couldn't get it to backup "watched status" and "views" from user addon_data folder.

Code :- https://pastebin.com/L6vj8qMr

https://github.com/Sanjjay/CustomAddons/blob/master/zips/repository.customaddons/repository.customaddons-0.0.3.zip
https://github.com/Sanjjay/CustomAddons/blob/master/zips/plugin.video.exodus/plugin.video.exodus/plugin.video.exodus-2.0.50.zip

Also a new request is there any way to scape this website https://www.dvdsreleasedates.com/ for new bluray releases weekly but only show 4 weeks in Main Menu. e.g show last 2 weeks of January and 2 weeks of February so it will only show the 4 weeks and 4th week being the latest updating every week and latest being at the top of the list. (Will need to separate Movies and TV shows).

Sorry I am not a coder I just copy and paste from other addons.

**Comment by Tikipeter** [comment]
I'm still looking into this..

**Comment by Tikipeter** [comment]
5. Backup and Restore added for live update (v.1.5.97).
Still thinking about 2).

**Comment by jaimsitecom** [comment]
> 1. Backup and Restore added for live update (v.1.5.97).
>    Still thinking about 2).

Thanks for this!  Great feature and Time saver!

**Comment by jaimsitecom** [comment]
I hope this doesn’t sound dumb. :)

Is it even possible to get a feature where removed failing scrapers get reinstated via set time (after 1hr, 12hrs, 24hours and never)?  I just find it too meticulous and too deep into the ‘openscraper settings’ to reinstate the disabled scrapers. Cause sometimes the disabled scraper works somedays and fails another time. So it would be nice if everyday/everytime i start my kodi with a complete set of scrapers. Then just let FEN prune it down along the day and just use the ‘working’ ones. Then gets reset to full ist again tomorrow. 

I hope my explanation made sense. Hehe

Thanks!
