### ISSUE TITLE
mdblist

### ISSUE THREAD

**Issue by Arthur1967** [Tikipeter/repository.tikipeter#13]
I know you're busy just making a suggestion is there any way you can add this it's a great way to personalize your TV shows and movie lists he is on github Thank you

**Comment by Tikipeter** [comment]
I'll look into it. I know the Umbrella dev recently implemented mdblists.

I need to see whether these mdblists are what made Trakt recently impose limits of list size on their members. If it's because of this mdblist, then I wont be implementing them as they are abusing Trakt's service.

If that's not the case, then I'll have a look...

**Comment by Tikipeter** [comment]
I'm afraid I won't be implementing mdblist. It looks to be a main contributer to Trakt deciding they needed to implement limits on users' lists.

I can't support something like that.

Relevant snippet from a Trakt dev who was corresponding with the dev of mdblist. Before this quoted post the Trakt dev was not aware he was conversing with the mdblist dev.

>I just realized you're the dev at mdblist.com 🤦 This is one of the sites allowing users to create massive lists and one of the main reasons we are implementing these limits. I appreciate your project for helping people be creative. Mblist itself has list and item limits, so I think you understand where we are coming from.
