### ISSUE TITLE
issues on foreign language titles with accented and special characters

### ISSUE THREAD

**Issue by powei94** [Tikipeter/repository.tikipeter#138]
Hi, I just noticed this bug when using foreign languages for tikimeta, accents get removed and special characters like 'ñ' are replaced by just 'n', great work on this addon btw! if you're ever planning on adding translations I'd love to help with spanish!

**Comment by Tikipeter** [comment]
Hi powei94

I'm going to have to think about this for a while.

The accents are removed because I had terrible trouble with python encoding/decoding and this was the only way i could solve my issues. It's possible I may have to leave it the way it is, because it took me a long time to solve those issues.

I will have a very hard think about it, though.....

**Comment by powei94** [comment]
Thank you for looking into this, I did some testing by modifying the build meta file and managed to let the accents and special characters stay, it worked fine on my end but I understand that issues might be a possibility, maybe a good approach for this could be to add an option to allow special characters on settings and leave it disabled by default, thank you for looking into this.

**Comment by Tikipeter** [comment]
Hi @powei94 

I could have a fix for this issue. Let me test it some more before I issue an update (I'm a little worried about encode/decode errors. Seriously, I spent a LONG time trying to fix those). It may be a full day from now before the update. :)

**Comment by powei94** [comment]
thank you! this will be pretty useful for most non english users!
