### ISSUE TITLE
Filenaming RealDebrid cached torrents

### ISSUE THREAD

**Issue by jaysamuel1976** [Tikipeter/repository.tikipeter#141]
First off, thanks for all your effort in making an amazing addon. 
When selecting a movie/episode all the Easynews results show the exact filename , the RD results don't. It shows the resolution, audioformat and used codecs for video but in feliname you can see releasegroup and other useful information.
Especially for searching the correct  subtitles, filenames are very useful. Is it possible to make the RD results show filenames to?

Thanks in advance..

**Comment by Tinuz97** [comment]
Files names would be awesome (Real Debrid, Premiumize) if possible, +1 for this idea.

**Comment by Tikipeter** [comment]
Hi jaysamuel1976

(and of course Tinuz97) :) :)

The problem is the file downloader grabs the name from the RESOLVED link, not the original URL that I would have to deal with.

It is possible, but to do this I think I'd need to use regex language, which I don't know. That's the main reason I can't do much with fixing scrapers or scraping websites.

Leave it with me though, because it is something that would be very nice to have......

**Comment by Tikipeter** [comment]
OK. I seem to have had some success with this, but the main problem may end up being room on the screen. Here is how Fen's INTERNAL scrapers look when "Show Filenames When Possible" is enabled/disabled:

DISABLED:
![without_filenames](https://user-images.githubusercontent.com/28930002/75249668-caa67a00-582a-11ea-97b6-f6926a6f0992.png)

ENABLED:
![with_filenames](https://user-images.githubusercontent.com/28930002/75249619-b3678c80-582a-11ea-9f36-67c10f9b6353.png)

These look fine. I move the "extra info" (HEVC | BLURAY | REMUX) up to the top line when the filename has to be shown, and put the filename on the bottom line. The trouble with the external sources is the top line is already full, because it shows something like "EXT | 4K | RD CACHED | LIMETORRENTS | TORRENT".  That's BEFORE adding any of the extra info.

I can get rid of "EXT" no worries, but I would probably have to get rid of "TORRENT" as well, just to make some room.

Plus, what about users who use single line?

**Comment by Tikipeter** [comment]
OK. I've made it behave the same way as Fen's internal scrapers, like you see above. I don't know how much use it will be for people using that Aeon Nox Silvo skin with the MASSIVE fonts, though. That was the whole reason to add a second line in the first place.

FILENAME & EXTRA INFO ENABLED:
![screenshot000](https://user-images.githubusercontent.com/28930002/75275611-ecb6f100-5858-11ea-830c-630328e00446.png)

JUST FILENAME ENABLED:
![screenshot002](https://user-images.githubusercontent.com/28930002/75275881-4ae3d400-5859-11ea-889a-0226d8c5be19.png)

JUST EXTRA INFO ENABLED:
![screenshot003](https://user-images.githubusercontent.com/28930002/75276037-87afcb00-5859-11ea-8a83-57db6067d65a.png)

**Comment by jaysamuel1976** [comment]
EXT/TORRENT/TORRENTPROVIDER are the least relevant extra info. Especially when using cached torrents i personally dont care where the torrent originated from. Single line users is a different thing, maybe when the displayed info is relevant ( filename/codec/audio channels) people start using single line :)

**Comment by Tinuz97** [comment]
Maybey a test zip (before pushing it), on a seperate folder on github?
Using Aeon nox silvo mod skin for years now 🙂

**Comment by Tikipeter** [comment]
I'll put a zip in the repo location (the one you add to file manager in Kodi to gain access to the repo zip). You can access and install it from there.

**Comment by Tikipeter** [comment]
OK. It should be in the repo location (plugin.video.fen-test-1.6.002a.zip).
Install from zip in Kodi...

**Comment by Tinuz97** [comment]
Already installed before this message, I am faster then Uber 😁

Testing in a moment.

**Comment by Tinuz97** [comment]
https://tinuz97.stackstorage.com/s/hHicBXJ5vxX32Qq

**Comment by Tinuz97** [comment]
It is not bad, because (also important for me) I still can see the filesize immediately, without to having to wait for the scrolling.

But dude, this is very cool!
Almost thinking of testing a different skin especially for it.
What skin do you use personally?

**Comment by Tikipeter** [comment]
Arctic Zephyr 2.
It's a beautiful skin with full customization.

**Comment by Tinuz97** [comment]
I realy like this 'show filename'.
So I am gonna try the artic skin, now Fen has everything that I like 👌

**Comment by Tinuz97** [comment]
![Screenshot_20200225-202810](https://user-images.githubusercontent.com/47715606/75280266-6c1ed300-580d-11ea-8b8a-0d538ae6df27.jpg)
Oh, this skin is nice 😍

This is just installed next to aeon nox silvo mod skin, and 2 minutes customizing.

**Comment by Tikipeter** [comment]
Looks great Tinuz! It's a little slower than Aeon, but once you get used to it it's fine. You get clearlogo art throughout, too. And a lot of different views.

**Comment by Tinuz97** [comment]
But only 2 views for the section in my screenshot? (that shows the links).

Going to start up my computer, doing this on the phone is horrible, the skin is not touchscreen friendly 🙁

**Comment by Tikipeter** [comment]
Yeah, that view is for files. Most skins only have a couple for that. The movie, tv show and episode views are much more plentiful.

Definitely not touch screen/mouse friendly.

**Comment by Tikipeter** [comment]
It is VERY hard to commit to changing skins though, when you are so used to a different one.

**Comment by Tinuz97** [comment]
![Screenshot_20200226-183626](https://user-images.githubusercontent.com/47715606/75371517-2e7e8080-58c7-11ea-9f84-ba7e789908bd.jpg)


Just wondering, now that Fen can read the filename, is it possible to also tweak the Duplicate file checker?
It does remove duplicates, but there are still much files the same. 

In theory (no idea real life lol) the duplicate filter maybey can remove more now if tweaked? (comparing the torrents in file name level, no idea if possible, just a idea that I did get few minutes ago).

**Comment by Tikipeter** [comment]
I've been thinking about that.The issue is each of these duplicately named files has a different torrent hash, because the duplicates of those get removed by me before sending to the debrid services for checking. So legitimate cached torrents could/would be lost by simply doing another duplicate check, because the hash is unique.

There may be another approach, though. Duplicate filenames could be removed once there's more than one instance for that debrid account. The rest are superfluous.
