### ISSUE TITLE
Payback failed via FEN scrape of Premiumize cloud

### ISSUE THREAD

**Issue by les017** [Tikipeter/repository.tikipeter#142]
Hi Tikipeter. Please see log [https://paste.kodi.tv/xopiluhiku](https://paste.kodi.tv/xopiluhiku) 

Episodes that I've manually saved and titled in Premiumize cloud seem to be having issues playing when I scrape from Next Episodes. Scrape works fine, locates episode but then fails to play. Message is "playback failed"

Episodes that are saved to Premiumize via scrape seem to play fine. 

When I play the manual cloud file directly it plays fine, even when using FEN-Services-Premiumize. Never saw this issue prior to . 40.  

EDIT:. I've triple checked the Premiumize episode file making format. And it seems it must be right since FEN finds the file on scrape.

**Comment by Tikipeter** [comment]
I don't see any playback attempted in that log file, so  it's no help to the actual Issue you have opened here. Send through another log AFTER attempting playback.

I do, however, see an error that the trakt database is malformed. So that needs to be fixed anyway. Go to Tools->Clear Databases & Clean Settings Files->Check for Corrupt Databases and run that. Hopefully that will fix the alformed trakt database. Otherwise you will have to go into addon_data and delete the db yourself and restart.

**Comment by les017** [comment]
Well that's interesting. I pulled that log immediately after 2 failed play-via-scrape attempts, one successful direct file play and then another failed play-via-scrape. 

But I'll go take care of the Trakt db. Thanks for that.
And when I get back I'll try to pull another log.

Thanks for the help

**Comment by Tikipeter** [comment]
The log is only 30 seconds long (`15:26:23` to `15:26:53`), so you would have had to have been REALLY fast. :)
Maybe the wrong one uploaded, or it got truncated somehow.

**Comment by les017** [comment]
Will I am fast, just not that fast. Hopefully I'll have you a new log by tomorrow. Thanks again

**Comment by les017** [comment]
@Tikipeter  I'm gonna close this for now, as I've found hidden/special character in the Premiumize file name. It threw me because I did my file name via copy and paste and several episodes played as expected. So they should have all been fine Now that I've corrected all seems good.

Both thanks, and sorry for causing, your attention
