### ISSUE TITLE
"Play" button on Next Episode window freezes Kodi

### ISSUE THREAD

**Issue by thenbhdlum** [Tikipeter/repository.tikipeter#147]
The "Play" button freezes Kodi when selected. If I exit out of Kodi and reopen the app, auto play resumes. This only works if I turn off either "Limit Resolve Attempts to Selected Result Only" or "Disable Content Lookup Before Playback." If I turn on both or turn off both, I receive a "Playback Failed" notification when reopening Kodi. The next episode also auto plays if I select the "Close" button and manually stop the episode. This error only occurs on my Chromecast with Google TV 4K. I have the exact same setup on an onn. 4K box and a Shield TV Pro without this issue.

http://paste.kodi.tv/ociduyijah

**Comment by Tikipeter** [comment]
Owning a Shield as well, you're lucky it's only happening on the Chromecast.

Fen invokes the `self.stop()` player method when you select Play (to stop the previous stream), and some systems (mainly Android based) simply do not like it and freeze.

You only option is to select "Close" and then stop the stream yourself using the player controls. That should work. Otherwise, it's best to use another addon, as there's nothing I can do really do mitigate this.
