### ISSUE TITLE
Do not have ext_providers4.db

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#149]
After updating FEN last night I read the Changelog and follow the instructions. At first only FEN updated and Tikimeta would not...it gave an error so I restarted FEN then I was able to update Tikimeta. After that I went into my addon_data and saw I do not have ext_providers4.db.  I did have ext_providers3.db and ext_providers2.db.  In Tikimeta I do have metacache4.db and I had metacache3.db which I deleted.

**Comment by Tikipeter** [comment]
Fen will make the new database the first scrape for sources you do.

**Comment by ANHBOB** [comment]
I had deleted ext_providers2 and ext_providers3.db as you suggested, then after scraping I had ext_providers3.db back again. I do not have 4??

**Comment by Tikipeter** [comment]
Turns out I wrote that changelog and then decided NOT TO update the ext_providers cache number! So it is still at 3. I remember it was decided not change the number so Fen didn't lose the scraper success/fail stats which I've also got stored on that database.

As long as everything works it's OK the way it is.

**Comment by rrosajp** [comment]
@Tikipeter 
hi actually in fen ext_providers2.db become ext_providers3.db and in tikimeta metacache3.db become metacache4.db current update create this db file but it did not populate metacache4.db just for yr info.

**Comment by Tikipeter** [comment]
I can't even remember what I did anymore. I knew this update wiuld be a disaster.
