### ISSUE TITLE
Easynews 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#15]
Hey glad to see you back! Ive really been enjoying Fen since you brought it back. This is not an issue at all but just a question about easynews.

I am considering getting easynews to use in Fen. I had got it before but got a refund as I think Kodi 19 has had some issues playing links from from there  and sometimes it would just fail to play which would get frustrating. I saw that you included some new settings that might possibly help with this but I just wanted to find out how effective they are and if easynews is working any better now that you have implemented these changes.

Thanks!

**Comment by Tikipeter** [comment]
I'm having a much better time with Easynews these days. But I've done about all I can to make it work as best it can....

* Used these network settings in Kodi's `advancedsettings.xml` file:
```
<network>
        <disablehttp2>true</disablehttp2>
        <disableipv6>true</disableipv6>
        <curlclienttimeout>60</curlclienttimeout>
</network> 
```

* Went onto Easynews website and chose the quickest server for me (they have a testing page).
* In Settings->Providers->Easynews I have `Disbale SSL Connections for Playback` ENABLED.
* In Settings->Playback->Playback Utilities I have:
                 - `Disable Content Lookup Before Playback` ENABLED.
                 - `Monitor Successful Playback` ENABLED

With these settings I very rarely have an Easynews source not play. If it does fail, the `Monitor Successful Playback` function will see that it failed, and attempt to play it a second time. That would normally be enough to get it to play.

I'm much happier than I used to be with Easynews because of all of the above.

**Comment by IG2022** [comment]
> I'm having a much better time with Easynews these days. But I've done about all I can to make it work as best it can....
> 
> * Used these network settings in Kodi's `advancedsettings.xml` file:
> 
> ```
> <network>
>         <disablehttp2>true</disablehttp2>
>         <disableipv6>true</disableipv6>
>         <curlclienttimeout>60</curlclienttimeout>
> </network> 
> ```
> 
> * Went onto Easynews website and chose the quickest server for me (they have a testing page).
> * In Settings->Providers->Easynews I have `Disbale SSL Connections for Playback` ENABLED.
> * In Settings->Playback->Playback Utilities I have:
>   - `Disable Content Lookup Before Playback` ENABLED.
>   - `Monitor Successful Playback` ENABLED
> 
> With these settings I very rarely have an Easynews source not play. If it does fail, the `Monitor Successful Playback` function will see that it failed, and attempt to play it a second time. That would normally be enough to get it to play.
> 
> I'm much happier than I used to be with Easynews because of all of the above.

Thanks for the information, that's really helpful and makes my decision a little bit easier. If I do decide to go with them again I'll definitely take your advice and try to set my settings to what you have to try have the best experience possible. 

Thanks again I appreciate it.

**Comment by Tikipeter** [comment]
No worries.

Each of those steps seemed to incrementally improve Easynews' performance. I can't say which one was most beneficial, but likely setting the best server showed the largest improvement.
