### ISSUE TITLE
FEN not scraping internal sources

### ISSUE THREAD

**Issue by vinylity** [Tikipeter/repository.tikipeter#156]
Hi,

After the last update, FEN is no longer returning any results on Furk through Openmeta. I am able to see external sources with no problem. I have checked my Furk login and is correct and also the Furk scraper is enabled. I am also able  to access my saved content on Furk directly through "Premium" interface.

**Comment by Tikipeter** [comment]
Hi @vinylity 

Does it show results from Furk when you search directly through Fen?

**Comment by vinylity** [comment]
It doesn’t work inside of Fen either.

**Comment by Tikipeter** [comment]
Some things to consider:
* Make sure you have the Furk scraper enabled in Fen, not in Openscrapers by going to Settings->Internal Scrapers->Furk.
* Set "Search Moderation Level" for the Furk scraper to "No".
* Make sure your Furk scraper size limits are reasonable.
* Make sure there is an entry for the Furk API Key in Settings->Accounts->Furk (you don't have to enter it yourself, Fen will populate it so long as you have your Username and Password set).
* Turn off all other Scrapers in Fen apart from Furk (including External scrapers) and see if any Furk results come through.
* Take notice of what happens when trying to get results from just the Furk scraper. Does Kodi come up with a progress dialog? Does it take a few seconds where it looks like it's connecting to Furk before it comes back with no results, or is it an instantaneous showing of No Results?

When all else fails, it is always worth posting a log after replicating the issue. It may not have any info, but it is certainly worth me having a look...

**Comment by vinylity** [comment]
When I tried Furk alone it didn’t connect. Instantaneous showing of no results.

**Comment by tekknight** [comment]
I’m also having the same issue. No results for furk or easynews. I also noticed that when furk api is entered in settings by itself it won’t show furk status in the premium menu, but when you enter the username and password it shows up.

**Comment by Tikipeter** [comment]
Get me log files please.

**Comment by tekknight** [comment]
Sorry for not getting you the log earlier. Been super busy. Looks like I'm still having issues with this. here's the log.

https://pastebin.com/YexFK5XJ

**Comment by vinylity** [comment]
Thanks. I haven't had a chance to post my log, but I am happy you did. I am also still having the same issue with Furk. It looks like the dev closed this thread, but someone else opened another thread about this on the "issues" page. Maybe post your log link there?

**Comment by Tikipeter** [comment]
Please change Settings->Results->Display->Highlight Results Based On... to "SCRAPER" and see if that fixes the problem.

**Comment by tekknight** [comment]
Changing to scrapers fixed it. I’m finding sources now.

**Comment by vinylity** [comment]
Working for me as well. Thanks.

**Comment by Tikipeter** [comment]
Thanks for reporting back. A fix will be in the next update, so you can put that setting back to "Quality".

**Comment by vinylity** [comment]
New update fixed it. Changed the results back to “quality “ and it works now. Thanks.

**Comment by GGNIGHTSTIKE** [comment]
Through Real-debrid internal scrapers not showing results either.
