### ISSUE TITLE
Other Ratings in Extras Window 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#156]
Hi there. 

Would it be possible to have the ability to add other Ratings such as IMDB and Rotten tomatos in the extras window within fen? I saw a recent issue someone opened asking for these ratings and you mentioned it would slow down the addon but it could potentially be implemented in the extras window. I think this would be a great addition to the addon. I personally am trying to move away from heavier skins but what has stopped me is the inability to view these ratings on lighter skins. 

Sorry to open this right after you closed the other issue but I thought I'd ask while it's still fresh in your mind. 

Thanks!

**Comment by Tikipeter** [comment]
I'm halfway there. I've got the OMDb code sorted out (which will supply the info). I will even have a setting in the next update to enter your OMDb API key within Fen settings.

But it won't make the very next update, as it will take a bit of work to implement nicely within the Extras Window.

So the update after this one will hopefully have an option for these extra rating values.

I'll try and limit the new code to just this so I can get it out sooner rather than later.

It seems from their API I can get `metascore`, `rotten tomatos` and `imdb` ratings. As well as a brief sentence on the awards won by the movie/tvshow.

I'm not sure if that's the same ones heavy skins are able to get........

**Comment by IG2022** [comment]
> I'm halfway there. I've got the OMDb code sorted out (which will supply the info). I will even have a setting in the next update to enter your OMDb API key within Fen settings.
> 
> But it won't make the very next update, as it will take a bit of work to implement nicely within the Extras Window.
> 
> So the update after this one will hopefully have an option for these extra rating values.
> 
> I'll try and limit the new code to just this so I can get it out sooner rather than later.
> 
> It seems from their API I can get `metascore`, `rotten tomatos` and `imdb` ratings. As well as a brief sentence on the awards won by the movie/tvshow.
> 
> I'm not sure if that's the same ones heavy skins are able to get........

Thanks for your response! I'm really happy to hear that you are already working on this, that's great news. Honestly all I use is IMDB and rotten tomatos I think there might be some other options but those are what I enable just so things aren't too cluttered. No worries about getting it out in the next update I'm sure you want to do it right and Implement it in a clean way so I completely understand. 

I'm looking forward to seeing what you come up with and what it looks like. 

Thanks again!

**Comment by IG2022** [comment]
@Tikipeter This works really well and also looks great too! Thanks so much for adding this. I appreciate it.

**Comment by Tikipeter** [comment]
No worries.

Unfortunately I didn't really have any options as to where to place them. But it didn't turn out too bad.

**Comment by IG2022** [comment]
> No worries.
> 
> Unfortunately I didn't really have any options as to where to place them. But it didn't turn out too bad.

I think they are actually in the perfect place. Now I can start shifting away from the heavy skins. I came across your modified estuary skin and I'm trying it out now its working well. I'm enjoying using it.
