### ISSUE TITLE
Cosmetic issue. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#167]
All working fine, but you know me, I am from the details.
The new clean setting file dialog is not so great with Aeon nox silvo mod.
The previous pop-up (right corner above) did had no issues, is it possible to make it like the clear all cache dialog that pop ups, that one has no issues with the spinning wheel in front of it. 
![Screenshot_20200320-205122](https://user-images.githubusercontent.com/47715606/77201745-54292f00-6aed-11ea-89a7-b38a39ceee0f.jpg)

**Comment by Tinuz97** [comment]
(the spinning wheel does make it all dark for the clean setting file option dialog)

**Comment by Tinuz97** [comment]
Clear all cache looks great (so you can see the difference) 
![Screenshot_20200320-205848](https://user-images.githubusercontent.com/47715606/77201933-b08c4e80-6aed-11ea-8dc3-c939ab6b1a66.jpg)

**Comment by Tikipeter** [comment]
Funny, I don't get that spinning wheel in front. I'll add code to get rid of it if it appears for next update.

**Comment by Tinuz97** [comment]
Just a idea, if cleaning all cache, there is a pop-up afterwards, that confirms all cache is cleaned, maybey nice to add that to clean settings file also, comforts my OCD 🤣 (just a joke).

But same pop-up would be nice also, so it suits the clean all cache confirmation screen (just a idea)

**Comment by jaimsitecom** [comment]
Tikipeter, i’ve tried 1.6.08 and it’s definitely better than 1.6.05 but for my equipment (xiaomi mibox s with wired 100mb internet) the result scraped is still spotty, sometimes it plays thru or crashes. So, again, i went back to 1.6.04 because it’s super fast and reliable and simply is the best match for my machine. My question is, will there be an issue if i stick to this version and forever rely on external ‘resolveurl’ scrapes?  Will i get locked out and this version be eventually unusable in the future?  I just love this 1604 version! Hehe

**Comment by Tinuz97** [comment]
This is realy nice fixed for aeon nox silvo mod skin, Fen 1.6.09, thx. Look good now. 
![Screenshot_20200322-021953](https://user-images.githubusercontent.com/47715606/77240226-caa85880-6be3-11ea-8b5a-06e02644a76d.jpg)

**Comment by jaimsitecom** [comment]
@Tikipeter hi again. Wow!  I bit the bullet and updated to 1.6.09 and also to the latest tiki meta module, and everything worked perfectly on my mibox S.  Even faster than 1.6.04 i think. Yay!  Thanks again TikiPeter!!!
