### ISSUE TITLE
3 computers no plot text etc dont know why less sources also 

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#168]
the header dont need more info, i cant get plot text on 3 computers with fen :( please help i want to see what episodes is about:( also almost no sources on tw shows, there was many before, and also hd withoud debrid

**Comment by cabban** [comment]
![image](https://user-images.githubusercontent.com/19514493/77227247-33a9b500-6b7f-11ea-833a-1d99383e9f94.png)
![image](https://user-images.githubusercontent.com/19514493/77227249-3ad0c300-6b7f-11ea-915b-5e343c76af2f.png)
![image](https://user-images.githubusercontent.com/19514493/77227259-4d4afc80-6b7f-11ea-9366-217d357b3444.png)
![image](https://user-images.githubusercontent.com/19514493/77227271-576cfb00-6b7f-11ea-9cfb-243c8fe8a5f7.png)


only ex on the issue please, dont say its not a bug :( @Tikipeter

**Comment by cabban** [comment]
![image](https://user-images.githubusercontent.com/19514493/77227334-f560c580-6b7f-11ea-8b0d-03ab03fa6e5f.png)
venom

**Comment by cabban** [comment]
![image](https://user-images.githubusercontent.com/19514493/77227342-08739580-6b80-11ea-992a-06384aef6d73.png)
venom

**Comment by Tinuz97** [comment]
Hmz, my plot is gone also for me for allot of shows (not all) (just check it with 1.6.08), other issues no idea, because I am using Realdebrid and premiumize (so plenty of sources for me).
The Flash shows plot information, but for allot of shows it is gone indeed, no idea if this is a Fen issue. 
![Screenshot_20200321-151345](https://user-images.githubusercontent.com/47715606/77228327-c9950e00-6b86-11ea-8d6c-20057dac6e4e.jpg)

**Comment by Tinuz97** [comment]
Question.
Do you have changed the meta language like me in your own language? (in my situation I have set it to Dutch).
Maybey the plot info does not work because of that (did before, because if it did not find Dutch language, it did switch back to English for that movie or TV show).

Going to test it in a minute if that will fix it.

**Comment by Tinuz97** [comment]
Yes, that fixes it @Tikipeter.
I think the switch is broken in tiki meta, because if I change the language in tiki meta from Dutch to English, the plot shows for this MacGyver show.

If I set it back to Dutch, it is broken (does not show the plot) 

Zet to English is fine, so I think the switch got broken after the tiki meta module update (automatically switch to English if the other language could not be found) 
![Screenshot_20200321-151955](https://user-images.githubusercontent.com/47715606/77228425-b0d92800-6b87-11ea-9e7d-940ffa443910.jpg)

**Comment by Tinuz97** [comment]
Set to Dutch (in tiki meta module, cleaned meta module cache), gone. 
![Screenshot_20200321-152412](https://user-images.githubusercontent.com/47715606/77228489-1b8a6380-6b88-11ea-8579-7b5d69c1fd35.jpg)

**Comment by Tinuz97** [comment]
So @cabban, can you test this also to verify my findings?
Go to tiki meta module, change the language for meta data to English, and check if you see the plot again like me.

**Comment by cabban** [comment]
> So @cabban, can you test this also to verify my findings?
> Go to tiki meta module, change the language for meta data to English, and check if you see the plot again like me.

@Tinuz97  yes it its fen related,, to meta data now english plot is there, swedish none :P 
manyu shows none links work for ;(  i not watch so often, but i know it worked before :)

**Comment by Tikipeter** [comment]
Alright, I'll be home in a few hours to look into this.

In case you both aren't available by then, can someone let  me know if you get plot synopsis at the TV Show level? I can see from the examples the episode level is often missing plot.

**Comment by Tinuz97** [comment]
Yes, TV Show level does work (MacGyver) in Dutch language.
![Screenshot_20200321-185816](https://user-images.githubusercontent.com/47715606/77233181-1805d500-6ba6-11ea-8e09-587c03fe4cb5.jpg)

**Comment by Tinuz97** [comment]
I think the switch is broken if that is the correct term for this, the piece of code (I think) that will show English as fallback, if, for example, Dutch language is not available.

If Dutch is not available (episode level), the field is blank.
Previous versions it did work (I had the issue in the past, but you did fix it after making a ticket on github) :)

**Comment by Tikipeter** [comment]
Yes, I remember. For my sanity I hope it's something TVDb changed on their end.

**Comment by jaimsitecom** [comment]
Mine’s all ok since it’s set in english.

**Comment by Tinuz97** [comment]
> Mine’s all ok since it’s set in english.

Yes, English works fine, only other languages is causing this (dutch in my situation)

**Comment by jaimsitecom** [comment]
Hey Tinuz97, you think i’ll have a problem if i stay stuck in ver 1.6.04?  My android box works so well with it, but not with 1.6.08. I ‘m just worried it will stop working eventually.

**Comment by Tikipeter** [comment]
@Tinuz97 do you get English as backup at TV Show level when Dutch is not available?

**Comment by Tinuz97** [comment]
> @Tinuz97 do you get English as backup at TV Show level when Dutch is not available?

Yes, so the issue is at episode level, set to Dutch, fallback to English works at tv show level 
![Screenshot_20200321-192708](https://user-images.githubusercontent.com/47715606/77233793-19390100-6baa-11ea-983d-3ed9c4311f18.jpg)

**Comment by Tikipeter** [comment]
@jaimsitecom 
A developer of an addon is always going to tell you to keep updated, so I will do the same. It is always better to sort out  issues rather than stay with older versions.

In saying that, if you want to stay with an older version, be sure to turn off auto update for both the Tiki modules depended upon by Fen (Tikimeta being the most important). As a for instance, to fix this issue here I will have to change Tikimeta code. I may then have to change Fen code to use the different Tikimeta code. If you've updated one and not the other then that's the end of old version Fen working for you.

**Comment by jaimsitecom** [comment]
Got it. I ll turn off both auto update switches then. Thanks again.

**Comment by Tikipeter** [comment]
@cabban 
@Tinuz97 
There should be a fix in the next update. Let me know if it is giving the wrong plot for an episode when it falls back to English.

**Comment by cabban** [comment]
Thank u :-)

lördag 21 mars 2020 skrev Tikipeter <notifications@github.com>:

**Comment by Tikipeter** [comment]
@cabban 
I will look into the scraper results problem, but there is probably not anything I can do.

**Comment by Tinuz97** [comment]
> @cabban
> I will look into the scraper results problem, but there is probably not anything I can do.

Maybey he has 'disable not working' scrapers enabled? Sometimes a scraper is not working, and a few day(s) later it is working again.

**Comment by Tikipeter** [comment]
> Maybey he has 'disable not working' scrapers enabled? Sometimes a scraper is not working, and a few day(s) later it is working again.

Very true. If you are only relying on free sources it would be best to have 'disable not working' OFF to give yourself the best chance of getting results.

**Comment by Tinuz97** [comment]
![Screenshot_20200322-020555](https://user-images.githubusercontent.com/47715606/77240042-bcf1d380-6be1-11ea-93f2-955e3d7f0378.jpg)

Fix working, 1.6.09, am I fast or what, lol.
(set to Dutch, cleaned meta cache, fallback to English working 100%)

**Comment by Tinuz97** [comment]
But found a other issue I guess @Tikipeter.
Birds of Prey is released (1080p EVO release).
Working in Tempest (cached), Fen does find zero links (also in the scraping screen zero) , any idea?

Tempest :
![Screenshot_20200322-021033](https://user-images.githubusercontent.com/47715606/77240122-9c764900-6be2-11ea-85e0-37d5adde3b71.jpg)

**Comment by Tinuz97** [comment]
Could the long name cause this maybey, or the (movie name), no idea how to call this in English () 
![Screenshot_20200322-021344__01](https://user-images.githubusercontent.com/47715606/77240156-fd9e1c80-6be2-11ea-8a6b-1ede11f590e0.jpg)

**Comment by Tinuz97** [comment]
> But found a other issue I guess @Tikipeter.
> Birds of Prey is released (1080p EVO release).
> Working in Tempest (cached), Fen does find zero links (also in the scraping screen zero) , any idea?
> 
> Tempest :
> ![Screenshot_20200322-021033](https://user-images.githubusercontent.com/47715606/77240122-9c764900-6be2-11ea-85e0-37d5adde3b71.jpg)

It shows 1(cached) now after cleaning all options in Fen, but not as many as Tempest does,weird.

**Comment by cabban** [comment]
Maybe it's so guys thank u for help anyway
Can u send screen shot of great settings to enable and disable in fen
And tip of cheapest debrid option :-)

söndag 22 mars 2020 skrev Tikipeter <notifications@github.com>:

**Comment by cabban** [comment]
maybe its this cause still 
i have 0-2 sources m i reinstall fen , no different 
https://troypoint.com/tv-shows-not-working-in-kodi-cdata-error-solutions/
