### ISSUE TITLE
Feature Request - folder as widget 

### ISSUE THREAD

**Issue by SJ50** [Tikipeter/repository.tikipeter#171]
I have very big curated library and I am maintaining it very well. I am using FEN library integration option so there are no duplicates.
I like to have widget which shows recently added movies in folder, but can not do it via library otherwise I will have everything duplicated.
There is option to add folder as widget but it is not working (just keeps loading) and there is no sorting option, no image and metadata. 
If you can add this feature where we can add folder as widget with metadata and artwork.

**Comment by Tikipeter** [comment]
Unfortunately, I don't fully understand what you are asking for here, SJ50. Well, I kind of do understand, but it should already be possible with what Fen currently offers.

Could you answer a few questions to give me a better understanding?

* Do you have PHYSICAL media that you use for your library (video files on hard drives etc)?
* Do you then ALSO have some library items from Fen (.strm files made by Fen Subscriptions)?
* Why is everything duplicated if you make a widget using Kodi's built in 'Recently Added' for a widget?
* Have you tried Fen->Kodi Library->Recently Added Movies as a path for your widget (is that the one you are saying doesn't work)?

**Comment by SJ50** [comment]
Sorry for all the confusion in my first post.

Do you have PHYSICAL media that you use for your library (video files on hard drives etc)?
- Yes I have PHYSICAL media and I am accessing it by "Folder Scraper" 

Do you then ALSO have some library items from Fen (.strm files made by Fen Subscriptions)?
- Yes by using Trakt subscriptions feature

Why is everything duplicated if you make a widget using Kodi's built in 'Recently Added' for a widget?
- I have added SOURCES FOLDERS as widget but there is no artwork, metadata and can not sort by recently added, it is just plain list of media. If I add my physical media folder as library in Kodi than it will duplicate.

Have you tried Fen->Kodi Library->Recently Added Movies as a path for your widget (is that the one you are saying doesn't work)?
- This also lists media which I do not have physically. 

I want recently added movies in Folder (Physical media) as widget.
I hope this clears confusion.

**Comment by Tikipeter** [comment]
I'll be honest SJ50, I'm trying to understand your setup because I can't really do what you are asking. The Folders aren't setup to work that way in Fen. It is possible to scrape the Folders using the name of the folder, but it will be very slow and not satisfactory. I'm hoping there's a better way for you to approach the issue.

The main problem is you are pretty well doing things back to front. You have Physical media that IS NOT scanned into your local Kodi Library, and you have Online media (Fen Subscriptions) that IS scanned into your Kodi Library.

I feel you have 2 options...

1. Scan your Physical media into your Kodi Library also, then everything is in one place (the physical media and the online media). Fen has a 'Local Library' scraper that will pick up your library items then (instead of using the Folder scrapers) You can then make widgets using Kodi's default 'Recently' lists. OR.....

2. Get rid of your Subscriptions in Fen, and as such your Kodi Library altogether. Instead, add the items in your Physical media to your Trakt Collections, so all your media (physical and online) is now represented by your Trakt Collections. Then make widgets based on your Trakt Collections. There are 'Trakt Widgets' within the 'My Trakt' menu that includes 'Recently Added' for Movies and TV Shows and 'Recently Aired' for Episodes that acts the same as recently added. Keep the 'Folder' scrapers set up as you have them now, and Fen will play the local file if it's in your Folders or go and search online if it is not.

The second approach is how I have ended up having my setup (I also have a mix of physical media and media I need to stream from online).

**Comment by SJ50** [comment]
I have second option setup but I am using subscription as well, with your above suggestion widget will also show online media which I do not want.
example - I have FOO as physical and BAR as online I only want recently added FOO in widget not BAR.

**Comment by Tikipeter** [comment]
I'm sorry SJ50, Fen can not do what you are asking.
