### ISSUE TITLE
filter our external sources even it find source.

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#189]
@Tikipeter 
hi i thinks in external.py file  in def sourcesFilter(self): on line # 412 to 414 is with new update

`if include_nondebrid == 'true':
self.filter += [i for i in hoster_sources if not i['source'] in self.hostprDict and i['debridonly'] is False]
self.sources = self.filter`
is giving No Result dialog  where as it found sources.
if on line # 414 `self.sources = self.filter` is under if condition it will display and play the soureces.

**Comment by Tikipeter** [comment]
Thanks jigoop1.

I was aware of this, and there is already a fix for next update.

Amazingly, the problem was I was testing not importing resolveURL and didn't reverse that before I released the update. So `self.hostDict` was not being populated, meaning no relevant free hosters were being fetched by ResolveURL, meaning every free host was filtered out from the results.

**Comment by Tikipeter** [comment]
I should be able to release an update today some time.

**Comment by jigoop1** [comment]
thanks for prompt responce,  i really appreciate your hard work. and The dedication with which you work.
