### ISSUE TITLE
Studio logos not displaying correctly - trakt progress 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#190]
Hey I've noticed that when using trakt progress with Auramod studio logos are not displaying accurately I've posted this on the tmdb helper github to but after discussion I've been advised it may be plugin related

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/1033

Would you be able to take a look at it?

Kind regards

**Comment by Tikipeter** [comment]
Try with another Jurial skin and the same TMDbHelper version and report back.

P.S. Always do this when dealing with the Auramod skin. Because there is no way in the world I am installing that to test it.

AH2:

You:
![you](https://user-images.githubusercontent.com/28930002/226914804-524f6939-ff0b-4531-9c8b-e984a79db81e.png)

Servant:
![servant](https://user-images.githubusercontent.com/28930002/226914860-ec445ec3-8e71-4454-bb67-be13b81be016.png)

**Comment by JFG1000** [comment]
@Tikipeter decided to make the move to AH2 finally and I've got to say it's so sleek and nice shall I close these auramod ones now?

**Comment by Tikipeter** [comment]
I'll close them. Good idea making the switch.
