### ISSUE TITLE
 Request, not a issue. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#2]
First of all, nice clean, and fast addon, love the filter options also.
Is it possible to add 'sort by size' like Seren as a example?

The sorting in the settings are not able to choose sort by size as first option, that would be awesome if you could add that, so high to low filesize. 

Thx for this already great addon.

**Comment by Tikipeter** [comment]
Hi Tinuz97.

Thanks for the kind words.

Unfortunately, the external scrapers do not (and cannot) report back file sizes so I can't implement sorting by size without leaving them out of the sort, which pretty well defeats the purpose. Only the Furk/Easynews/Local and Download Folder results can be sorted by size.

Sorry about that. :(

**Comment by Tinuz97** [comment]
But most torrent scrapers do report filesize, like torrentapi, magnetdl, 1337x as a few examples.

Also not possible for the torrent scrapers?

**Comment by Tikipeter** [comment]
Not the way the External scrapers are made. They are direct copies of Exodus style scrapers, and I don't maintain any of them. I simply add ones that work from other people. These scrapers sometimes put size info into the 'info' field of what they return to Fen (mainly the torrent ones, like you said), but that isn't something I can reliably use for sorting. And almost none of the other External scrapers return any size info at all.

That's why you'll find any add-on that uses Exodus style scrapers will not be able to sort by size.

**Comment by Tinuz97** [comment]
Ah ok,that makes sense, thx for the information 👍
