### ISSUE TITLE
OpenSubtitles Login.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#201]
Is it possible to add a login for OpenSubtitles?
I received a email this morning, that they are going to block without logins:

API REQUESTS MUST BE AUTHENTICATED

With Covid-19 pandemic requests for our API went skyrocket, our servers could not handle so much traffic, so we decided to limit API usage just to authenticated requests for User Agents. In short it means, you have to provide opensubtitles.org username and password in LogIn() method.

We are avare some of user agents doesn't implement authentication for numerous reasons.

We are actively blocking IPs, which are sending unathenticated requests

**Comment by Tikipeter** [comment]
It should be OK for Fen. I use their JSON API instead of the old XML API that Exodus forks use, so there should be no need to login to get subtitles in Fen. I've had another look at their documentation, and there is still no endpoint to login using the JSON API, so hopefully it stays that way.

You will need any Exodus forks you use to have login ability (I know host505 has done it with TheOath).

**Comment by Tikipeter** [comment]
I had an extra look in their forums, and a user had asked this question regarding the API Fen uses.
Here's a relevant snippet from the reply by Admin:

> this REST API doesn't need authentication.

Hopefully there isn't an issue with how they are monitoring this, I use subtitles heavily and don't want my IP address banned! I'm sure you feel the same.

**Comment by Tinuz97** [comment]
Yes exactly, that is why I did open a ticket :)

But sounds ok, not worried anymore 😄
