### ISSUE TITLE
IMDb integration

### ISSUE THREAD

**Issue by jaysamuel1976** [Tikipeter/repository.tikipeter#204]
My wife uses IMDb to add movies to her
watchlist. Told her to use trakt, but she shares IMDb links with her Friends. Is there any way of adding her IMDb user credentials to view her watchlist? It used to be present in Exodus and Convenant addon.
Thanks in advance!

**Comment by Tikipeter** [comment]
I need to think about this.

Because Fen's main menus are made to be dynamic (i.e. you can move/remove/add items to the Main (Root), Movie and TV Show menus), I will need to find a spot for IMDb in another sub-menu where I can control it's visibility.

I'm thinking I could rename "My Trakt Lists" on the Main menu to "My Lists", then I could put the IMDb Watchlist in there (and maybe the users created IMDb lists).

Let me think about it for a while, because I should clean up the default Main, Movie and TV Show lists as well, so I might do this at the same time.

**Comment by Tikipeter** [comment]
This is included in latest update. Please read change log regarding Menu resets.

Any troubles with IMDb, send me another issue. :)
