### ISSUE TITLE
Very Slow widget scrolling 

### ISSUE THREAD

**Issue by trkselim1** [Tikipeter/repository.tikipeter#215]
Hi
Thank you for this beautiful addon
I have a little problem
In (sittings) open extend info when 
selecting When i select( both) widgets scrolling fast
But when I select (non) the widget scrolling very very slow
I don’t want  to open extend info When I select movie or tv show
It’s happened in my tvbox (Coreleec) 
And laptop (Windows)
I don’t know what to do

**Comment by Tikipeter** [comment]
Hi trkselim1.
I'm confused as to what you mean by "widget scrolling". Could you please explain what you mean.

**Comment by trkselim1** [comment]
The widget movement in the home screen

**Comment by xyzfre** [comment]
> The widget movement in the home screen
> This what happened when open extend info select (both)
> https://imgur.com/gallery/0cJ4FXN
> 
> This what happened when I select (none)
> 
> https://imgur.com/gallery/FQAonib
> 
> It’s very slow

You you don’t mind me asking what skin are you using

**Comment by trkselim1** [comment]
It’s titan bingie but I make it one row widgets

**Comment by Tikipeter** [comment]
I'm afraid I have absolutely no idea why this might be happening. From the video, it looks like the artwork is downloading to be displayed for the first time, but I assume you have navigated that list before and that is not the case.

I installed the AuraMOD skin and set up a widget and it did not behave like the one in your video. I don't really have anything to suggest to try and fix the problem. Maybe try removing the widget and re-adding it. If the widget points to a very large list perhaps try a widget with a smaller list and see if the behavior stops.

It's a long shot, but perhaps a fresh log will show something out of the ordinary (by fresh log, I mean restart Kodi, let the widgets load, navigate through the problematic widget and then send through that log).

**Comment by trkselim1** [comment]
Hi tikipeter
I tried everything still the same problem
Install new kodi,3 deferent skins
If I select show extended info everything works fine
But whe I select none the widgets movement very slow 
Can u help

**Comment by pcliff069** [comment]
I don't know what has happened with the latest update. I can now only get it to play occasionally. Time outs while updating playlists between fen and trakt. And then just the buffering fox or whatevet it is for 10 minutes trying to load a show, I'm told there is a log somewhere but not on my TV or should I say not anywhere where i can download it. Back to Plex i fear. I really did like your app and appreciate all the work you put into it.

**Comment by Tikipeter** [comment]
@pcliff069 if you run Kodi there is ALWAYS a log. Anything to do with 'timeouts' are related to the online service related to that timeout i.e. if there is a Trakt timeout, that is because of a problem with the Trakt service. I cannot do anything about that. I don't know what a 'buffering fox' is, but if a show won't load that is also something outside of my control. Unfortunately, there is nothing in what you have written that would even begin to help me find out why you are having issues, and I really don't understand why you have overtaken someone else's Issue tab with a completely unrelated set of issues.

@trkselim1 I really can't help you more as the problem you are having is not reproducable by myself. I donwloaded and installed the skin specifically to test it against what you have reported as happening, and I can't replicate the problem. There is one thing left for you to try from my previous reply, maybe that is worth a shot for you?

**Comment by trkselim1** [comment]
Thanks tikipeter And still fen the best addon I have ever used 
Have a nice day 😊😊😊😊
