### ISSUE TITLE
still can’t add MARVELS Agents of SHIELD

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#217]
Hi again Tikipeter. I’ve mentioned this ‘bug’ to you before, that even if i’ve added this particular tv show into my Subscription list, it seems it cannot connect and link up with tvdb’s info about the show, thus it wont add into the library. I noticed that whenever i search for it in FEN’s tv search function, it comes out with the Title plus the year-  MARVELS Agent of SHIIELD (2013).  Is that the reason why it wont hook up with tvdb’s info?  Cause i notice when i try to add the show via a different video addon (venom) it only has the title without the year, and it populated the shows info and episodes properly, thus getting added into the kodi library. 

It’s a minor annoyance for me but just letting you know that the bug still exists. 

Thanks man!

**Comment by eeden003** [comment]
Well..... I've tested 10 add-ons with FREE links, with calender-function, with tv-shows function, with search-function, and.....all they find is MARVELS Agent of SHIIELD with NO seasons. Other titlles from MARVEL dó work perfectly ánd play !. So.....the developers should know what the problem is or can be !

**Comment by Tikipeter** [comment]
It will take a re-write of subscriptions to fix this issue, which means anyone using subscriptions would most likely have to set them up again. I can't do that at this stage. If you use the Kodi TMDb scraper for that show, it will add to library correctly.
