### ISSUE TITLE
Bug? Issue? Or am I doing something wrong perhaps. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#22]
Discovery, a great new, refreshing thing.
It did work great before the latest update, but now it is broken for me. 

The old list that I did create does work fine (I see my filtered movies in that one), but if I create a new filter list with Discovery, it does not show any movie unfortunately. 
I have no idea how to log this one in the kodi log, is it just me?

**Comment by Tikipeter** [comment]
Discover relies on setting properties held internally by Kodi. The first thing to test would be to simply restart Kodi, as that will clear any old properties from before the update. It should not stop you making new lists, though...
If the problem persists after a restart I will put some logging info into the coming update (v.1.5.43a).

**Comment by Tinuz97** [comment]
I did restart kodi, I even deleted the folder(s) from fen in the userdata location.

I can create a list, no problem, with the latest update. 
But it does not show any results (it did one version ago). 

Thx for the reply :)

**Comment by Tikipeter** [comment]
If you let me know the filters you set, I will duplicate it and try and see what's going on. Thanks if you can Tinuz97.

**Comment by Tinuz97** [comment]
I created a video of that is OK, for me easier as writing in English, I can upload it, and post a link.

**Comment by Tinuz97** [comment]
Here is the video, if it is not ok I will remove the comment :


https://tinuz97.stackstorage.com/s/AfFPHftlICS9bWN

**Comment by Tikipeter** [comment]
Thanks for the video Tinuz97. Much appreciated.

There are simply no movies that meet the filters you have set (the genres filter is the problem).

The genre filter acts as an AND filter not an OR filter. So it is searching for movies that have ALL those genres present. There isn't a movie on the TMDb website between 2015-2019 that meets ALL those genres, so it is not returning anything. When I took out the 'Family' genre, I did get 3 results, so it is working correctly. Playing with the 'Include Genres' along with the 'Exclude Genres' would get you a better result. Pick, say, the 3 most important of the Include Genres you currently have, and pick all the Exclude genres that you definitely don't want to have included and it should basically give you what you want, but without being quite so literal about it.

Just to make sure there isn't a problem with your install, run a simple search with minimal filters and make sure it gives results. Say just Movies 2018-2019 with no other filters. You can delete it from your history using the context menu afterwards so it doesn't get too cluttered. Otherwise, it was the restrictive genre filters that was the problem....

**Comment by Tinuz97** [comment]
Thx.
I did set the filter to only 2018/2019, and that did work,getting results. 
But weird that I did get results with previous update 😅

But it seems to work if I set only 2018/2019,i go play a little more with the filters.

**Comment by Tikipeter** [comment]
I appreciate you replying Tinuz97. I am going to close this for now, because the filters are working, but if you have any more troubles write back here and I will reopen this. There's a decent amount of code involved with this feature so I expect more problems. Plus, it's impossible to test all variables. :) :)
