### ISSUE TITLE
Firestick 4k: No Results from EasyNews

### ISSUE THREAD

**Issue by omen124** [Tikipeter/repository.tikipeter#229]
I have Fen 1.6.26 installed on Kodi 18.7 on a Firestick 4k and put the login details into Fen to access my Easynews account. When I search using the "services" part of Fen I get no results via searching or checking account details and when I go straight to a show or movie with Easynews as the only search option I get no results. When I check the account details via the services section I get an error message.

I went through every option I can find inside Fen looking for something I have missed, right now I have:

Disabled external sources so EasyNews is the only source that is being searched

Turned off mature content filtering.

Tried with and without the VPN active, all other applications are working (Netflix, etc).

Uninstalled Fen completely and reinstalled it twice being extra vigilant putting in the right details and it still doesn’t work.

Log: http://paste.kodi.tv/ifuyubekaz

**Comment by Tikipeter** [comment]
Hi @omen124 
Using the latest Fen version (1.7.02a), please get me another log after trying to check your Easynews account stats through Fen. It should give me some information. Previous versions of Fen, which your current posted log is from, had an error in the error reporting.

BTW, you need to have http access from your Easynews account to use it within Fen. I'm not sure if all the Easynews plans include this at the moment, it's been a while since I looked.

**Comment by omen124** [comment]
I installed the latest version of Fen and I checked the most recent log I got and there didn't seem to be anything I could spot. Maybe you can see it.
http://paste.kodi.tv/seyudufevo

I got an error when checking the account stats, the error said.
Error
'NoneType' object is not iterable.

Regarding the EasyNews account access, it should be enabled because I don't have any upgrade option to add that feature and NNTP is enabled along with anything else I could see. I won't rule out that it may be something I cant see though.

**Comment by Tikipeter** [comment]
> ...I assume would be the same protocol that Fen would use to stream.

It's most likely not the same protocol. Fen uses this http Easynews site:
https://members.easynews.com/2.0/

It is the only way Fen searches for Easynews content. It does not use the nntp protocol at all. If your login and password work on that site linked above, then there is a problem in Fen. If it does not work, then that is where the problem is. Your account needs to include "Browser Access to Usenet" as a feature.

Since I'm assuming you have triple checked your user/pass, all I can do is assure you that Easynews does work in Fen. I use it every day.

If you find you **CAN** login and search on the easynews site linked above, let me know, and I'll include a test build here for you to install that should let me see what the situation is.

**Comment by omen124** [comment]
Opening an Incognito page and going to https://members.easynews.com/2.0/ prompts me to log in and then takes me to https://members-beta.easynews.com/3.0/ where I can search for stuff (google style UI) and get results.

**Comment by Tikipeter** [comment]
Ok. That's good news.

I'll post a zip with a test file for you to install soon.

Please do 2 things when you test:
1. Test the Account Info like you have been doing.
2. Test the searching of a popular movie using only the internal Easynews scraper. Turn off all other scrapers.

Please then post the log here and hopefully I will see what your issue is...

**Comment by Tikipeter** [comment]
Here is a test zip:

[plugin.video.fen-1.7.03-test01.zip](https://github.com/Tikipeter/repository.tikipeter/files/4800617/plugin.video.fen-1.7.03-test01.zip)

If it is difficult to install an addon through zip due to accessibility issues, I have included the same file in the github.io source for this repository. In this case, you would select "Install form Zip" in Kodi,  then navigate to the source you added to Kodi to install the Tikipeter Repo. The test file will be there to select and install.

Don't forget to do the 2 tests in the post above, and send through your log file.

**Comment by omen124** [comment]
So to cover my methodology here, after uninstalling Fen and all settings, I then installed the test and logged into EasyNews.
I then enable the EasyNews internal scraper and turn off adult content filtering, I then turn off external scrapers (in the settings menu).
After going to services and choosing Easynews and looking at the account info I got the actual account details to show up on the screen (WONDERFUL!)
I then went to the movies section and searched trending got Zero results.
http://paste.kodi.tv/wicixabihi

**Comment by Tikipeter** [comment]
It looks like the redirect to 3.0 Beta of the members search area might be your problem. I'm looking for a way to stop Easynews redirecting to 3.0 Beta, and instead using 2.0 in the Easynews settings, but I haven't had any luck finding anything. Fen is not able to get results from 3.0 Beta, only 2.0.

If I can't find anything in the Easynews settings to prevent this redirect, it might be an idea for you to open a ticket with them, and let them know you don't want your account redirected to the 3.0 Beta members search page.

This doesn't look good at all.

**Comment by Tikipeter** [comment]
I may be able to stop redirects at the request stage in the code.
Let me post another test file. Give me a few minutes....

**Comment by Tikipeter** [comment]
No need to test the Account Info anymore. We know that's working. Please test a different popular movie (so the cache isn't used) with this test zip and post the log. I've added a "no_redirect" for the call, hopefully that is enough.

[plugin.video.fen-1.7.03-test02.zip](https://github.com/Tikipeter/repository.tikipeter/files/4801047/plugin.video.fen-1.7.03-test02.zip)

Zip file is also hosted on the repo address, like before. It may take some time for the contents of the repo address to refresh it's cache.

**Comment by omen124** [comment]
Did a reinstall/update to test02 without wiping settings.
No search results found. Tried a movie and tried searching via the services menu.

Log: http://paste.kodi.tv/ipaperuvip

**Comment by Tikipeter** [comment]
> ...are you able to use the 2.0 UI?

Yes. I hadn't heard of or seen the 3.0 Beta site until you said you were redirected there.

Unfortunately, I am in a situation I am not familiar with code wise. I looked up the requests module that is used to make the call to the Easynews website in Fen, and it says it has a "no_redirect" pararmeter that can be set. I've set that now for Easynews with the last test file, and it hasn't worked it seems.

I'm going to keep looking for a solution, but I strongly suggest now that you try and get Easynews to stop redirecting you to the version 3.0 Beta members search site. They are certainly not doing that with my account, and I can search in Fen as a result. Tell them you want to use the 2.0 website and not the 3.0 Beta.

In the meantime, I'll keep looking for a solution on my end....

**Comment by Tikipeter** [comment]
Try seeing if you are redirected when navigating to the following url. It is the version 2.0 url, only http instead of https:
http://members.easynews.com/2.0/

Did this one redirect you?

**Comment by omen124** [comment]
I have messaged EasyNews about the 2.0 site.
The link still redirects to 3.0 beta. I suspect since my account is new (made after 3.0 was released) that 2.0 is not a default option they offer or it may be the account type I am using. Hopefully, the EN team can get back to me with this information.
It would be nice to get 3.0 beta working though as this problem will probably only become more frequent as people sign up.

**Comment by Tikipeter** [comment]
> ...It would be nice to get 3.0 beta working though as this problem will probably only become more frequent as people sign up.

You are right about that. It's not something I'm very good at though (scraping web sites). Actually, that's an understatement. I've never learnt how.

Unfortunately, Easynews don't provide an API to access their search, so it's going to be tough for me.

**Comment by omen124** [comment]
I have heard back from EasyNews and they have told me that my account is only 3.0, I would have to downgrade to an older deal to get 2.0
The deal I got when signing up is unlimited web/NNTP at with a 20% discount for the yearly rate. Usually, they have limited downloads for their older deals and offer unlimited downloads to their longer loyalty customers later.
Hopefully, you can get 3.0 working as well. I have also tried Gaia and they also have difficulty with the 3.0 UI and currently are doing an overhaul that will arrive in a month or two. But their UI/structure for browsing is clunky and unintuitive and doesn't integrate as well with Trakt (offering colours and checkmarks) compared to Fen.
As you have stated the scraping is a weak point and I can see the difference between Gaia with its multiple scrapers and different techniques, but that is a side benefit for me as EasyNews should be my main source.

I don't know if I can trust the Gaia people as much because when I contacted them they asked if they could use my account details to do some testing up until the next release and then I would have to change my password.

**Comment by Tikipeter** [comment]
I can't speak as to the trustworthiness of the Gaia devs. Them asking to borrow your account would normally be due to the fact they don't have an Easynews account to test with. But I can certainly understand not wanting to "lend" someone your account.

I will keep looking for a solution for this.....

**Comment by Tikipeter** [comment]
@omen124 

Here is a test file for you to try. Let me know if it works (v.1.7.04a):
[plugin.video.fen-1.7.04a.zip](https://github.com/Tikipeter/repository.tikipeter/files/4809371/plugin.video.fen-1.7.04a.zip)

**Comment by omen124** [comment]
Tested and there were no results when searching only with EasyNews/Services search.
http://paste.kodi.tv/kizerikejo
I did not remove the settings during the reinstall and tried searching for a new movie.

**Comment by Tikipeter** [comment]
Damn.

OK. Please try this file with the new movie "You Should Have Left", which I know has only 3 results. I'm logging the progress of the search, to see what's going wrong.

[plugin.video.fen-1.7.04b.zip](https://github.com/Tikipeter/repository.tikipeter/files/4810254/plugin.video.fen-1.7.04b.zip)

**Comment by omen124** [comment]
Same uninstall/reinstall. External scrapers off, the only internal scraper is EasyNews.
No results from manually typing the movie name in the services section.
No result from selecting the movie in recent releases.
Log: http://paste.kodi.tv/dumetukisu

**Comment by Tikipeter** [comment]
I'm afraid that was my last chance to get this working.
I'm going to keep looking for a way, but at the moment I'm afraid I can't help you omen124.
