### ISSUE TITLE
Fen Autoplay chooses the largest GB file possible

### ISSUE THREAD

**Issue by NickPodsiadlo** [Tikipeter/repository.tikipeter#233]
This isn't so much an "issue", but rather a feature request. Fen will default to the largest GB file possible. If there is a 4k movie it will choose the ridiculous 65GB file vs the 15GB file that looks exactly the same. For a 25 minute TV episode it will default to the ridiculous 5GB file when the 0.89 GB file looks exactly the same.

I have a 1000GB monthly data limit so this will fill up very quickly if I'm spending 5 GB on 25 minute episodes. Therefore I have to just ignore the feature entirely which sucks because it's great for automatically playing the next episode.

In the autoplay section it would be nice to set a GB limit for each Quality.

**Comment by Tikipeter** [comment]
Just use the size filter settings that are already there.

I don't see a need for autoplay specific size filtering.

**Comment by NickPodsiadlo** [comment]
> Just use the size filter settings that are already there.
> 
> I don't see a need for autoplay specific size filtering.

Okay, thank you. I guess I didn't look hard enough for that option... I will look again.

**Comment by NickPodsiadlo** [comment]
> Just use the size filter settings that are already there.
> 
> I don't see a need for autoplay specific size filtering.

I found the size filter option you were talking about which is not helpful for what I was explaining here. There should be filtering options specifically for movies and for TV shows and specific to quality. I am fine with a 15GB 4k movie, while I am not fine with a 5GB 25 minute episodes.

With the current filtering options all I can do is set a max file size. So if I set that at 15GB, sure it cuts out the large 4k files but it does nothing for the episodes that I want to be under 1GB. If I set the filter to 1GB then I just can't ever watch any movies so the system is indeed flawed.

You don't seem too interested in this recommendation which is fine, I guess I will just use something else or try to fork this and figure out adding the feature myself.

**Comment by les017** [comment]
@NickPodsiadlo   I can agree that separate movie and TV tunings could be great, as I see things similarly to you.

But I've had great success switching from FILE SIZE to DATA RATE. If you play with the values you should also have success, as the data rate calculation will let you set up in a manner that will cap your results on a Mbps value rather than absolute file size.

For example my results are consistent where the biggest 30 minute episode I get is about 4GB, the largest 1 hour drama I get is about 8GB and the largest 2 hour movie I get is about 16GB.

try it

**Comment by NickPodsiadlo** [comment]
> @NickPodsiadlo I can agree that separate movie and TV tunings could be great, as I see things similarly to you.
> 
> But I've had great success switching from FILE SIZE to DATA RATE. If you play with the values you should also have success, as the data rate calculation will let you set up in a manner that will cap your results on a Mbps value rather than absolute file size.
> 
> For example my results are consistent where the biggest 30 minute episode I get is about 4GB, the largest 1 hour drama I get is about 8GB and the largest 2 hour movie I get is about 16GB.
> 
> try it

Thanks for that recommendation, I will try that out!

**Comment by Tikipeter** [comment]
>You don't seem too interested in this recommendation which is fine, I guess I will just use something else or try to fork this and figure out adding the feature myself.

What, no apology to me for you being wrong and accusing me of having no interest?

**Comment by NickPodsiadlo** [comment]
> > You don't seem too interested in this recommendation which is fine, I guess I will just use something else or try to fork this and figure out adding the feature myself.
> 
> What, no apology to me for you being wrong and accusing me of having no interest?

Lmao wtf, I don't owe you anything Tiki. I wasn't wrong about anything other than the fact that you already have a lackluster system for filtering. It's half ass, the other guy gave a decent suggestion but it is still FAR from ideal.

**Comment by Tikipeter** [comment]
Yep. That's pretty much how I thought you'd reply.

I'll be removing this functionality from next update.

Anyone using it I'm sorry, but it's not good enough for our boy Nick here.

He's let me know what he thinks of it, and who am I to argue?

Since it's such a half assed effort on my part, I really should get rid of it.

Thanks for the feedback Nick. :)

Anything else you have a problem with whilst we're here?

Please say the whole addon in general, so I can retire this thing once and for all.

Please.

**Comment by NickPodsiadlo** [comment]
> Yep. That's pretty much how I thought you'd reply.
> 
> I'll be removing this functionality from next update.
> 
> Anyone using it I'm sorry, but it's not good enough for our boy Nick here.
> 
> He's let me know what he thinks of it, and who am I to argue?
> 
> Since it's such a half assed effort on my part, I really should get rid of it.
> 
> Thanks for the feedback Nick. :)
> 
> Anything else you have a problem with whilst we're here?
> 
> Please say the whole addon in general, so I can retire this thing once and for all.
> 
> Please.

Retire it, I've already switched to Seren. I could care less, have fun being a salty little boy.

**Comment by xyzfre** [comment]
@NickPodsiadlo don't know why you Gotta be so disrespectful to somebody with such a great add-on blame yourself for having a shitty system limiting you to gigs being cheap cause you ain't got enough cash ,,upgrade your shit you fuck face because of people like you making stupid suggestions and don't know what you're doing  getting somebody like @Tikipeter upset Fen is the best addon out there but people like you just don't know how to use it fuck this person @Tikipeter let him use garbage add-ons probably using a fucking punk ass fire stick lol

**Comment by xyzfre** [comment]
> > Yep. That's pretty much how I thought you'd reply.
> 
> > 
> 
> > I'll be removing this functionality from next update.
> 
> > 
> 
> > Anyone using it I'm sorry, but it's not good enough for our boy Nick here.
> 
> > 
> 
> > He's let me know what he thinks of it, and who am I to argue?
> 
> > 
> 
> > Since it's such a half assed effort on my part, I really should get rid of it.
> 
> > 
> 
> > Thanks for the feedback Nick. :)
> 
> > 
> 
> > Anything else you have a problem with whilst we're here?
> 
> > 
> 
> > Please say the whole addon in general, so I can retire this thing once and for all.
> 
> > 
> 
> > Please.
> 
> 
> 
> Retire it, I've already switched to Seren. I could care less, have fun being a salty little boy. 

@NickPodsiadlo don't know why you Gotta be so disrespectful to somebody with such a great add-on blame yourself for having a shitty system limiting you to gigs being cheap cause you ain't got enough cash ,,upgrade your shit you fuck face because of people like you making stupid suggestions and don't know what you're doing  getting somebody like @Tikipeter upset Fen is the best addon out there but people like you just don't know how to use it fuck this person @Tikipeter let him use garbage add-ons probably using a fucking punk ass fire stick lol

**Comment by xyzfre** [comment]
> > Yep. That's pretty much how I thought you'd reply.
> 
> > 
> 
> > I'll be removing this functionality from next update.
> 
> > 
> 
> > Anyone using it I'm sorry, but it's not good enough for our boy Nick here.
> 
> > 
> 
> > He's let me know what he thinks of it, and who am I to argue?
> 
> > 
> 
> > Since it's such a half assed effort on my part, I really should get rid of it.
> 
> > 
> 
> > Thanks for the feedback Nick. :)
> 
> > 
> 
> > Anything else you have a problem with whilst we're here?
> 
> > 
> 
> > Please say the whole addon in general, so I can retire this thing once and for all.
> 
> > 
> 
> > Please.
> 
> 
> 
> Retire it, I've already switched to Seren. I could care less, have fun being a salty little boy. 

Use Seren that hasn't been maintained for a while and does nothing but errors specially if you look at your log but somebody like you might not even know how to do that or even paste a log lol,, I'm already using Omega with Fen working flawlessly and I can stream 30 minute episodes that can be up to 60/90 and plus gigs not have to worry about wasting anything cause I ain't cheap ,,sorry @Tikipeter You know I'm the nicest guy here but this guy really blew my mind

**Comment by Sauromayne** [comment]
> > > Yep. That's pretty much how I thought you'd reply.
> > 
> > 
> > > 
> > 
> > 
> > > I'll be removing this functionality from next update.
> > 
> > 
> > > 
> > 
> > 
> > > Anyone using it I'm sorry, but it's not good enough for our boy Nick here.
> > 
> > 
> > > 
> > 
> > 
> > > He's let me know what he thinks of it, and who am I to argue?
> > 
> > 
> > > 
> > 
> > 
> > > Since it's such a half assed effort on my part, I really should get rid of it.
> > 
> > 
> > > 
> > 
> > 
> > > Thanks for the feedback Nick. :)
> > 
> > 
> > > 
> > 
> > 
> > > Anything else you have a problem with whilst we're here?
> > 
> > 
> > > 
> > 
> > 
> > > Please say the whole addon in general, so I can retire this thing once and for all.
> > 
> > 
> > > 
> > 
> > 
> > > Please.
> > 
> > 
> > Retire it, I've already switched to Seren. I could care less, have fun being a salty little boy.
> 
> @NickPodsiadlo don't know why you Gotta be so disrespectful to somebody with such a great add-on blame yourself for having a shitty system limiting you to gigs being cheap cause you ain't got enough cash ,,upgrade your shit you fuck face because of people like you making stupid suggestions and don't know what you're doing getting somebody like @Tikipeter upset Fen is the best addon out there but people like you just don't know how to use it fuck this person @Tikipeter let him use garbage add-ons probably using a fucking punk ass fire stick lol

Not a stupid suggestion. I was trying to be helpful by making a recommendation and he is the one that got salty. [It's this simple](https://imgur.com/no559bA).

You are cute including my last name, I guess now I have to deal with a bunch of people harrassing me because I tried to make a simple suggestion and somebody got all upset. I would advise anybody against harassing me IRL, I have a lot of guns in my home and carry one with me wherever I go. So please feel free to harass me online however much you want but stay away from me IRL.
