### ISSUE TITLE
[Enhancement] Next-up based on chapters

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/repository.tikipeter#236]
Hey Peter, I hope you're well. I was wondering whether it would be possible for you to sync the TV show next-up function with the chapters of the particular video file you're watching. If you take a look here I've noticed a lot of TV shows have a final chapter for credits

![20230531_164950.jpg](https://github.com/Tikipeter/repository.tikipeter/assets/76912707/3c6cb27e-2b21-476b-9bf1-57ca408f748f)

![20230531_165609.jpg](https://github.com/Tikipeter/repository.tikipeter/assets/76912707/4101e4bf-153f-4c43-babc-72198c8a4903)

If the next-up function could appear along with the final credits chapter it would make for a better user experience imo. It would prevent the next-up from appearing too early or too late. Do you think this is possible, and if so would you consider implementing it? Thanks a lot for all your hard work.

**Comment by rizreflects** [comment]
No you're right, most of them don't. But there are a fair amount that have the chapter info aswell. The problem is the final chapter isn't always necessarily credits, but when it is it says the word 'credits' in the chapter title. Tbh it's far from a game changing enhancement, but if its easy enough for you to code in then I don't see why not. Seems like a nice feature to have, even if it's only used now and again.

**Comment by Tikipeter** [comment]
I decided I would add this.

I had all the code sorted out  and had the setting and everything done already, but the fact that the final chapter isn't always the credits gives me pause. I will add a check for the final chapter name being called "Credits" and see how that goes. I could also, when the name isn't available (this happened a fair bit when I was testing chapter info with movies), examine the value of the final chapter. If it is over maybe 95% of total playback time, then it is likely triggered by the credits.

I'll have a longer think about it, since I've done three quarters of the work already.

I just still can't find a single episode with chapters. But the tests I need to do I can do with movies instead.

**Comment by Tikipeter** [comment]
Chapter names is not reliable. I'll use the final chapter if it exists and is >= 90.

Settings->Playback->Episodes->"Use Chapter Info For Alert When Available"

**Comment by rizreflects** [comment]
> Chapter names is not reliable. I'll use the final chapter if it exists and is >= 90.
> 
> Settings->Playback->Episodes->"Use Chapter Info For Alert When Available"

That was much faster than expected. Thanks a lot! I think judging by percentage is probably more effective than chapter names anyway so good call. P.s. if you're still trying to find shows with the chapter infos, try the wu tang show on Hulu. I think each episode has had them so far.

**Comment by Tikipeter** [comment]
Kodi wouldn't even let me get the chapter name for the final chapter unless the player was within that chapter, so it as a bust. :)

Tried with Wu-Tang, and it's working well. Just after the credits start up pops the next ep window.

Good suggestion. Hopefully more files have chapters moving forward.

**Comment by TwilightMercy** [comment]
Can the settings be applied also to “Auto Scraper Next Episode”?
