### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by ke7doy** [Tikipeter/repository.tikipeter#241]
last night i had a problem where i had to re-install kodi.  after reinstalling fen and authorizing rd and enabling all coco scrapers i still get a no results error on all programs  paste.kodi.tv/rotomuhumi

**Comment by TwilightMercy** [comment]
RD is currently down

**Comment by ke7doy** [comment]
it does not seem to be related to rd outage.  in fen i get no results but if i use a browser i can access the results   and watch directly from the website..

**Comment by ke7doy** [comment]
this issue has nothing to do with the rd outage,  rd is working on my machine as evidenced  by the fact that it works on the same machine that i have real debrid installed.  when i try to play an episode in fen it shows a number of links are there, but even if vi scrape with all filters removed, not even uncached results appear.  maybe my api is defective?

**Comment by Tikipeter** [comment]
Fen is not able to access it's settings in time during start up.
```
error in make_settings_dict###: [Errno 2] No such file or directory: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.fen/settings.xml'
```

1. Make sure that settings file exists.
2. Disable all Fen widgets, restart and see if Fen functions properly.
3. If Fen functions correctly when widgets are disabled, enable Settings->General->"Wait for Fen Services to Initiate Before Making Widgets", re-enable the Fen widgets, restart Kodi and see if that fixes the issue.
4. If issue not fixed by 3 when widgets are re-enabled, then you will either have to not use Fen widgets, or use a different addon. Umbrella uses the same scrapers as Fen, and is actively maintained.

**Comment by ke7doy** [comment]
yay! i replaced the settings file and it worked.  not sure what a widget is, but i guess i do not have to worry about that. i  hear a lot about them though and i am curious.
