### ISSUE TITLE
Easynews not pulling links and no results when searching in premium services

### ISSUE THREAD

**Issue by Aguzy** [Tikipeter/repository.tikipeter#244]
Hi, I just recently started using easynews and have integrated it into fen but no matter what I try it will not pull links or give any results when searched in the premium services part of the addon. I don't know if this is because of the new 3.0 as I'm clueless with this sort of thing but would it be possible to fix this. Thank you

**Comment by Tikipeter** [comment]
Hi @Aguzy 

Unfortunately, it would be because of the 3.0 change to Easynews. Fen is not yet able to access files from this new version.

I've been busy with another project for a couple of weeks, but I intend to look into this issue soon.

As an aside, it might be worth you tracking down a fairly new add-on called "Shadow", which has Easynews support taken from Fen. It is claimed in their log that they "fixed Easynews" a little while ago.

Perhaps try that addon.

It would be great if you could report back here if Shadow works for you, then I can look and see what's been done and works and implement similar into Fen.

**Comment by Aguzy** [comment]
Sorry I've taken so long to get back to you. I tried the shadow add-on and it's pulling easynews links. Thank you for the suggestion. I hope when you get a chance you can maybe take a look and do this with fen. Thanks again my friend and sorry to leave you hanging for so long 🤝

**Comment by Tikipeter** [comment]
No worries. That's great news about Shadow.

I'll have some time soon and will grab what inspiration I need to from it, and plug it into Fen.

If you'd prefer to use Fen (not saying you should, Shadow looks like a nice addon), keep an eye out for an update that will have v3 Easynews support.

**Comment by Aguzy** [comment]
Excellent, I'll be keeping my eye out for the update, not trying to be a suck up but fen has been my favourite add-on for ages, I always get great results from it
