### ISSUE TITLE
Error loading content

### ISSUE THREAD

**Issue by omen124** [Tikipeter/repository.tikipeter#246]
Had difficulty loading in a list of shows from my trakt list, then an issue searching for stuff. Don't know if this log is useful or not.
paste.kodi.tv/enomejepex

**Comment by Tikipeter** [comment]
There is a `RuntimeError` error on startup when Fen's `services` file runs. It seems to indicate a problem with identifying Fen as an addon. It's possible the code in services is running before all the python modules are loaded.

A couple of seconds later, `build_next_episode` is called by Fen, which fails also. There is unfortunately nothing else in the log (the whole log is 30 seconds worth of activity.)

I would assume this has not happened again, and is likely due to modules being called before they are available.

Let me know if this continues to happen.
