### ISSUE TITLE
Kodi freezes playback and looses sound after autoscrape next episode selection

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#247]
Hi Tiki I've noticed on a few occasions tonight after selecting the next episodes link after the autoscrape kodi freezes playback and i completely loose sound after playback starts.

I've managed to capture a log : 

https://paste.kodi.tv/osibujufeg

Here is another log after restarting kodi, the issue still persists 

https://paste.kodi.tv/varizacibi

Coming out and selecting something else does not solve the issue, only a full restart of my nvidia shield fixes it. It seems I've triggered it everytime tonight using the autoscrape feature, Would it be possible to take a look. Many thanks 

Kodi version 20.1
Nvidia Shield pro 
Arctic Horizon 2 skin 
Fen version 3.1.12

Edit : I also noticed that other apps like Tivimate on my shield would have no audio and freeze after exiting kodi also, this would only start working again after a reeboot of the shield, but this issue was triggered using Kodi, it's very odd I've never encountered this before, would a cachebuffersize advanced setting be the cause do you think? It's not a big one but not sure if it's recommended to remove it

**Comment by Tikipeter** [comment]
Turn off playback monitoring and see if that makes a difference.

**Comment by JFG1000** [comment]
Ok will do some more testing with that turned off today then. Many thanks, I'll report back

**Comment by JFG1000** [comment]
UPDATE : seems to be ok with that setting you advised to be turned off, many thanks I'll continue to test for now

**Comment by TwilightMercy** [comment]
What playback monitoring setting does?
And for most cases should it be on or off?

**Comment by JFG1000** [comment]
UPDATE this is now happening again but now with general playback

Log

https://paste.kodi.tv/gibinezix

Many thanks

**Comment by Tikipeter** [comment]
It's out of my area of knowledge if there's no errors with Fen. I have zero understanding of Kodi's internals when it comes to their player.

In saying that, there will be changes in this area next update, so give it a try when that releases and see if it makes any difference.

**Comment by JFG1000** [comment]
Many thanks tiki much appreciated

**Comment by pyro12** [comment]
On Linux, my kodi has a quirk where when the HDMI goes to sleep and the HDMI audio is not (temporarily) available, kodi will switch to analog out.  It won't say it switched in settings, but it does switch.  The only way to get it back is to close and restart kodi.

Assuming you're using an HDMI out (I know nothing of the shield except it almost certainly runs Android), maybe plug some headphones into the analog out (if it has one) or something to see if it has switched outputs. 

Could help narrow down the problem.  I hesitate to suggest a wonky cable because in my experience it's almost never a wonky cable, but it could be a wonky cable.
