### ISSUE TITLE
Fen and Real Debrid

### ISSUE THREAD

**Issue by pcliff069** [Tikipeter/repository.tikipeter#249]
Hi
Seem to be having an issue with Real Debrid. I pick out a show and it is doing a pre-sources scrape search sits at 1% - so far for a couple of minutes.
I'm using it on my Amazon Firestick so not sure how I can get a log to you.
I also tried to re-authorise Real Debrid but all I got was code L7 and the authorisation screen quickly disappeared.

**Comment by Tinuz97** [comment]
Real-Debrid issue i guess
![realdebrid](https://user-images.githubusercontent.com/47715606/90312239-09c4a680-df03-11ea-84c7-cee4ffce0934.jpg)
,try again.

**Comment by pcliff069** [comment]
Thanks

Thought they might be having issues.

Regards

**Comment by Tikipeter** [comment]
Tinuz is right. This should be OK now.

I do need to see why RD was not honoring my timeout setting of 13 seconds though, as this was unacceptable.

**Comment by dm2912** [comment]
On a related note. I have all-debrid as a backup to real debrid just because of the recent issues.

However, All-debrids torrenting is utterly useless. They dont host them themselves and they just sit there on 0% cache and not playing, but, they are very good for hosters

Is there a way of setting fen so it checks my RD torrent cache, but doesnt check the AD cache and uses AD only for hosters.

**Comment by Tikipeter** [comment]
Not at the moment. It could be added though I suppose.

**Comment by Tikipeter** [comment]
I'll close this and open a new issue for this request.
