### ISSUE TITLE
No Issue -- Just Thank You

### ISSUE THREAD

**Issue by MrC001** [Tikipeter/repository.tikipeter#25]
I am glad you are back and Fen lives on.  The best add-on ever.

Small feature request ... is it possible to add a toggle to enable/disable ability to use my accounts add-on.  I know you do not use or maintain it .. I use my own wizard with my 76 Yr old dad who is 2 hours away and just easier if his trakt account stayed in one place if I update him.  Right now have to use Ezra...(Not that its bad, but Fen's better with recent updates)

Regardless, Thanks for everything ... past and future !!

**Comment by Tikipeter** [comment]
I really wish I could help you so as to make it easier for your dad, but unfortunately it just isn't possible.

Just using Trakt as an example, because Fen has moved away from My Accounts, there are now different client id's being used. If you authed in My Accounts, and I brought that info over to Fen, it still wouldn't work.

If it softens the blow any, there are plans from Ezra to remove My Accounts as well. He is the last one using it, so that then would be the end of My Accounts. So unfortunately something is going to need to be done from your end before too long anyway. Might be time to make the plunge now and get it all switched over.

Actually, thinking about it, make sure it's a good decision to switch your Dad to Fen. I do more updates and sometimes I break things trying to bring in new features. Ezra on the other hand isn't doing that sort of thing. It might be better leaving him on Ezra for the stability?

**Comment by MrC001** [comment]
No prob...ya I know you break things...I turn off auto updates lol.... It's
all good .. no harm in asking...
