### ISSUE TITLE
enchantment - Different color for line2 of mulitline results

### ISSUE THREAD

**Issue by Mr-invisibles** [Tikipeter/repository.tikipeter#25]
Hey Love this add-on and thx for it and the time you spend.
But have you seen (TheOath) add-on ?

I see i can choose in FEN Display multi line. but its hard to see the results ..
and i have used TheOath and he manage to add a second color and it looks more clean..

The problem is i love your add-on, so my question is if it possible to take a look if its hard and to match work to add it t your add-on? 
here is a link if you want to check it out! 

https://github.com/host505/repository.host505

here is how i looks 
https://drive.google.com/open?id=1RP7fDUdwcQKuhakvIwChjGYzXi3RoMUL

Thx anyway for a lovely superb add-on ...

just send an answer if you can check it out, or will will do it, but stupid to loose all changes on an update..

Best regards / Mr-inv

**Comment by Tikipeter** [comment]
Hi Mr-invisibles.
Let me think about how to implement it within Fen.
I'll write back here if I include it....

**Comment by Mr-invisibles** [comment]
sounds nice, was checking bait but the 2 add ons are not direct built on the same ground :)

**Comment by Tikipeter** [comment]
No, Fen is not an Exodus fork, it was coded from scratch with some helpful code plucked from a few different add-ons. So I need to do the code myself for things like this. :)

I have implemented a different color choice for line2 of the multi-line results. The default will be 'No Color', meaning it will be the same color as line1. You will be able to change it in settings (Oath uses 'Cyan' as it's color for line2 if you want it the same).

I don't use multi-line normally, but I think I like having line2 as a different color. So good suggestion Mr-invisibles! :) :)

This be included in next release (v.1.5.47), just give me about 24hrs to test this release, as it has other changes that I need to make sure are OK before uploading.

**Comment by Mr-invisibles** [comment]
Yea i understad :)  never used it before, but when i tried it with different color i started to like it.. 
Sure will wait and try.. 
hope you find a way to make it great!!

**Comment by edb64** [comment]
I tried out The Oath and found that it wasn't returning many good links. I have RD & have tried a lot of scraper addons with much better results. I don't think I set it up wrong, but didn't work well for me so I uninstalled it 🤷‍♂️

**Comment by Mr-invisibles** [comment]
well the oath was just an example to show how it looked in dual line mode.

But Tiki how did you manage to do your context menu? 
would really want to try implement it in an add-on if possible!

**Comment by Tikipeter** [comment]
Where do you mean Mr-invisibles?

Send through a screen shot for me if you can...

**Comment by Mr-invisibles** [comment]
was not so important, just like how easy it is to change menus after liking.
is it possible to get Trakt to scroble or synk when load the add-on, the only i could see was autoupdater on start for subscription .

**Comment by edb64** [comment]
Once you have linked Trakt it will sync on addon startup... At least it does for me.

**Comment by Tikipeter** [comment]
Fen caches Trakt data as needed (user watched history, user lists, etc), so it doesn't do a full sync like, say, Seren.

I can clear the cache on startup and then Fen will refill it with fresh data as it is needed. Well actually, not on startup, but the first time you enter a Fen menu that needs Trakt info, it will refresh the cache and start getting new info. This will ensure any widgets pointing to Fen lists will get new Trakt info as well.

This will be a setting in General->Trakt Navigation and Cache.

Note if you have any widgets using Fen lists, the notification that the Trakt Cache clear has happened will be hidden. You know it is successful because there will be a notification if it fails, even from a widget list loading.

@edb64 : That sync you see is a different thing. That is Fen syncing Trakt's Watched Statuses with Fen's internal watched Statuses. That is for when the Trakt API goes down, you can switch Indicators to Fen and have an identical watched history as Trakt until the Trakt API fixes itself. This change will make Fen clear all Trakt info the first time Fen asks for it, and begin re-caching info as needed.

**Comment by Mr-invisibles** [comment]
Is it possible to import or add .xml files i have on my server and was using for my "Mr invisible" add-on ?

**Comment by Mr-invisibles** [comment]
well maybe just do on a jen add-on :)
