### ISSUE TITLE
[Question] Enable Kodi Menu Caching Setting

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#252]
Hi, 

opened this only to ask what “Enable Kodi Menu Caching” setting does?

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/46edd98f-11f6-47a5-8dcd-df08d31e1d55)

**Comment by Tikipeter** [comment]
I'll quote an old friend:

>It caches the whole function.
Say you navigate TV Shows-->Most Popular-->Game of Thrones-->Season 1.
Now if you back up to Most Popular, then no new external requests are made and it's pulled directly from Kodi's cache on your disk.

So it's supposed to keep a "snapshot" like cache of each window in the tree of windows you navigate to.

But, it only triggers to do that if the container loading takes longer than (I think) 2 seconds to display.

There are not many practical uses for it, but turning it off can help alleviate a couple of issues to do with mainly Jurial skins like AH2.

Code wise, it is a param when ending a directory after building the listitems:
`xbmcplugin.endOfDirectory(int(sys.argv[1]), cacheToDisc=False)`

**Comment by TwilightMercy** [comment]
Do you recommend to enable it for faster menus navigation using Estuary skin?
Or there will be no major difference?

**Comment by Tikipeter** [comment]
I do recommend enabling it. If you have a slow device, then it might take Fen over 2 seconds to display a set of list items, even if it has them cached through the addon. In those cases, pressing "back" to load the previous window should be instantaneous when "Enable Kodi Menu Caching" is enabled. Otherwise all the previous window's list items need to be made again by Fen to display.

Unless you are using a skin where there are known issues with enabling this, then it is better to have it enabled, even if in the end it might not do too much.

**Comment by TwilightMercy** [comment]
I see thank you for the explanation. 

What is the reason you won’t make the setting enabled by default?

**Comment by TwilightMercy** [comment]
For Estuary and FENtastic skins - 
Do you think it will cause issues?

**Comment by Tikipeter** [comment]
Nope.
