### ISSUE TITLE
Fen stopped since last upgrade

### ISSUE THREAD

**Issue by pcliff069** [Tikipeter/repository.tikipeter#256]
As the heading says. log file at:

[https://paste.ubuntu.com/p/gB4x2vgxKS/](url)

**Comment by pcliff069** [comment]
At this stage I have uninstalled addon and will re-install tomorrow morning. Numbers, Plex are all working OK. I did have some trouble with the skin I was using (Debrid) but did a restore and also went back to Estuary skin. I also tried true and false with the language invoker but still Fen error. 
Will report more later.

**Comment by Tikipeter** [comment]
Kodi is trying to navigate to Fen's `my_trakt_content`, which hasn't existed since version 1.6.19.
There must be something in your setup (widget usually) that is trying to access this non-existent menu.

**Comment by pcliff069** [comment]
Not sure what menu that could be.
I reinstalled all my short cut menus.
Hopefully a clean install will take care of it.

**Comment by Tikipeter** [comment]
I'll upload a new version soon (v.1.8.05) which might make a change for the trouble you're having.

But something in your setup is trying to access a function that is no longer available. The function `my_trakt_content` used to access your Trakt Lists. It changed a long time ago to accommodate IMDb lists also being present.

Find where that old link is, and you should be OK once you remove it. It won't be called `my_trakt_content`, but something like `My Trakt Lists` or similar.

**Comment by diemenz** [comment]
The newest version (05) still throws an error on Apple TV and does not work. Previously I just went back to the 17 series and everything would work as normal but with today’s update going back results in all searches being blank.

**Comment by Tikipeter** [comment]
I'm at the point where I'm going to need logs (NOT Debug).

**Comment by pcliff069** [comment]
All I am getting is Fen error check the logs.
Latest log enclosed
https://paste.ubuntu.com/p/CsSx6BNfFw/

**Comment by pcliff069** [comment]
So why would it suddenly reappear?
And this is Android​ on a Firestick. No idea how where or what this
mysterious widget is or where this newly added file is nor to be honest
what it is.

**Comment by pcliff069** [comment]
The end of an extremely frustrating day. Nothing worked.
You can close this off and I'll check back from time to time - upgrade to upgrade.

**Comment by cgcgcgcgcg** [comment]
A friend had the same issue -me too-, and I remembered the dev suggested this on an older issue.
Clicking on all 3 of these solved it.
![118765896_1685582278267343_8139267724161519974_o](https://user-images.githubusercontent.com/38960370/91993169-b98c7780-ed3d-11ea-893c-704a7c316414.jpg)

**Comment by diemenz** [comment]
^ unfortunately that isn’t an option as the error prevents the add on from opening so you can not navigate to the tools section.

**Comment by cgcgcgcgcg** [comment]
> ^ unfortunately that isn’t an option as the error prevents the add on from opening so you can not navigate to the tools section.

@pcliff069 too.

You can always use Kodi File Manager to navigate to userdata/addon_data, delete plugin.video.fen and restart Kodi. Then just open Fen, do what I described above first, then authorize debrid & Trakt.

**Comment by Tinuz97** [comment]
1.8.0.6 did break it for me also.
I did get a message mismatch settings or something like that, do you want to restore?
I did hit yes, and after that Fen was totally gone on my Android phone (did Uninstall itself). 

Can't find anything related in log either, weird. 
Before 1.8.06 everything worked great for me :/

**Comment by Tinuz97** [comment]
Installed 1.8.0.6 again, after that it removed itself, luckily it did remember my settings, and seems to work now.

**Comment by diemenz** [comment]
Tried a fresh install on a fresh kodi install. 

Apple TV = error seconds after install and will not load. 
Fire Tv = no problem 
Windows = no problem. 

My guess is that it has something to do with the way the Apple TV uses cache files. If anyone out there knows how to pull the log from an Apple TV reach out and I will pull it, I have had no luck so far.

**Comment by pcliff069** [comment]
Followed the steps as suggested by cg(etc) and still no joy. Latetest log:
https://paste.ubuntu.com/p/ZzB95wmhmC/

**Comment by pcliff069** [comment]
1.8.06 Got it
Happy camper (again!!!!)
Love your work - keep it up

**Comment by Tikipeter** [comment]
I was just writing out a big post, and I saw that @pcliff069 has got it working now. Which is great.
This was a very disruptive update with a whole stack of potentially breaking changes, so I'm glad you've got it working again.
The whole way Fen interacts with settings and Kodi in general was changed, so there were bound to be issues.
Things will go back to normal for a while now. There shouldn't be any risky "breaking" updates.

As for @diemenz , I would say your issue with Apple TV will be due to using Kodi 17 on that platform, is that correct. I need to see what is happening with 17. At best I'll need to fix something. At worst Fen will no longer be compatible. I would love a log file of after Fen shows an error.

**Comment by Tikipeter** [comment]
@diemenz  Also, after making sure 1.8.06 is installed, restart Kodi before testing Fen. I just needed to do that before it would work, but it is now working for me on Kodi 17 with minimal testing so far....

**Comment by diemenz** [comment]
Tried it on a fresh install and did the kodi reboot. Still an instant error. I wish I could pull a log because I'm certain that it has to do with the change to the service settings management as that was just implemented into venom and it throws the exact same error and doesn't load. I have reverted back to 1.7 with the old module and it's working with no issues. Apple TV is a great device but it sometimes hates kodi :). 

Thanks for all your hard work.

**Comment by Tikipeter** [comment]
@diemenz are you able to install an update from zip?
If so, I might have a fix for this very disruptive issue you are having.
I'll post it here in case you are able to install from zip on your Apple.
Be advised, Downloading doesn't work on this release, as it's going through a re-write at the moment. This test update is just to see if it fixes your issue because I just thought of a possible solution.

[plugin.video.fen-1.8.07g.zip](https://github.com/Tikipeter/repository.tikipeter/files/5212046/plugin.video.fen-1.8.07g.zip)

**Comment by diemenz** [comment]
I will test it tonight, thank you I appreciate it.

**Comment by Tikipeter** [comment]
@diemenz I forgot. Also install this tikimeta version.
[script.module.tikimeta-1.2.07c.zip](https://github.com/Tikipeter/repository.tikipeter/files/5212130/script.module.tikimeta-1.2.07c.zip)

**Comment by diemenz** [comment]
Tested and this version is working 100% with apple tv 4k and apple tv HD.
I just want to reach out and say thank you for your hard work. I have been using fen and one other addon since they came out not just because the addons are great but also the Devs are so friendly and dedicated. The fact that you would fix this when the impact is not wide spread but just device specific is very appreciated.

**Comment by Tikipeter** [comment]
Great that it's working. It was an easy fix in the end.

**Comment by Tikipeter** [comment]
@diemenz 
I pushed `1.8.07b` to the repo which is the changes needed for Apple users applied to the last fully working Fen version. So donwloading should work on this version too.

**Comment by diemenz** [comment]
I noticed it throws an error unless I’m using the tiki meta module I was testing.
