### ISSUE TITLE
[Feature Request] Sort 4K HDR to the top when using source select

### ISSUE THREAD

**Issue by ambulancePilot** [Tikipeter/repository.tikipeter#258]
Hi there, I'm just wondering if you would be willing to implement this feature as an option (or if it's already available and I'm missing it somehow)? I apologize in advance if this question has already been asked.

If there's no interest from your side, then not a problem. The add-on is the GOAT either way.

The prefer HDR for autoplay kind of solves the problem, but for those of us who enjoy auto scrape instead of autoplay, it would be nice to have that option.

We are already able to sort 4K to the top, and it would be nice to be able to sort 4K HDR even higher.

Thanks for reading! Have a good day.

**Comment by Tikipeter** [comment]
Let me think on this. The sorting/filtering code really needs a re-write to be able to successfully accommodate more advanced sorting and filtering. What's there currently is only really good enough because it is only implemented at Autoplay level, so you can't really see what the sort is ending up as.

Currently there are 4 filters which can be set to `Prefer (Autoplay)`. There is, however, no code to set in which order they should be preferenced, and that is the issue.

The current order in which the filters are preferenced is:
```
HEVC
AV1
DOLBY VISION
HDR
```

...and currently there is no way to change that order. So no way to tell Fen "I want both Dolby Vision and HDR prefered, but I want Dolby Vision preferred over HDR".

I could remove the limitation on the current implementation being only preferred for Autoplay, but I fear that will open up a can of worms.

So I'll have a long hard think about what to do. The time may have come to do something about this.

**Comment by Tikipeter** [comment]
I'll need to be honest.... my brain just can't get into doing this at the moment. It's a bit too big a job.
