### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#262]
Good evening,

 Which skin is best to use for FEN?

**Comment by Tikipeter** [comment]
Impossible to say. I use my own skin because it's very fast, and that's what I find important. But it's old looking these days so nobody else would want to use it.

I used Arctic Zephyr for a fair while, it's a great looking skin.
Others use Aeon Nox Silvo. Looks fine but the fonts are HUGE.
There are of course many other skins for Kodi.

There's not really a specific skin that will make Fen work the best. Fen will always SEEM quicker if you have a quick skin that doesn't make additional calls to the metadata providers as you are browsing lists in Fen, but most do nowadays.

I think Fen provides all the artwork and info that skins might need to look their best, so in the end Fen is compatible with all of them, so choose based on what's important to you in the way of looks and speed.

For skins, it's more of a case of installing a bunch of them and giving them all a try. Maybe live with each one for at least a day, and then move onto the next if it doesn't fulfill your needs.
