### ISSUE TITLE
Enhancing User Control: Independent Management of Watched Items in External Widgets

### ISSUE THREAD

**Issue by DevGeniusCode** [Tikipeter/repository.tikipeter#262]
I use the FENtastic skin, and there is an option to display search results using widgets. Because widgets are affected by FEN settings, it is not possible to manage the setting in a skin external to the FEN. Below is a description of the problem as it appears in the FENtastic  skin.

In the previous search form, users had the convenient ability to show or hide watched items by simply opening the side window (Media Menu) and clicking on Watched Toggle. However, with the introduction of the new form, the side window has been removed, and the option to manage watched items is now controlled by the FEN settings (because now it's widgets).

Currently, the FEN settings (Settings > Navigation > Widgets) govern the visibility of watched items in both the search screen and the home screen. This means that if users choose to enable the hiding of watched items on the home screen, they have no option to disable it on the search screen without going to settings each time. As a user, I personally prefer to hide watched items on the home screen since there is no need to see offers of items that have already been watched.

**Request**:
Add option to manage this option independently of the main setting for it.
Alternatively, add an option to write a directive in the xml file that says to ignore this setting and display all results by default.

**Code Snippet:**
`userdata\addon_data\plugin.video.fen\settings.xml`
`<setting id="widget_hide_watched">false</setting>`
This is the section of code in the settings file that manages the display settings of widgets.

**Comment by Tikipeter** [comment]
You seem interested in the code and what's happening so I'll take the time to explain some things.

>Currently, the FEN settings (Settings > Navigation > Widgets) govern the visibility of watched items in both the search screen and the home screen.

The way this works is Fen does a check to see whether the items it is going to make are coming from a container within the Fen addon, or from a container outside of the Fen addon. If the check reveals the container is being made from WITHIN Fen, then it is deemed to NOT be a home screen widget. If the check reveals the container is being made OUTSIDE of Fen, then it is deemed to be a home screen widget. The setting value for widget behavior is then accessed and the behavior is then based on that check.

The check works by Fen asking Kodi what the currently loaded addon is. If the container is to be made from within Fen, then the returned value will be `plugin.video.fen`. Otherwise the returned value will be blank. If the value returned is blank, this has always been good enough to determine that the container is a home screen widget. This is why the content within FENtastic's new search window behaves the same as if it were content on the home window. Fen assumes it is the home window widgets because it fails the currently loaded addon test.

With skins now making more use of custom windows to display content (i.e. the new search window in FENtastic) it is more necessary to use a different method to determine whether a container is loading from the home window or not. From next update I will use the current window's ID to determine if it is a home screen container being loaded or not. Each Kodi window has an ID attached. The home window is `10000`. This will fix your issue as FENtastic's custom search window of course has a different ID (`11121`). If the current window ID is `10000`, then it is a home window widget, otherwise it is not. This will fix your issue as FENtastic's custom search window has a different ID.


This is going to cause some issues that I will need to address, as the current function to test has other purposes where it needs to be kept at the current implementation. So unfortunately it will not be completely straightforward.

But it will be fixed in the next Fen update.

**Comment by DevGeniusCode** [comment]
I have now downloaded the new update and am happy to update that it works well and there is indeed a separation between the modes.
Appreciate your work and keep up the good job:)
