### ISSUE TITLE
Difference between fen and Venom

### ISSUE THREAD

**Issue by protocol77** [Tikipeter/repository.tikipeter#268]
I've noticed that both your addon and the venom now have the my account feature as well as scrapers dubbed "Fenom" which is clearly a combination of both addons names 

I was wondering what difference is there between both addons 

I personally use yours mostly as I find it scrapes faster but venom is really popular so I am curious if now you're both using the Fenom scrapers assumedly you would get the same search results therefore what sets fen apart from venom besides preference and IMHO faster scraping?

**Comment by Tikipeter** [comment]
Fen and Venom are completely different code, so apart from using the same scraper pack, and keeping in mind the inherent similarities simply due to them being designed to achieve the same functions, they are very different in their approach.
Instead of me listing their differences, it is best for you to navigate to Tools->"Tips for Fen Use" and reading through the tips. Most things written about in there are differences Fen has compared to other addons.

**Comment by Tikipeter** [comment]
As an aside, before Fenom Scrapers were released, both Fen and Venom also still used the same scrapers (Openscrapers).

**Comment by protocol77** [comment]
I appreciate your response and your explanation 
I personally love FEN and use it on all my media players 

Thanks for all your hard work and dedication to bringing this great addon to life 👍
