### ISSUE TITLE
Rescan and source select

### ISSUE THREAD

**Issue by Junkdewd** [Tikipeter/repository.tikipeter#286]
I was an early user of fen, and you were always right there to help as I was learning to appreciate your vision of a Kodi addon.  I just want to thank you for that and express I'm very happy you are continuing development.  If you need testers at anytime, I have multiple devices I'll happily trash for the good of us all. 🤪

Now to my subject.  Are the rescan and rescrape options still available somewhere and I'm just unable to find it?  I remember you mentioning moving it, but I could have missed that you were removing.  I currently just disable autoplay when I hit problematic sources, and can continue if the option isn't available any longer.  

Thanks again.   

Edit: edited to comply with rules. Sorry.

**Comment by Tikipeter** [comment]
I had to get rid of the "Rescrape & Select Source" because of troubles with the Language Invoker that I now have the option to enable/disable.

If, in the past, you used this when you had autoplay enabled and now wanted to clear providers and choose a source instead, that is now not possible. I'm hoping to add it back, but it is not a trivial fix anymore. Your current solution would be a 2 step process: Context Menu->Options...->Auto Play (this will turn Autoplay Off), then Context Menu->Options...Clear Scrapers Cache (this will clear the previous results.) Then you can select the movie and choose a source.

If you are not using autoplay and just want "fresh" results, the process is the same as above.

Hopefully "Rescrape & Select Source" will be possible to bring back. I don't know yet.

**Comment by Junkdewd** [comment]
I remember now.  It's cool, I'm using the turn off autoplay, but usually don't have to rescrape as generally it's just the first source won't connect, do I can just try the second.  

Hope the bug hunt is going well for you.

**Comment by Tikipeter** [comment]
@Junkdewd 

I'll be bringing back "Rescrape & Select Source" with the next update (v.1.8.16). Got it working properly in all settings situations.

**Comment by Junkdewd** [comment]
Unexpected but appreciated.  Thanks
