### ISSUE TITLE
Feature request: Ability to auto re-scrape with all providers enabled if no source results are found

### ISSUE THREAD

**Issue by Omarscomin** [Tikipeter/repository.tikipeter#295]
Hey Tikipeter! I hope you've been having a good week!

I have one final request for a feature that I may or may not have some mild withdrawals from, when I switch from my Umbrella/AH2 set up to my FEN/FENtastic set up. 

I absolutely LOVE Umbrella's option that allows you to automatically re-scrape from all of Coco Scraper's providers if no source results are found. The reason this is so amazing is because you typically only need 1-2 providers enabled, in order to get good results, which makes scraping extremely quick. On rare occasions, more providers are needed to find more obscure content, which is when that setting comes in handy!

Honestly, other than the IMDB lists that I already requested, I can't think of even _one_ more feature that I'd request, so I don't think you'll be hearing from me on here again. Lol. As always, thank you for everything you do, and thank you for considering to catering to my nitpickyness🙂

**Comment by Omarscomin** [comment]
> Library feature... that's 1 🫠

Just use Umrella😉lol

All jokes aside, I personally just don't care about a library feature. I haven't researched the benefits of having a Kodi library.

**Comment by TwilightMercy** [comment]
Context Menu - Playback Options - Rescrape with all external scrapers

Or you’re asking for it to be automatic?

**Comment by Omarscomin** [comment]
> Context Menu - Playback Options - Rescrape with all external scrapers
> 
> 
> 
> Or you’re asking for it to be automatic?

Asking for it to be automatic, yes😇

**Comment by Tikipeter** [comment]
There's certain features of Umbrella which the dev has worked hard to implement.

2 examples of this are using subtitles to determine when the "Next Episode" pop-up should occur, and automatic scraping of all providers if no sources are found.

With the understanding that umbrellaplug would NEVER ask that they remain Umbrella only features, I decided when they were implemented that it would be nice for them to be Umbrella only features, considering the work he put into them.

Time has passed since then, but for now I still think Umbrella should have this as an exclusive feature.

Down the road it can be revisited of course, because I do think it's a very handy feature. I would definitely use it myself quite often, considering I search for some obscure titles.

So if it makes you feel any better, I'm depriving myself of this feature too.  :-)

**Comment by Omarscomin** [comment]
> There's certain features of Umbrella which the dev has worked hard to implement.
> 
> 
> 
> 2 examples of this are using subtitles to determine when the "Next Episode" pop-up should occur, and automatic scraping of all providers if no sources are found.
> 
> 
> 
> With the understanding that umbrellaplug would NEVER ask that they remain Umbrella only features, I decided when they were implemented that it would be nice for them to be Umbrella only features, considering the work he put into them.
> 
> 
> 
> Time has passed since then, but for now I still think Umbrella should have this as an exclusive feature.
> 
> 
> 
> Down the road it can be revisited of course, because I do think it's a very handy feature. I would definitely use it myself quite often, considering I search for some obscure titles.
> 
> 
> 
> So if it makes you feel any better, I'm depriving myself of this feature too.  :-)

I totally understand and respect that! I love the little bond that you 2 have🙂Thank you for the reply!

**Comment by TwilightMercy** [comment]
The specific feature of auto rescraping with all external providers when no source results are found - will be great and helpful in FEN.
Maybe in the future we can hope : )
