### ISSUE TITLE
Nerdy question about source quality “Not an issue / enhancement  “

### ISSUE THREAD

**Issue by ethamb** [Tikipeter/repository.tikipeter#304]
I’m wondering what quality media should be preferable are Blu-ray 1080s better then upscaled web 4k ?
excluding audio track 

obviously the 4k should look sharper but would it have more blocking or artifacts from its lower bit rate 

 Although it depends on a lot of things like how much frames move / grain / darkness etc that could make cause a need for higher bitrate 
Even different kinds of content may have different results like simpler cartoonish movies should have less variable data 

But for the average action movie with movement ,darkness ,grain  would a Blu-ray over 4k web be preferable? 
(“1080 264 Blu-ray compared to 4k 256 without comparing audio etc “)

or is there some site or sheet/ chart with a comparison of different codecs / bitrates at slow encoding I could use to decide?

**Comment by ethamb** [comment]
sorry if it’s like comparing oranges to apples 
as there are a ton of variables within video quality from codec bitrate slower or fast encodes 
Parameters within the encode 
the content itself (grain motion darkness etc  )

maybe even a bit of luck

**Comment by Nuklear92** [comment]
4K Web DL over 1080p Blu-Ray. If we talking picture quality alone, 4K is 4K on a 4K Display. Where as 1080p Blu-Ray regardless of having more bitrate, still have to go through the Upscaling process if it's being watched on a 4K display. Therefore, the picture will be stretched out and artificial pixels for enhancing sharpness and detail will be added. 

I can tell you by experience because I have a 4K OLED TV and Nvidia Shield Pro With AI Upscaling. And had compared 1080p sources upscaled both via the TV itself or AI Upscaling from the Nvidia Shield. At the end of the day a true 4K source just looks cleaner, vivid and not artificial in some aspects. Upscaling with the Shield AI upscaler tends to add a bit too much edge enhancements which does look somehow not natural, it doesn't look that bad if you have it on the AI-Enhanced Detail: Low setting instead of the default Medium. 

When you're viewing a 4K Source there's no pixels added, edge enhancements, among other things from Upscaling a picture so the content just looks so natural, with the right amount of sharpness, background environment looks perfect, text doesn't look fuzzy, blurry, etc. Simply if both qualities are available for choose, 4K over 1080p is the obvious way to go. However, if you're more into Audio quality, then usually a Web DL 4K source from a streaming service, Netflix, Prime Video, Apple TV Plus, or VOD rentals, Movies Anywhere (MA), iTunes Movies, etc. Will always have lossy audio tracks, Dolby Digital Plus 5.1 with or without ATMOS.

A 1080p BluRay source, if we are talking about the Remux ones. Those typically will have DTS-HD or Dolby TrueHD 5.1/7.1 audio tracks which are the lossless quality. 

In the end it all depends on what you're looking for. If there is 4K Remux files and 1080p Remux files the choice is inevitable 4K is the way. Superior picture quality and audio.

If you have you have the scenario of 1080p Remux BluRay and 4K WebDL sources then you have to sacrifice either Picture Quality with the 1080p source but HD audio. Or vice versa with the 4K source and sacrifice HD audio by having a lossy Dolby Digital Plus track. Unless you have a big AVR system with expensive speakers there won't be a massive difference in audio quality if you have a Soundbar. You can sacrifice the Audio Quality and go with the 4K source. But in the end it all depends what's more important to you when watching content. Audio Quality vs Picture Quality.


Apologies for the long comments, hope this helps you into deciding. 👍

**Comment by ethamb** [comment]
> 4K Web DL over 1080p Blu-Ray. If we talking picture quality alone, 4K is 4K on a 4K Display. Where as 1080p Blu-Ray regardless of having more bitrate, still have to go through the Upscaling process if it's being watched on a 4K display. Therefore, the picture will be stretched out and artificial pixels for enhancing sharpness and detail will be added.
> 
> I can tell you by experience because I have a 4K OLED TV and Nvidia Shield Pro With AI Upscaling. And had compared 1080p sources upscaled both via the TV itself or AI Upscaling from the Nvidia Shield. At the end of the day a true 4K source just looks cleaner, vivid and not artificial in some aspects. Upscaling with the Shield AI upscaler tends to add a bit too much edge enhancements which does look somehow not natural, it doesn't look that bad if you have it on the AI-Enhanced Detail: Low setting instead of the default Medium.
> 
> When you're viewing a 4K Source there's no pixels added, edge enhancements, among other things from Upscaling a picture so the content just looks so natural, with the right amount of sharpness, background environment looks perfect, text doesn't look fuzzy, blurry, etc. Simply if both qualities are available for choose, 4K over 1080p is the obvious way to go. However, if you're more into Audio quality, then usually a Web DL 4K source from a streaming service, Netflix, Prime Video, Apple TV Plus, or VOD rentals, Movies Anywhere (MA), iTunes Movies, etc. Will always have lossy audio tracks, Dolby Digital Plus 5.1 with or without ATMOS.
> 
> A 1080p BluRay source, if we are talking about the Remux ones. Those typically will have DTS-HD or Dolby TrueHD 5.1/7.1 audio tracks which are the lossless quality.
> 
> In the end it all depends on what you're looking for. If there is 4K Remux files and 1080p Remux files the choice is inevitable 4K is the way. Superior picture quality and audio.
> 
> If you have you have the scenario of 1080p Remux BluRay and 4K WebDL sources then you have to sacrifice either Picture Quality with the 1080p source but HD audio. Or vice versa with the 4K source and sacrifice HD audio by having a lossy Dolby Digital Plus track. Unless you have a big AVR system with expensive speakers there won't be a massive difference in audio quality if you have a Soundbar. You can sacrifice the Audio Quality and go with the 4K source. But in the end it all depends what's more important to you when watching content. Audio Quality vs Picture Quality.
> 
> Apologies for the long comments, hope this helps you into deciding. 👍

Thanks a lot
