### ISSUE TITLE
Ability to change sort method for trakt lists by other users.

### ISSUE THREAD

**Issue by TheGuyWhoo** [Tikipeter/repository.tikipeter#32]
As far as I can tell they are sorted by "added" by default. This makes no sense for lists like "Latest releases". I would like to sort those by release date. Is this possible at all or something you'd be likely to implement?

**Comment by ambulancePilot** [comment]
The one thing I think you should keep in mind is that the reason most latest release lists are sorted by "added" by default is because old movies get re-released in 4K _all the time._ If you sort by release date, you will never see that those movies have been re-released. The people that curate these latest release lists sort them manually so that you can see the latest release regardless of original release date.

Either way, custom sorting of all lists would be great. I imagine it will increase loading time.

**Comment by Tikipeter** [comment]
Big(ish) job that. Let me think on it..

**Comment by Tikipeter** [comment]
Looks like you're getting the Umbrella dev to do this too, so I'll close this issue as I wasn't really wanting to implement this.

**Comment by TheGuyWhoo** [comment]
Bummer! I do regularly use both addons, so it is an issue I experience in both. Thanks for at least entertaining the idea, though.
