### ISSUE TITLE
[Possible bug] Playback failed on certain shows.

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#337]
I get playback failed on Kill La Kill, and The Midnight Gospel. It works on other shows such as Jujutsu Kaisen, and Seinfeld.

I press play (using TMDB Helper, to Fen 1.8.20), it loads forever without playing anything, i press back, get playback failed. Here is the log

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5648210/kodi.log)

**Comment by Tikipeter** [comment]
Not sure on this one, but likely related to the other playback issue you've opened. Will need to wait and see when I fix that.

**Comment by mathu204** [comment]
> Not sure on this one, but likely related to the other playback issue you've opened. Will need to wait and see when I fix that.

1.21.b I still get this problem 

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5649670/kodi.log)

**Comment by mathu204** [comment]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5649953/kodi.log)

for Kill La Kill Episode 11

**Comment by Tikipeter** [comment]
Did you delete the metacache6.db file? Because there are still errors in there for that.

Also, go to Tools and clean your settings file. There are a lot of old settings Kodi is looking for. Your whole install looks like a mess to be honest.

I added Kill La Kill to my kodi library through TMDbHelper, and it played, marked progress and marked watched correctly every time.

I'm going to close this issue and keep the other issue open for these problems.
