### ISSUE TITLE
Trakt Issue

### ISSUE THREAD

**Issue by muzikherif** [Tikipeter/repository.tikipeter#34]
At the end of playback it doesn't marking as watched movies or series.This issue exist for me from earlier builds which before you discontinued project.And now i awared you continuing the project again.And I be very happy to see you come back.Thank you for all your works.But I didn't get why I'm still getting this error.It is kind of trakt error and I getting it everytime.You can see at the log.Please help.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/9550071/kodi.log)

**Comment by Tikipeter** [comment]
I don't think there's much I can do about 104 errors.

From next update, I'll make a fresh `sessions` object each time Trakt info is needed. Apart from that I can't think of what else I could do, as it's server side.

**Comment by kodifitzwell** [comment]
I'm curious about your opinion on [urllib3.util.Retry](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html).  Venom and Seren both implement it fairly granular with their sessions.  I added very early in my fork (but less granular), but never really had the user count to determine its effectiveness other than a one off where a user reported Trakt issues with Ezra but not with POV on the same device.

I only utilize the **total** and **backoff_factor**.  I ask because now I see there is also a **connect** parameter for *How many connection-related errors to retry on*.  any advantage to a fresh ```sessions``` vs a retry?

clearly Fen has gotten along famously for all this time without so certainly your opinions are valuable.

**Comment by ambulancePilot** [comment]
I don't know anything about this as the discussion is above my intellectual capability. However I would personally not support modeling Trakt implementation after Seren. The Trakt DB in Seren is known to be very prone to corruption and requires a rebuild on almost a daily basis if one watches TV regularly.

**Comment by Tikipeter** [comment]
I decided against any retry like parameters, but I can't really remember why. It may be as simple as I didn't want to have another import. Sometimes that's all it takes. I may revisit it in the future though. It might solve something like this 104 error I suppose.

**Comment by Tikipeter** [comment]
I'm going to go with straight `requests` for the trakt calls for the next update. See how that goes.

**Comment by muzikherif** [comment]
It seems to be fixed, thanks a lot
