### ISSUE TITLE
[Query]Empty placeholder between Favorites & Site

### ISSUE THREAD

**Issue by onlytanmoy** [Tikipeter/repository.tikipeter#348]
Hiya,
please see this screenshot

https://imgur.com/a/mkqfvGu

from past few days I am getting that blank entry - the one highlighted between Favorites & Site. I am using the latest version of Fen. How to get rid of that?

**Comment by Tikipeter** [comment]
For future reference, you MUST provide a kodi log with every issue opened.

Context menu->Edit Menu->Restore Root Menu to Default. This will fix your issue.

Also please note, it is important to read the changelog upon each update.

This issue was addressed in the changog for version 1.8.22, in big capital letters.

**Comment by onlytanmoy** [comment]
@Tikipeter Thanks for the pointer mate, the issue is fixed now.
sorry my bad I will ensure to read the changelog going forward. Tbh I find it bit difficult to read the scrolling changelog on my TV :) Is there a link in github where I can read it from my mobile/laptop?
