### ISSUE TITLE
Not a issue, improvement

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#35]
Downloading option works great ,but i have a request on that part.
Is it possible to keep the original filename? or a option (switch) in the settings to 'keep original filename' ,because it is easier to search for a subtitle after downloading (now i get release type not detected, because it removes all the extra needed info in the filename).

Not issue, but just a idea/request.

**Comment by Tikipeter** [comment]
Sorry for late reply Tinuz97, I'm really busy at the moment for some reason

 It makes sense what you are saying.

I'll have a look and hopefully change it for the next update.

**Comment by Tinuz97** [comment]
No need for a hurry, because everything runs fine :) 
But it would be great for a feature update, because subtitle addons can find a sub much better with the original (i use torrent) file names , a example : Bird.Box.2018.NF.1080p.WEB-DL.H264.AC3-EVO[EtHD].mkv

if you download it,is getting renamed to something like Bird Box (2018) :)

**Comment by host505** [comment]
It's a good idea for torrs, but not so for hoster files, because most of the times they have irrelevant file names.

**Comment by Tinuz97** [comment]
Yeah that is why I mentioned I use torrents for downloads ;)

**Comment by Tikipeter** [comment]
I've finished this code ready for next update, and included a basic check to see if the show or movie's name is in the filename. If it isn't, then FEN will rename it as it does now. If it is, FEN will keep the original filename. It's only a basic check for the name, as I'm assuming if the file has the tv show's name in it, it will also have the season and episode. I can adjust this if that turns out not to be the case. It should work like this though...
