### ISSUE TITLE
'Recently watched episodes' order is random

### ISSUE THREAD

**Issue by cruse777** [Tikipeter/repository.tikipeter#354]
Hi,

the order in TV Shows item 'Recently watched episodes' seems random and does not reflect the order items are watched / shown in Trakt. This section could adhere to the configured order for Watched in Settings.

Fen already does support a logic to remove duplicates (of rewatched items).

Thanks!

**Comment by cruse777** [comment]
Thanks for looking into this. It might be related since it seems to disrupt processing. Let me explain.

(I think) You can reproduce it by rewatching, e.g., the third item in your Recently list.

- Trakt will create a new watched instance for this episode which is put on top of the list (it literally is the most recent episode watched), moving the other episodes including its former watch instance one notch down.
- Fen (seems to) avoids this duplicate logic (good!) with multiple instances, but would only put the rewatch on top of the list randomly. Rewatched items generally seem to screw with the order.

When testing this yesterday I initially thought I saw some logic where you would only have to change the processing to consider the latest watch instance instead of the first. But after another rewatch the order was completely reshuffled and one time it even crashed when leaving the addon and returning to the main menu.

I trigger rewatches a lot by falling asleep while watching. Episode finishes, Kodi marks it as watched, Trakt creates instance.

Thanks!

**Comment by cruse777** [comment]
This is processed correctly by another addon (S), so they found a way. But if the addon has to calculate by itself I think it's not worth the effort.

Obviously I prefer Fen, superior in any other way.

Thanks!

**Comment by Tikipeter** [comment]
I don't even remember if that's right now. I'm getting old. There's SOMETHING that Trakt doesn't provide correctly in it's sync data. :)

**Comment by ambulancePilot** [comment]
Hi there. I was actually just about to report something like this for Fen (not light). Not sure if you are interested in looking at it. as development has stopped. Since you stopped development, I have started to learn as much as I can about python. I don't know much.

I am not exactly sure how to describe what's happening. What I do know is that it exclusively is related to shows you have already watched. For example, I have fully watched a show. When I watch an episode of that show again, it MAY or MAY NOT move to the front of the "Watched" list in response to the fact that it is the most recently item of a fully watched show that I have watched. Sometimes it does and sometimes it does not, and I'm not sure what makes the difference.

I went in and changed some code (mainly because I didn't want to have two lists: Watched and In Progress Shows). I actually just want one list which is a chronological listing of the most recent shows I have watched regardless of whether they are fully watched or airing or whatever. The logic for this list is just take a look at all watched episodes in chronological order, figure out which TV shows they belong to, strip out duplicates, and then return the list.

Even by simplifying the logic for this list I still wasn't able to get the list to reflect what shows up in Trakt even though Trakt knows what I've watched and when. It even lists it accurately on the website. But for some reason Fen isn't able to sort this list properly (the way it's shown on the website). Some shows just never move from their spot in the Watched list.

Is there an issue with the last_played info that is stored by Fen? I tried to delete the Trakt DB and have it rebuild but still, no improvement. Where is it getting the faulty last_played info from? I know that Fen is properly marking the episode as played since the Trakt website shows the episode as having just been watched.

This is the simplified code I used for testing purposes:

`def get_watched_items(media_type, page_no):
	watched_indicators = watched_indicators_function()
	if media_type == 'tvshow':
		def _process(item):
			data_append(item)
		watched_info = get_watched_info_tv(watched_indicators)
		duplicates, data = set(), []
		duplicates_add, data_append = duplicates.add, data.append
		prelim_data = [{'media_id': i[0], 'title': i[3], 'last_played': i[4]} for i in watched_info if not (i[0] in duplicates or duplicates_add(i[0]))]
		threads = list(make_thread_list(_process, prelim_data))
		[i.join() for i in threads]
	else:
		watched_info = get_watched_info_movie(watched_indicators)
		data = [{'media_id': i[0], 'title': i[1], 'last_played': i[2]} for i in watched_info]
	if lists_sort_order('watched') == 0: data = sort_for_article(data, 'title', ignore_articles())
	else: data = sorted(data, key=lambda x: x['last_played'], reverse=True)
	return data`

**Comment by ambulancePilot** [comment]
Not sure how ChatGPT did this but I got it output the follopwing code which works perfectly for my use case.

def get_watched_items(media_type, page_no):
    watched_indicators = watched_indicators_function()

    if media_type == 'tvshow':
        watched_info = get_watched_info_tv(watched_indicators)
        duplicates, data = set(), []
        duplicates_add, data_append = duplicates.add, data.append

        watched_info.sort(key=lambda x: x[4], reverse=True)

        for i in watched_info:
            if i[0] not in duplicates:
                duplicates_add(i[0])
                data_append({'media_id': i[0], 'title': i[3], 'last_played': i[4]})

    else:
        watched_info = get_watched_info_movie(watched_indicators)
        data = [{'media_id': i[0], 'title': i[1], 'last_played': i[2]} for i in watched_info]

    if lists_sort_order('watched') == 0:
        data = sort_for_article(data, 'title', ignore_articles())
    else:
        data = sorted(data, key=lambda x: x['last_played'], reverse=True)

    return data

It properly orders the Watched list now based on the last episode you watched from any show (I have it coded to include all shows regardless of completed and airing status, I felt that filtering was unnecessary and complicated things).

Any idea what the difference is and why this code works?
