### ISSUE TITLE
TV shows not working in Fen Light

### ISSUE THREAD

**Issue by Cloudman999** [Tikipeter/repository.tikipeter#356]
Hi @Tikipeter 
I updated to the latest version of Fen Light yesterday. I can't seem to get any of the TV shows menu items to display anything.

I'm using Fen Light on a Google Chromecast with Kodi 20.2.

I've got a kodi log file

https://paste.kodi.tv/juxayepeni

Would appreciate some help.

@Cloudman999

**Comment by Tikipeter** [comment]
Unfortunately there's absolutely no info in that log pertaining to you trying to enter a directory in Fen Light.

And TV Shows are working fine for me.

Have you been using Fen Light from early in it's life? Before it moved to the main repo?

**Comment by Cloudman999** [comment]
> Unfortunately there's absolutely no info in that log pertaining to you trying to enter a directory in Fen Light.
> 
> And TV Shows are working fine for me.
> 
> Have you been using Fen Light from early in it's life? Before it moved to the main repo?

Hi @Tikipeter 
Yes, I used Fen Light when it was in the test repository, and then updated it from the main repository, when you released it a week or so ago.

It was all working fine until I updated to the latest version, yesterday.

My Movies menus work fine, it just seems to be anything to do with TV shows.

@Cloudman999

**Comment by Cloudman999** [comment]
> Do you know how to navigate into your "packages" folder?
> 
> Or do you have a "wizard" installed that clears the "packages" folder if you ask it to?

Hi @Tikipeter 
Yes, I have Simple Wizard installed, and I just cleared all packages.
Tried TV shows again (after clearing all caches), but nothing works. Movie menus work.

@Cloudman999

**Comment by Cloudman999** [comment]
> Uninstall Fen Light after clearing the packages. Then reinstall it.
> 
> No need to clear the settings when uninstalling.

Thank you @Tikipeter 
Fen Light is now working.

Much appreciate your help and add-on.

@Cloudman999

**Comment by Tikipeter** [comment]
Want to know what it was? I'll tell you anyway, since it's interesting:

Kodi keeps copies of the zip files of all the addons it updates in it's "packages" folder. If you go to install/update an addon, Kodi first checks whether it has a local copy of the zip file in the packages. If it does, it simply uses that to install/update the addon instead of downloading it again online.

Turns out, in the early days of testing Fen Light, I happened to label a couple of updates as `plugin.video.fenlight-1.0.03` and `plugin.video.fenlight-1.0.04`. So when it came time now for Kodi to install the recent update to Fen Light, if you had installed those old, but identically named, versions of the addon a long time ago, Kodi sees those zips in it's "packages" folder and installs that instead of getting the real, "new", 1.0.04 from the repo.

Of course, that old version of Fen Light won't work due to many changes.

Clearing that "packages" folder, and then re-installing Fen Light makes Kodi fetch the correct zip from online.

You can still use the test repository if you want as this can't happen again, but it might be better anyway to use the main repo moving forward.


Well, at least I found it interesting. :)
