### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by kodiadon** [Tikipeter/repository.tikipeter#367]
When Fen changed from using Open Scrapers to Fenom Scrapers and Accounts, I did the update/upgrade.  After using the all new version and setting everything up correct, almost every 2-3 days I would have to reauthorize Real Debrid and My Accounts. I don't know why it wasn't keeping my info..but it wasn't.
 So I uninstalled everything and went back to using 1.7.12a version and it works flawlessly, but it is the older version.

  I've been reading about the latest update and a lot of people are saying everything is working great and fast, and it's making me thinking about trying it out.

So my question is:  If I want to try out the newest version, Tikipeter in your opinion should I delete every part of the old version 1st, reboot, then set up the new version OR just update from 1.7.12a to the latest?

**Comment by Tikipeter** [comment]
That's tough to answer.

**Q: Should you upgrade:**
There was a fair amount of troubleshooting and bug squashing around My Accounts after it was released. We found the reasons for people having issues with it by and large, and there hasn't been ANY mention of issues for a few months now, either from Fen or Venom users. So I think it is very stable now.
It would be better to test Fen on an install of some kind that you don't rely on. Maybe your computer if you have one.

**Q: Should you delete all traces of an old Fen version:**
Usually I would say no to this, but because you have missed many updates, then it would be better to clear all traces of Fen from your install.

**MOST IMPORTANT**
If you are going to try the new version, then make sure you have the old version you need as a zip so that you can re-install if needed. You would also need **script.module.tikimeta** and **script.tiki.art** from the same timeline as the old version of Fen. Also, Fen removed a fair few features between when you stopped updating and now, most noticeably **Subscriptions (Library Integration)**. If you still rely on that, no use updating.

**Comment by kodiadon** [comment]
Thank you Tikipeter for your answers, I found it very helpful.

I only have Kodi installed on my Nvidia shield, which I just bought about a month ago. Before the Shield I had the 4K Firestick.  I've never installed Kodi onto my computer or phone. I do have the old version as a zip just in case.
I think I did uninstall everything  but I can't be sure.  What I did was open Kodi...addons..highlight Fen then choose uninstall. A box popped up asking if I wanted to uninstall all the settings as well, I chose Yes.  Then I did the same for Open Scrapers...deleted it and all the settings. After that I restarted Kodi.

After installing the newest version and setting up My Accounts with Real Debrid and Trakt,  I also sync Fenom scrapers and Fen with my accounts. Then I watched one TV show  and it worked perfect.  After that show ended I wanted to watch the next episode and problems came. It scraped and I saw the count going up, then it said no links available. So I tried to rescrape and select source and the blue wheel just kept spinning for about 5 minutes so I backed out of Fen. opened up My accounts and my user name for Trakt was still there but my Real Debrid user name was empty. So I Reauthorized it again and re-synced everything again for the 2nd time.  Watched the second show and so far-so good. I'm going to see how it goes for the next few days and I'll let you know.

I know I'm supposed to submit a log file, but I'm not asking for you to troubleshoot the problem, I'm just letting you what I've done so far. If I continue to have problems, I'll do the log file.

Fen is truly unique, very fast, customizable, and has a Dev (Tkipeter) that listens to users requests and problems and tries to fix them quickly.  Thank you for all the work you've done.
