### ISSUE TITLE
Fen Integrated Library bound to play through Fen ?

### ISSUE THREAD

**Issue by Nazim1981** [Tikipeter/repository.tikipeter#370]
I love Fen , I have a massive library using Fen subscription now I went to Kodi 19 where Fen is not supported , my problem is I want Fen integrated library to play through some other addon like Seren which is only addon who is compatible to Kodi 19 , how can I lift Fen addon restrictions from library integration so that it will give me options to play other addon as well ?

**Comment by Tikipeter** [comment]
Why did you move to Kodi 19?!?!

I have never seen somebody do so much to make Kodi unusable! And yet you are still getting by! Kudos to you I suppose.

I'm going to try and help you out, because I've been keeping an eye on your story for a while now. Just answer a few questions and I'll see what I can do based on your answers. I may have to make you a little addon to get what you want.

1. I'm assuming you absolutely are unwilling to move your integration handling to TMDbHelper. Is this still correct?
2. Are you willing to use TMDbHelper as a "bridge" to get to Seren playback?
3. Are you willing to have Fen installed on your Kodi 19 system, even though at the moment you can't play back using it on Kodi 19?
4. What file structure do you have for your movie and tvshow .strm files? Is there one folder with all the movie folders inside and one folder with all the TV Show folders inside?

Answer those and we can go from there..

**Comment by Nazim1981** [comment]
The only reason to move kodi 19 for HDR , i am tired of playing 1080p
whereas i can stream UHD remux 60 GB file easily. I was waiting for one
addon to work with Kodi 19 and here it is .

Kodi PC can handle biggest library in ease thanks to your subscription i
have 16000 media included half million episodes with all kind of artwork
and ratings using Titan Bingie mod 100% look and feel better then native
netflix app with hundreds of personal playlists and premiumizer for results
, every movie & show is there you name it.

1- I have no option on single click to select the choice of player , all i
have long press to select tmdbh , then player then addon ,each time with 3
steps , but kodi 19 dont have tmdbh and  context menu or i am unlucky due
to dependencies error 2.26.0 doesn't satisfy

2- Yes i am willing for 3 steps Tmdbh in Kodi 19 .

3- Fen is always my primary source , when i cant find desire results then i
use Seren , and this never happened in the case of movies search  but TV
Shows , Fen is little lacking in TV shows results whareas Seren is better
in Tv shows finding .
I will keep waiting Fen to release for Kodi 19 .

4- One Folder of "Movies"  and inside all movies name folders in .strm
format
One Folder of "TV Show" and inside all tv shows name folders in .strm
format .

**Comment by Nazim1981** [comment]
Edit : tmdb installed but  players  & context menu unable to install .

**Comment by Nazim1981** [comment]
I raised a request for tmdbh context Menu in jurialmukey github 
they answer , it wont work other then tmdbh items

https://i.postimg.cc/3Rnb2VY5/image.png

Now only you can solve it .

**Comment by Tikipeter** [comment]
In the first post above, you originally included an image that implied Fen was not installed on your Kodi 19 setup.

Is this not the case anymore? Do you in fact have Fen installed now?

And if so, what version?

**Comment by Nazim1981** [comment]
Fen were never installed on Kodi 19 till now. But I saved my Library folders and gave path to Kodi 19 Library to reflect. Now my library is ready , Seren is ready , tmdbh installed and ready . but I cant use library item because when I click to play there is No Fen to play them because its integrated through fen ( something in .strm who is bound to Fen )  , so i tried to use tmdbh context to use seren play for library contents but tmdbh doesn't show in context menu other them tmdbh items. so huge library data is wastage unless Fen release for Kodi 19 or any context menu who might illegible to show all players  .

**Comment by Tikipeter** [comment]
Ok. I understand.

My idea is to make you a "dummy" addon called plugin.video.fen, so that it can accept the command from your strm files, and then hand the playback to TMDbHelper. If you set Seren as the default provider, then you would need only a single click for playback. If you don't set Seren as default provider, then you will need 2 clicks for playback.

To be 100% sure on this:
* You DEFINITELY have TMDbHelper installed on Kodi 19?
* You DEFINITELY have the players installed for TMDbHelper?
* You DEFINTIELY have Seren installed on Kodi 19?

If those 3 things are true, I have an idea of what I might be able to do to get this sorted for you. But please remember, I won't be able to test this, and I'm certainly not 100% sure it will work. But, it's worth a try....

**Comment by Nazim1981** [comment]
Yes that's what i want , seren default ok , library updated , tmdb matrix
installed , players manually placed in tmdbh " players" folder.

**Comment by Tikipeter** [comment]
Install the zip file below into your Kodi 19 setup and see if it works (UNTESTED):
[plugin.video.fen-DUMMY_SHELL.zip](https://github.com/Tikipeter/repository.tikipeter/files/5867507/plugin.video.fen-DUMMY_SHELL.zip)

**Comment by Nazim1981** [comment]
Unfortunately no luck. First of all windows10 think it's virus, i had to stop virus check. After installation , Kodi behave like auto working , its auto get back from current screen , and it doesn't work on library contents . i will wait for it after reading the new announcement made by your side.
