### ISSUE TITLE
Recent episodes not listing....

### ISSUE THREAD

**Issue by medievil1** [Tikipeter/repository.tikipeter#385]
dunno if it is an actual issue, something I need to do or new setting I need to change or what...
All of a sudden (past couple of weeks) searching tv series no longer show all the season episodes... what was once 7 episodes listed (3 in red cause they hadn't yet aired) is now 3 episodes last one mid January, I've reauthorized trakt, have a TMDb account/session id, etc... cleared cache's, FEN has even been reinstalled....
Not sure what other steps to take . on latest release

LOG file 
https://paste.kodi.tv/giceqexote

**Comment by Tikipeter** [comment]
Does this happen for all shows? Some shows? One show?

Give me an example and I'll test when I get home.

Sounds like incomplete metadata from TMDb.

**Comment by medievil1** [comment]
kindred spirits
Ghost nation 
I can't say it is 100% all shows, but seems like all I have tried recently

**Comment by Tikipeter** [comment]
KINDRED SPIRITS: I'm afraid that's the info TMDb return for that show. Nothing Fen can do about it.
GHOST NATION: I'm afraid that's the info TMDb return for that show. Nothing Fen can do about it.

Like I thought, both of the 2 shows you've quoted have incomplete metadata on TMDb. Since Fen has now switched to TMDb out of necessity, there isn't anything I can do about this. This is the info that is given.

It looks like it's time to get your hands dirty, jump on TMDb's website, and update the info for those 2 shows. Wait an hour for th API to update, then refresh the cache in Fen for those shows and they'll pull in the new, correct data that you have filled in on the TMDb website.

People are going to have to step up and help TMDb's TV Show database get up to speed moving forward, now that TVDb is not an option for metadata.
