### ISSUE TITLE
Trakt issue in FEN

### ISSUE THREAD

**Issue by jamos316** [Tikipeter/repository.tikipeter#386]
Hi

In 'Next Episodes' under 'TV Shows' it shows 2 TV shows that has episode numbers that do not exist, I have checked on trakt website and it doesn't show the episode and all others are marked as watched. When I try to mark that episode as watched on trakt in FEN it shows Trakt error 429. So how do I get rid of this episode?

The 2 episodes are;
When louis met 2x05
First dates 16x04
You will see if you search for these on trakt that it does not exist so where are these coming from if not trakt.tv? 

Hope I explained this OK, im a newbie 😂 

James

**Comment by Tikipeter** [comment]
TV Show data for Fen ALWAYS comes from TMDb now, having previously come from TVDb. I do not query Trakt for Movie OR TV Show data.

TMDb has 5 episodes in season 2 for "When Louis Met". The fifth episode is titled "Living With Louis". Trakt has this as a "Special". If it is a special (and it looks like it is), then TMDb's data needs to be corrected for this show.

"First Dates" aired it's 4th episode of Season 16 on the 9th February 2021.

There is nothing I can do for either of these two occurrences. In the first instance (When Louis Met), TMDB's data looks wrong. In the second instance (First Dates), Trakt's data looks wrong.

Fen has no way to decide who is supplying it with correct or incorrect data.

Also, you need to include a log file when opening an issue.

**Comment by jamos316** [comment]
Thanks for the reply

**Comment by jamos316** [comment]
As I don't get this issue with other movie scrapper addons in Kodi can I
assume that these addons use Trakt for their metadata while Fen uses TMdB.
If this is the case is there a way to change the source from TVdB to Trakt
in Fen to fix this issue.
Just annoying that Fen is telling me these shows are next when I've already
watched them and marking them as watched in trakt doesn't work.

**Comment by Tikipeter** [comment]
>As I don't get this issue with other movie scrapper (sic) addons in Kodi....

Other addons are still using TVDb for metadata. Fen switched from using TVDb (to which the issues like yours above were not a problem), to TMDb a few weeks ago. This was necessary as TVDb are moving to a paid only, subscription model in March of this year. On top of that, nearly all unnofficial Kodi addons that interact with TVDb do so using the v1 API, which TVDb will turn off completely in March of this year. So they will very soon ALL stop working.

>...I assume that these addons use Trakt for their metadata while Fen uses TMdB.

They use TVDb, which wil effectively stop working in March.

>... is there a way to change the source from TVdB to Trakt in Fen to fix this issue.

No. Whilst Trakt does provide some metadata info for Movies and TV Shows, it is not a viable alternative to use it for that purpose. It has a rate limit on it's API which would likely be met consistently if used for metadata, and it also doesn't provide images. So there'd be no posters or fanart from Trakt for all Movies/TV Shows.

>Just annoying that Fen is telling me these shows are next......

As I said, nothing can be done at the moment. This is all due to TVDb changes in March, and the need for addons to now use TMDb for metadata, or accommodate TVDb's paid model (I'm not doing that).

You have 4 choices here..
1. Switch to a different addon that displays your Next Episodes correctly (but will not work at all for TV Shows come March).
2. Go to the TMDb website and fix the issues that it currently has with the shows you mentioned (this is what people should be doing).
3. "Hide" the shows that are giving you trouble from your progress in Trakt.
4. Accept the annoyance of these shows displaying and wait for Trakt to finish THEIR migration to using TMDb instead of TVDb for THEIR metadata (this is currently happening).

**Comment by jamos316** [comment]
Thanks for your detailed answer!
