### ISSUE TITLE
Download notification broken.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#434]
I noticed the Download notification is broken, if fixed,can you set the minimum % to 1 also instead of 2%?
I can post the log,but i see no errors in it,or maybey you can help how to log it.

If it is at 100% (so downloaded), then i get the Download Succes pop-up,so that one is working fine :)

**Comment by Tikipeter** [comment]
I'll have a look now Tinuz and see what's going on...

**Comment by Tikipeter** [comment]
![screenshot00001](https://user-images.githubusercontent.com/28930002/112736909-7bd98f80-8faa-11eb-8c81-9241291bdf56.png)

OK. This is going to be hard to explain. :)

Firstly, the notification wasn't broken.

The issue is if the notification is active (showing) when you press "Back" to back out of the results window, then it will break the notifications and they won't show for the remainder of the download (this is a Kodi bug).
Since (I assume) you currently have your notifications set to show every 2% of progress, then there would be a notification showing right from the start of the download, meaning when you hit "back" to exit the results page, it is going to break the notifications every time.

You would need to wait until the notification wasn't showing anymore to back out of the results window. Again, since you have it set for showing every 2%, that likely will never happen (there will always be a notification active on screen).

To fix this, I can have the first notification not appear until at least 10 percent of the file is downloaded, and then continue at the rate (2% or whatever) after that. That would give you time to back out of the results screen before the first notification appears at 10%.

Let me know what you think. I don't think there's another way around this though.


Oh, I'll change the minimum % for notification progress to 1% for next update as well.

**Comment by Tinuz97** [comment]
Is it broken in Aeon nox silvo mod skin maybey then?
Because it got 'broken' for me since download module changes (I think) in Fen.

Because the notification does not pop-up for me (not hitting any buttons).

**Comment by Tikipeter** [comment]
As a test, change your notification percentage to 10%, and try a download. Make sure to back out of the sources window before the first notification shows.

I'll try on Aeon Nox Silvo.

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/112737546-703c9780-8faf-11eb-83b6-6b256579bbb7.png)

Aeon Nox Silvo working OK.

**Comment by Tikipeter** [comment]
I'd say the wait until 10% at a minimum will fix this. I just set the notification to 1%, and with that wait built in, it worked OK.

I'll push a mini update soon so you can see if it works for you.

**Comment by Tinuz97** [comment]
This is weird.
Moved the slider from 2 to 16%, clicked OK, moved it back to 2%,clicked OK, now it is working.

**Comment by Tikipeter** [comment]
Ah good. Perhaps the setting Fen was looking for might not have been written properly to the settings file. I'll ad a check for that as well.

I might hold off on the update if it's working for you now. There's a few more things I'd like to get sorted first.

**Comment by Tinuz97** [comment]
Yeah working now, no issues further 💯

**Comment by 123Venom** [comment]
@Tinuz97 need some Dutch translations for new settings being added to FS and MA, thanks in advance

Write FenomScrapers log in reverse order
Clear FenomScrapers log file
View FenomScrapers log file

Write My Accounts log in reverse order
Clear My Accounts log file
View My Accounts log file

**Comment by Tinuz97** [comment]
@123Venom  (same order as above here the translations) 

Schrijf Fenomscrapers log in omgekeerde volgorde
Wis het Fenomscrapers logbestand
FenomScrapers logbestand bekijken

Schrijf Mijn Accounts log in omgekeerde volgorde
Logbestand Mijn accounts wissen
Logbestand Mijn Accounts bekijken

**Comment by 123Venom** [comment]
forgot one, or should I say I decided to add yet one more feature to FS and MA

Upload FenomScrapers log file to pastebin
Upload My Accounts log file to pastebin

**Comment by Tinuz97** [comment]
@123Venom (translations in the same order as above here). 

Upload FenomScrapers logbestand naar pastebin
FenomScrapers logbestand geüpload naar:

Upload Mijn Accounts logbestand naar pastebin
Mijn Accounts logbestand geüpload naar:
