### ISSUE TITLE
Random show appearing in next episodes

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#437]
![20210331_160142](https://user-images.githubusercontent.com/76907836/113166282-8742ea00-923a-11eb-9e53-afc99c9c93e8.jpg)

Hi mate sorry but I don't suppose you would know why this show has randomly appeared on my next episodes? I've never watched or heard of it, marking as unwatched in trakt does nothing it still keeps it marked as watched, I've also tried clearing all cache and even fresh installed fen.

**Comment by Tikipeter** [comment]
No idea. It looks like this show:
https://www.themoviedb.org/tv/119272-horizonte?language=en

Which has a tmdb id of `119272`.

Firstly, go into TV Shows->In Progress TV Shows and see if it is included in that list. If so, try and mark it all as unwatched there.

If that doesn't work, navigate to TV Shows->Next Episodes, bring up context menu on any item, and select "Next Episode Manager". Choose "Manage In Progress Shows". From that screen, find Horizonte and select it so that it changes from "[INCLUDED]" to [EXCLUDED]". Navigate back to Next Episodes and hopefully it is hidden.

If none of that works, you'll need to install a Fen version with some logging so I can see where it is coming from.

**Comment by JFG1000** [comment]
Trued all of the above mate and i still have no luck unfortunately, it won't let hide the show either, I did message you on Keybase if it would be easier to discuss it further there?

**Comment by JFG1000** [comment]
UPDATE : ended up creating a new trakt account which has solved my issue. Thanks anyway mate
