### ISSUE TITLE
Movie appearing in trakt list - new shows by Gary

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#457]
Hi there for months now when using Fen if this trakt list for new shows

https://trakt.tv/users/garycrawfordgc/lists/new-shows?sort=added,asc

Is a liked list, for some reason a movie called "The last word" appears at the start, and it never goes away, I've checked on the website where the list is hosted and it does not display that film, 

I have also made 2 comparisons, first screen shot shows fen with the liked list displaying the movie, the second is venom with the same list, not displaying it 

![20210512_211717](https://user-images.githubusercontent.com/76907836/118039413-38738e80-b368-11eb-82d3-3dc37528b322.jpg)

![20210512_211638](https://user-images.githubusercontent.com/76907836/118039460-46c1aa80-b368-11eb-9516-87e9b511feec.jpg)

I have also provided my kodi log here 

http://paste.ubuntu.com/p/VtZBSRmszd

Nvidia Shield, Auramod Kodi 19.1

Many thanks

**Comment by nived0999** [comment]
Which skin is this?

**Comment by JFG1000** [comment]
Auramod

**Comment by xyzfre** [comment]
> Hi there for months now when using Fen if this trakt list for new shows
> 
> 
> 
> https://trakt.tv/users/garycrawfordgc/lists/new-shows?sort=added,asc
> 
> 
> 
> Is a liked list, for some reason a movie called "The last word" appears at the start, and it never goes away, I've checked on the website where the list is hosted and it does not display that film, 
> 
> 
> 
> I have also made 2 comparisons, first screen shot shows fen with the liked list displaying the movie, the second is venom with the same list, not displaying it 
> 
> 
> 
> ![20210512_211717](https://user-images.githubusercontent.com/76907836/118039413-38738e80-b368-11eb-82d3-3dc37528b322.jpg)
> 
> 
> 
> ![20210512_211638](https://user-images.githubusercontent.com/76907836/118039460-46c1aa80-b368-11eb-9516-87e9b511feec.jpg)
> 
> 
> 
> I have also provided my kodi log here 
> 
> 
> 
> http://paste.ubuntu.com/p/VtZBSRmszd
> 
> 
> 
> Nvidia Shield, Auramod Kodi 19.1
> 
> 
> 
> Many thanks 
> 
> 

Just noticed the same issue here with the same TV show it always shows up first and I also did a￼ comparison with venom and it doesn't show up￼￼

**Comment by Tikipeter** [comment]
Intersting. I'll look into it and see what's going on.

**Comment by JFG1000** [comment]
Thanks Peter much appreciated

**Comment by Tikipeter** [comment]
2 issues here.
Firstly, that movie IS in the list by garycrawfordgc. It is meant to be at position 138 in the list when sorted correctly as defined by the trakt sort order. You can see it below in the list from the trakt website. First item in that middle row:
![last_word](https://user-images.githubusercontent.com/28930002/118158404-127ce580-b45f-11eb-96bb-b7528e5b65ed.jpg)

If you were to go to Venom, and access the "New Shows" list through `My Movies->Movie Lists` you will see it there as the only result from that list. Venom (and Exodus forks) will separate the contents of the list into either `Movies` or `Shows` depending on where you entered the list from i.e. Movie Lists or TV Show Lists. Fen doesn't work that way, I include Movies and TV Shows in the list always, as the list maker intended. If a list has both Movies and TV Shows in it, that is how Fen will present it.

So, in saying all that, the actual error is to do with the fact that the movie wasn't sorted in the correct position in the list; instead always showing up first.

This will be fixed in the next update, as shown below:
![last_word_correct_position](https://user-images.githubusercontent.com/28930002/118159351-44db1280-b460-11eb-8d70-7582bee092c6.png)

Since this is meant to be a TV Show list, likely garycrawfordgc has made an error in including this movie in his list, but it is there and thus will be shown by Fen.

Anyway, fixed for next update.

**Comment by JFG1000** [comment]
Legend, much appreciated mate as always thankyou for your hard work with everything and explaining it all. Respect

**Comment by nived0999** [comment]
> Auramod 
Auramod released for K19?cannu give the repo link pls...

**Comment by JFG1000** [comment]
No official repo as of it so updates need to be downloaded from github

https://github.com/SerpentDrago/skin.auramod/tree/Matrix
