### ISSUE TITLE
Easynews long time before playback starts

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#458]
Hi Tiki, since already sometime all the playbacks from easynews links take very long time to start. I could say about 2 mins while kodi is freezes in the meantime but without any error. The links from Furk or RD/PM are instantaneous instead. Is there any settings I should take care on Fen or EN website? As I can see v2/v3 switch in Fen in not there anymore. On EN I m using as usual the latest Interface (I guess it is v3) and closest server (though I tried Europe and E.USA without any significant improvement).
I m not attaching any log because I did not see any error but if you need one no problem to get it.
Pls advise.
Thanks

**Comment by ReaLx3m** [comment]
Its a problem with Kodi 19.1, they did some change that affects EZN(also sometimes RD, but rarely). You can roll back to 19 for the time being.

**Comment by Tikipeter** [comment]
Hi sasagr. :)
As ReaLx3m says, there is an issue with Kodi 19.1, that is exactly the issue you're describing. So assuming you've updated to 19.1, your only option to fix this issue at the moment is to downgrade to 19.0

Unfortunately I have had to do this on my Windows install. I was hoping maybe this issue was affecting Windows only, but I know you use Apple so it seems that's not the case.

**Comment by sasagr** [comment]
Yes, reverting to 19 seems to have fixed the issue also for the Apple TV . A “thanks” to both ReaLx3m and Tikipeter for the advise. Maybe it is worth it an announcement in the changelog preview as a warning till there is green light to future updates?

**Comment by Tikipeter** [comment]
That's a good idea. I'll include a warning in the next changelog.
