### ISSUE TITLE
kodi crash

### ISSUE THREAD

**Issue by shahaf1122** [Tikipeter/repository.tikipeter#465]
hi, 
i am using fen with the skin.arctic.horizon
and all the time after i play a movie/tv show from fen the kodi crash
[kodi.txt](https://github.com/Tikipeter/repository.tikipeter/files/6534545/kodi.txt)

**Comment by Tikipeter** [comment]
1. Your log file is useless. You have to upload a whole log file for there to even be a chance of it holding any value.
2. What troubleshooting steps have you taken to address this issue? Please list all the things you have done so far to troubleshoot this.

**Comment by shahaf1122** [comment]
I did a clean install of kodi.
I install the skin.arctic.horizon and i remove all the widgets and shortcut from home screen.
I just go to to tv series and play a episode and when i press stop the kodi say busy and crash.
I checked with other addons like shadow and seren and they nor crashing...
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6535111/kodi.log)

**Comment by Tikipeter** [comment]
I can't make it happen I'm afraid.
Some troubleshooting options:
1. See if it happens with any other skin.
2. Set to FALSE "Reuse Language Invoker" (found in Tools).
That's about it really.

**Comment by shahaf1122** [comment]
1. it only happen in this skin and I contact the skin developer and he say it a problem with the addon with FEN.
2 it look like It solved the problem I did a clean install and i try a few episodes and it worked!
thanks for all the help, I hope the problem not show again....
and your addon is amazing you did an amazing job.

**Comment by Tikipeter** [comment]
1. It's definitely not a problem with the addon if it doesn't happen with other skins. But it is a problem with Kodi, and how it interacts with addons/skins. It's almost certainly caused by using the "seasons" type views, where the skin populates the episodes on the fly based on the season you have highlighted. That is a hack done by skins, not Fen, and it can fail causing a crash especially if reuse language invoker is turned ON. If that's true it would only happen on episode playback and not movie playback. Worth a try if you want to test it, but turn the Invoker back on first.
2. Glad it worked.
