### ISSUE TITLE
Trakt Items not populating

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#473]
Hey there recently I've noticed when things are added to my movies watchlist they do not appear in fen unless i clear the trakt cache, did you need a log for this or is it something you are aware of? Many thanks

Nvidia Shield Pro
Kodi 19.1

**Comment by Tikipeter** [comment]
It's expected behavior.
Unless you add something to Trakt from within Fen, then you will need to clear the cache/wait for the item to show in Fen. This is because ALL calls to outside services like Trakt are cached by Fen. This lightens the load on the online services.

The best you can do to alleviate this is to cut the trakt cache time down to 1 hour in the settings.

**Comment by JFG1000** [comment]
No worries, the reason i ask as it's happened before where i had added something from my phone in the morning via and app to the watchlist, it did not populate when i loaded kodi that following evening so wasn't sure it that was expected behaviour
