### ISSUE TITLE
Enhancement: Next Page item for widgets

### ISSUE THREAD

**Issue by Logs22** [Tikipeter/repository.tikipeter#482]
I looked through settings everywhere that I could and could not find any setting that would enable a "next page" sort of button to be added to the end of a widget row. Ideally, the functionality would open that list up inside fen, on the next page that the widget could not display because of item limits.

if i am just blind, or this is impossible please let me know

Random log for the rules - https://paste.kodi.tv/osizerakos

Edit: this actually is probably a skin issue, apologies, I didn't test enough and just assumed. The items that are cut off are trakt items, however i have them set to a 40 item limit in the Fen settings, and a 50 item limit in the skin settings for the widgets. The skin is showing 50 items instead of 40, does the trakt widget item limit not work like i assume it does? I also tested this on another skin just to confirm and the same thing happened, the widget displays the item limit determined by the skin, and not what is selected in the trakt settings of fen

**Comment by Tikipeter** [comment]
Few things here.
The easiest to explain is the "Max. Items" setting in the Trakt portion of Settings. This setting is only for widgets from the "TRAKT: Widgets" section of "My Lists". They are special lists made by Fen that could be handy to have as a widget. All other widgets made using Fen are not affected by that setting.

As for a "Next Page" on the widgets, this is disabled  because skins usually have their own "More..." or "Continue..." or "Next Page..." that they use themselves. Because of this I disabled the "Next Page" that would normally show. The other reason it was disabled was because if people wanted to have the widget items shuffled by the skin, then the Next Page would of course be shuffled as well, and could end up anywhere within the list.

I can add a setting for next update to toggle whether to show the "Next Page" or not, but if your widget has 50 items and you set it from the skin's settings to only show 40, then one of the 10 that will not show will be the Next Page, as it's at the end of the list.

When possible, use an addon's settings to limit the number of items in the widget.
Fen's general setting for limiting items per page (or widget) is Settings->General->Navigation->**Paginate Lists When Possible**.

**Comment by Tikipeter** [comment]
With regards to the "Max. Items" setting within the Trakt portion of Fen's settings, that is only for specific lists made from the "My Lists->TRAKT: Widgets" section of the addon. All other widgets made from Fen lists do not honor that setting.

There is a Next Page item when Fen makes the list that the widget will use. If you use the skin's setting to cut the list short, then the Next Page item will be cut because it is always at the end.

You are better off using an addon's setting if possible to limit list (or widget) item numbers.
For Fen that would be Settings->General->Navigation->**Paginate Lists When Possible**. That setting will limit the amount of items for things like Trakt/IMDb personal lists, Favorites, etc. Basically any list that isn't generic such as Trending. Popular etc.

**Comment by Logs22** [comment]
> Paginate Lists When Possible. That setting will limit the amount of items
ah, i actually did not know that that is what that setting did. When setting a Paginate value that did make the next page label show up, so that fixes my issue. Thanks a lot for the in depth reply!
