### ISSUE TITLE
Weird issue, crash after exiting playback of a movie from a Fen widget

### ISSUE THREAD

**Issue by Logs22** [Tikipeter/repository.tikipeter#483]
Hi again, im sorry to be writing another issue. This one is a rather weird one, and one that I don't quite have a grasp on at all. Im pulling from My Lists < Movie Collections as my starting playback widget. Starting playback, scraping, and playing the movie all works fine. However, when exiting out of the player I often get a crash, or a playback error that says "check log for more info" (paraphrased). 

Here are two logs where crashes happened after exits, the first was after cars 3, the second was after Avengers Infinity War.

First - https://paste.kodi.tv/zarapiciya.kodi

Second - https://paste.kodi.tv/onumucaleq.kodi (this one is a debug log, thought that might but helpful if you needed it)

I tested this on two different skins (Titan bingie mod and arctic horizon) and had crashes on both. Please let me know if you need more info, 

Heres a video of the issue, and the log of that video

https://streamable.com/mo0ght

https://paste.kodi.tv/ekagocobos.kodi

Edit: Looking at the log myself, I thought it might have been skin helper service widget that was causing the crash. I deleted it, along with skin helper service and the crash still persists.

https://paste.kodi.tv/onuvoyomaq.kodi - thats a log with Skin helper service widgets uninstalled. Sorry for so many logs

**Comment by Tikipeter** [comment]
Turn OFF "Reuse Language Invoker" at the bottom of the list of items in Fen's `Tools` menu. That should sort this out hopefully.

**Comment by Logs22** [comment]
Yup that did indeed fix all the crashing. I still get a playback error in Titan bingie mod, but not in Arctic Horizon. I'm assuming that that is a skin issue since it is not happening on both?

**Comment by Tikipeter** [comment]
No. There shouldn't be a playback error. Perhaps if these are library items and not direct Fen items there could be a playback error. But Fen doesn't support library integration anymore.

**Comment by Logs22** [comment]
yea I would understand that, (ive got a history with it lmao) these widgets are coming directly from the My Lists < Movie collections tab in fen

**Comment by Tikipeter** [comment]
I'll install that horrible skin and have a look what fresh hell it's up to. :) :)

**Comment by Logs22** [comment]
hahaha sorry, I think it has something to do with the "netflix" window play type that it does

**Comment by Tikipeter** [comment]
Yep. Just seeing that now. That's Kodi's "Info" screen. Whilst Fen will allow playback from that screen, there will be that default Kodi warning after playback ends because I don't use `setResolvedUrl` in Fen. I use direct playback.

You might like that info screen popping up before playback. If you don't care about it though, and would like to get rid of that default Kodi error after playback, you would have to turn off the setting to show it.

`Skin Settings->Homescreen Layout->Widgets->Set Default Select Action to Show Information`

No way around it though, unfortunately.

**Comment by Logs22** [comment]
Thanks, i might just do that honestly since all the other items in there are for library basically and can't be used, faster that way as well. thanks for taking the time to look into it as well!

**Comment by Tikipeter** [comment]
No problem.

Weigh the concessions you're making against the benefit of using Fen as well. No addon is for everyone. It would be better to have the setup you want and pick an addon that accommodates that, rather than changing your setup to accommodate an addon that sometimes does things differently. Just something to think about, but I'm sure you've done that already.

I don't know why, but I always figured you were a library guy. I can only think that comes from interactions here in the past. Are you trialing replacing the library with direct widgets?

**Comment by Logs22** [comment]
nah I'm actually trying to make something fairly easy for family members/friends, library is still my preferred go to atm because i have it figured out, and syncing is working well for my needs. I love being able to customize with artwork a lot and the loading times being really quick.

Other addons have been a bit finicky recently, but in my testing fen has been easy to setup and has worked well with pretty much everything, consistently being the fastest (although I'm throwing that out the window with bingie lmfao). I can't say there's one addon i love 100%, so I'm always in between a couple, but for this project stability is the main concern, and Fen seems to be the most stable at this time compared to other options!

**Comment by Tikipeter** [comment]
>...Fen seems to be the most stable at this time...

I'm about to drop an update, so hold that thought. :)

**Comment by Logs22** [comment]
hahaha ill do my best to break it then ;)
