### ISSUE TITLE
Widget paths [QUESTION]

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#49]
Fen is undoubtedly the fastest add-on on the block. That being said I started running into issues that were skin-based and that upset me because well, Fen is uber fast. It deserves a skin that can keep up with it. So I went back the default Estuary skin cause I know Fen is FAAAST on that skin. The downside in my eyes was no widget support in the skin among other things. So I tried my hand and dove into the code to get it to support widgets from Fen. After a few days I finally figured it out! The best part is no TMDb Helper, SkinShortcuts, or library integration. The skin pulls straight from the XML so it is LIGHTNING fast as there is nothing to weigh down Fen. Now I have a custom version of Estuary solely built around the usage of Fen! I named it FENtastic and I'm quite proud of it. This is where my question comes in.

I noticed that only the Next Episodes widget refreshed itself after playback but all the other ones didn't when adding or removing something from the widget list. So my question is, when using Fen widget paths like `plugin://plugin.video.fen/?action=trakt_collection_lists&amp;iconImage=trakt&amp;mode=build_movie_list&amp;new_page=recent&amp;name=Recently+added`, is there something I can append to the end of the path to make the widgets refresh when I've added or removed something from the widget list? Something like `widgetRefresh=true`? Or is this happening because the widget is pointing to a shortcut folder and not the original menu item in Fen?

**Comment by Tikipeter** [comment]
Great job on this. It feels great to achieve something like this.

I'll answer you question first: unfortunately no, there is nothing to append to the paths to force the widgets to refresh.

Great job on this. It feels great to achieve something like this.

Some info for you:
Kodi itself handles refreshing of home widgets based on a few triggers. The pertinent ones are
* Start/End of media playback.
* Upon finish of a library update.

Addons can manually trigger a widget refresh by faking a Kodi library update. Usually `executebuiltin('UpdateLibrary(video,special://skin/foo)')` is used. the `video,special://skin/foo` is a fake file path that doesn't exist. This means Kodi checks that path for updated items for the library, and immediately sees that it is not a valid path, and the library update finishes immediately. Even so, the library update was triggered, so the widgets are reloaded.

Addons on many occasions need to refresh containers (within the addon) or widgets (on the home screen). In Fen, I have a function that will do an `executebuiltin('Container.Refresh')` if you are inside Fen when it is called, or a `executebuiltin('UpdateLibrary(video,special://skin/foo)')` if you are on the home menu.

But, I have not implemented that everywhere throughout the code, and upon looking this morning I see that only container refreshes are being done for all the Trakt related code that refreshes like adding/removing an item from a list etc. So that is something I can change for you for next update (due soon). That will mean if you are on the home window, and perform an add/remove from the lists you have there, they should trigger the `executebuiltin('UpdateLibrary(video,special://skin/foo)')` and refresh.

The issue there is if you are within Fen, and perform a task like that, then Fen will only perform a container refresh, not a fake library update widget refresh.

If you'd be willing to post a zip of your skin mod, I'll have a good look at it and see how much I need to do within Fen to get it working properly for you.

There's also "tricks" like using `<onload>` at the top of the Home xml, and putting some Kodi command in there that would trigger a widget reload every time the home page was loaded. I could look into things like that for you as well.....

**Comment by ivarbrandt** [comment]
> Great job on this. It feels great to achieve something like this.

It sure does, thank you. I find myself wanting to tweak the skin more and more. It's fun.

> So that is something I can change for you for next update (due soon)

Yes please do. And thank you for all of that information. I understood it from a process point of view but I have no idea where to put that in the code or what the syntax would even look like.

> If you'd be willing to post a zip of your skin mod, I'll have a good look at it and see how much I need to do within Fen to get it working properly for you.

I have attached my skin mod here! Thank you! Also, could you please mark in the code where you made changes? I want to know where to look so I can see what you added/changed.

> There's also "tricks" like using <onload> at the top of the Home xml, and putting some Kodi command in there that would trigger a widget reload every time the home page was loaded. I could look into things like that for you as well.....

What is the difference between using `<onload>`, a container refresh, and a fake library update? What are the advantages of using <onload> vs the other two? Are these all just different methods of achieving a widget refresh?

Again thanks for the detailed reply. I appreciate being able to learn from you.

[skin.FENtastic.zip](https://github.com/Tikipeter/repository.tikipeter/files/9737917/skin.FENtastic.zip)

**Comment by Tikipeter** [comment]
>What is the difference between using <onload>, a container refresh, and a fake library update? What are the advantages of using <onload> vs the other two? Are these all just different methods of achieving a widget refresh?

If you put an `<onload>do something here to make widgets refresh</onload>` at the top of your Home xml, then each time it is loaded, the widgets will refresh. It's just another option to think of.

I will download and install the skin and see what has to be done on Fen's end. Hopefully it can work out OK for you.

If I make any changes to the skin I'll mark them so you can find them.

Unfortunately, I'll be working for the next couple of days, so I won't have a lot of time. But I'll push the Fen update tomorrow with the changes I already know are needed and that might well be good enough anyway.

**Comment by ivarbrandt** [comment]
> It's just another option to think of.

Ah now I understand. I don't think I'll be using this since you'll be adding the fake library update and from my understanding this will make it so there is no need to refresh the widgets when loading the home page. Actually, could you please add this to the Home.xml anyways and just comment it out? I will decide later if that's something I want to use.

>  I won't have a lot of time

That's totally cool. I  completely understand. Thank you for letting me know. Drop the skin here whenever you get a chance. I'm excited to test out the new Movie Sets feature in the upcoming update! Thanks again.

**Comment by starman2908** [comment]
[skin.FENtastic.zip](https://github.com/Tikipeter/repository.tikipeter/files/9737917/skin.FENtastic.zip)

@ivarbrandt Great work on this. I'm using it as my go to skin and love the addition of the clear logos in some of the views. Kudos! I was wondering if I could ask for a bit of help as I'm not an advanced skinner. I'm trying to sort out the Infowall view as the grid of episode list items seem to overlap a bit and the episode text doesn't appear in the bottom boxes [Sreenshot](https://imgur.com/jvbUc9g) . 

Just wondering if you had done any more work on the views that you'd be willing to share? If not, I was wondering if you would mind giving a bit of advice as to what parts of XML code I could tweak to try and align them myself. I have tried for a few days, broke the skin a few times ha, so thought I'd be best to reach out for help. 

Appreciate your effort, thanks again!

**Comment by ivarbrandt** [comment]
@starman2908 I'm glad you like it!

Yeah I noticed that changing the widget for Next up messed up the Info Wall view. I couldn't figure it out so I was fine leaving it alone cause I don't use that view anyways. 

I'm glad you were able to figure it out. I'll probably have a deeper look at it later. Hopefully I can fix it too.

**Comment by starman2908** [comment]
@ivarbrandt took me two days to find it lol, but its about line 420 in the infowall view XML ... Changed the width to 380 and it that seems to have taken care of the overlap. I've a new fou.d respect for Skinner's...mind must be easy when you know how 🙂

**Comment by ivarbrandt** [comment]
@starman2908 Awesome thanks!

Lol I understand completely. I felt the same way when I started digging into the code.

**Comment by tundrablasen** [comment]
@starman2908 @ivarbrandt 

do you might want to share the current state of The fentastic skin? Is the upper .zip the latest iteration? couldn’t follow now who had made the latest changes.

I was looking for exactly the same like you guys. Estuary for fen with widgets.

**Comment by ivarbrandt** [comment]
@tundrablasen 

That version that I shared above is the latest version for Matrix. Actually it's the only version lol.

I am currently using Nexus and I'm planning to do the same mods to the final version of the Estuary skin when a stable version of Nexus is released.

**Comment by tundrablasen** [comment]
> @tundrablasen
> 
> That version that I shared above is the latest version for Matrix. Actually it's the only version lol.
> 
> I am currently using Nexus and I'm planning to do the same mods to the final version of the Estuary skin when a stable version of Nexus is released.

Cool! I installed it today and will be my new daily driver I think. Can’t wait for your nexus release

**Comment by ivarbrandt** [comment]
@tundrablasen 

> Cool! I installed it today and will be my new daily driver I think

Awesome! I'm glad you like it.

> Can’t wait for your nexus release

Same. I don't like what the Kodi devs did to the Nexus version of Estuary.
