### ISSUE TITLE
Cached torrents only check. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#50]
I just did some testing, got bored, and compared it to Numbers By Numbers addon (that does not have a option for cached only). 

Breaking Bad, Season 1,episode 1.
It has playable (cached at Realdebrid) torrent streams (not all, some do skip, because there is no cache check) like Magnetdl, Btscene, kickass, Piratebay, Skytorrents just to name a few. 
So there are cached torrent links, but in Fen only Hosters (no torrents with cache check on). 
I get 123123movies, cartoonhd, freefmovies, freeputlockers, solarmoviefree, watchseriesto, so only few Hosters. (some scrapers are blocked, like ddlspot.com, they block the netherlands). 

Could you test this maybey, I have a feeling that the 'cached torrents only' option does also filter out links that are cached.

**Comment by Tinuz97** [comment]
Ps, all named torrent scrapers do work here fine in Fen, with newer shows, movies.
But Breaking bad is a good test (no torrent results for me).

**Comment by Tinuz97** [comment]
Also tested Seren, cached only, does find cached torrents also (torrentapi as a example), just fyi.

**Comment by Tikipeter** [comment]
I was going to write back that I received a fair few cached torrents for BB s01e01, then thought I'd try another machine first. Sure enough, no cached torrents when trying from a second setup.

Turns out a scraper was returning a somehow malformed magnet link, making the info hash extracted from that link incorrect. The real-debrid API allows you to check 100 info hashes at once, meaning that a bad info hash was in with the only batch of 100 sent to RD for BB s01e01.

Also turns out RD API will only send back an error report if ANY of the info hashes it is sent in the batch is incorrectly formed.

Since correct info hashes are 40 characters in length (from what I can see), then a simple check of info hash length before including them to be checked should fix this.

Fix will be in next update....

**Comment by Tinuz97** [comment]
I have no idea why I can't post a picture in here, sometimes I see the option, now the option is gone.
But now I have cached torrents for breaking bad, season 1, episode 1, thx 🎉🙏👍

**Comment by Tinuz97** [comment]
No idea if placebo, but since the fix I have the idea that it also is showing better cached results (more high, and working GB files), I'm happy with cached results for Breaking Bad also ❤️
