### ISSUE TITLE
[BUG] Kodi 19.4 on tvOS crashes after installing FEN

### ISSUE THREAD

**Issue by rtuRgALp** [Tikipeter/repository.tikipeter#51]
https://paste.kodi.tv/emukevenej.kodi

I am using Kodi 19.4 Matrix on my Apple TV 4K (Latest Model). 

Whenever I install Fen, Kodi crashes. I tried the trick detailed [here](https://github.com/Tikipeter/repository.tikipeter/issues/9#issue-1327676790) but it did not work. 

I have linked the error logs for further investigation. Thank you for your consideration of this bug report.

**Comment by Tikipeter** [comment]
I'd delete the settings file for Fen in the userdata folder.
It looks like for some reason Kodi is not able to read the settings file.

**Comment by rtuRgALp** [comment]
I tried that but it did not solve the issue. 

The tvOS build seems to have bugs that are not present on other platforms like macOS or Android.

cocoscrapers seems to have an error handler for this. I get a notification saying something like “error cleaning settings.xml. Using old settings file”

**Comment by rtuRgALp** [comment]
I tried that but it did not solve the issue.

The tvOS build seems to have bugs that are not present on other platforms like macOS or Android.

cocoscrapers seems to have an error handler for this. I get a notification saying something like “error cleaning settings.xml. Using old settings file”

**Comment by Tikipeter** [comment]
Cocoscrapers runs a settings clean on each start, that is why you see an error message appear for it.

Fen, unfortunately for you, MUST have access to a settings file to function. Really, all addons do. Unfortunately it will find itself in a loop if it can't access one, because it makes it's own cache of the settings for quicker access, so will continue indefinitely to attempt to do that as it continues to attempt to retrieve settings it needs.

If you've found no way for Kodi to function correctly on your TvOS, I can't see any way Fen would be able to work on it.

Do you have any idea what the issue/s are with tvOS and Kodi? This is more than a bug really if settings files can't be accessed.

**Comment by rtuRgALp** [comment]
This is certainly fascinating. I have been able to set up other add-ons in my various tvOS builds just fine. Some throw that “error cleaning settings.xml” error on first start up, but then function normally. 

If I had to guess, maybe the settings.xml file is in a directory that is locked? Apple notoriously makes it impossible to access the file architecture without jail breaking the device. 

Can I donate an Apple TV to you for your own testing? I’m happy to donate funds to get you an Apple Developer license as well so you can sideload it to the Apple TV using Xcode. This is how I’m able to install Kodi without jailbreaking the device. 

I’d really like to see Fen working on tvOS. I am happy to sponsor this development in any way that I can.

**Comment by Tikipeter** [comment]
The only thing I can think of, if other addons are able to function normally after an initial error, is that the file is not available for access immediately on start up. It must somehow be available generally, as addons definitely need read/write access to that settings.xml file. The issue is there is contradictory evidence to that as well, specifically in Fen where I write a setting to the settings.xml file as the second thing I do in the services to make sure it exists. Perhaps that is also failing, so I'll add a check to see.

>Can I donate an Apple TV to you for your own testing? I’m happy to donate funds to get you an Apple Developer license as well so you can sideload it to the Apple TV using Xcode. This is how I’m able to install Kodi without jailbreaking the device.

I appreciate the offer, but that's not necessary. I can really only change a couple of things in Fen to try and get it to function properly with the little we know, and I'm doing that right now.

If you can install addons manually I can share the zip here after I've finished, or else the next update will include the changes.

Are you able to successfully disable/uninstall Fen in the meantime so as it's not continually crashing Kodi?

**Comment by rtuRgALp** [comment]
Ok, sounds good. I have a good feeling that adding that additional logic to handle the instance of not being able to access the settings.xml on first run will fix this issue. When CoCoScrapers is installed alongside Fen, it throws the error I previously mentioned but then runs fine afterwards and I’m able to update the settings normally. I know it works because I’ve used the same CoCoScrapers module with another add-on that relies on it too (Umbrella). 

I can install add-ons manually, so I’ll happily test the latest build once you provide it. For now, yes I can disable the add-on to prevent Kodi from crashing. 

If there is any other way I can donate to support you, please let me know!

**Comment by rtuRgALp** [comment]
Ok, sounds good. I have a good feeling that adding that additional logic to handle the instance of not being able to access the settings.xml on first run will fix this issue. When CoCoScrapers is installed alongside Fen, it throws the error I previously mentioned but then runs fine afterwards and I’m able to update the settings normally. I know it works because I’ve used the same CoCoScrapers module with another add-on that relies on it too (Umbrella). Umbrella itself also throws the same error. 

I can install add-ons manually, so I’ll happily test the latest build once you provide it. For now, yes I can disable the add-on to prevent Kodi from crashing. 

If there is any other way I can donate to support you, please let me know!

**Comment by Tikipeter** [comment]
Try `3.0.18` currently in repo and see how it goes. Fingers crossed it works OK with the changes.

**Comment by rtuRgALp** [comment]
It works! No crashes. Well done, Tiki. You are a gentleman and a scholar. Really appreciate it! Now I can use my favorite add-on on my Apple TV!

**Comment by Tikipeter** [comment]
Great news. :)

Apple TV is a nice bit of kit. I suppose we still don't know for sure the reason for this issue, but it seems it's not having the file available immediately on Kodi start. As long as you can change settings successfully, it doesn't really matter I suppose.

Anyway, happy it's working.

**Comment by rtuRgALp** [comment]
It might be a race condition. Maybe? Anywho, you fixed it! Great work. 

Apple TV 4K 2nd Gen is arguably the best streaming box you can buy. Price to performance wise, I’d argue it’s better than the 2019 Nvidia Shield. You have to go through more hoops to get Kodi side loaded on it, especially without jailbreaking it; but, it’s performing better than any Amazon device I’ve ever owned. 

FYI, they’re on sale for Amazon Prime Early Access!

Thanks for your help. If you accept donations, please let me know.
