### ISSUE TITLE
Extras Dialogue (Feature Request/Enhancement)

### ISSUE THREAD

**Issue by starmanrf** [Tikipeter/repository.tikipeter#526]
Hi, first and foremost I want to thank you for such great effort, simply stunning!

I'm unsure if it's possible but thought I'd throw it into the mix to suggest a settings menu to toggle features on/off within the extras dialogue.  I've seen a similar option feature on some skins...such as Arctic Zephyr 2 and Arctic Horizon which may garner some inspiration and code. 
Would be great for users to enable/disable any aspect of information they choose ; I.E Recommended, Reviews, Trivia, Blunders, Parental Guide, Videos, Posters, Fanart, More from (year), More from (genre), More from (studio), Collection.

I see you also mentioned on the last changelog about toying with keeping scroll bars on the extras components, perhaps a toggle could be implemented in the same extras setting menu to give the users the choice. 

Thanks again for your excellent hard work!! BTW put a donate button on the github page... i'm one very happy chappy and would send some pennies your way.

**Comment by Tikipeter** [comment]
Unfortunately the features of the skinning engine available to an addon compared to a dedicated skin are very basic.
Whilst providing settings to hide/unhide certain lists is easy enough, the conditions that would need to be written so that the remaining lists lined up correctly would be a nightmare. It might not even be possible without features that are only available to skins.

It just can't really be done. At least not by myself.

**Comment by starmanrf** [comment]
Ah I see, thanks for looking into it, I appreciate it.
