### ISSUE TITLE
Next Episode Select Source Option

### ISSUE THREAD

**Issue by Baubascat** [Tikipeter/repository.tikipeter#528]
It would be great if the source select screen would show for the next episode instead of auto playing. Could you please add the ability to select the source for the next episode?

**Comment by ShibajiCh** [comment]
Hi @Baubascat,
Yes, I agree with you. Even I want this same feature to be added to Fen. This will make the already amazing Fen add-on even better. 🙂

**Comment by Tikipeter** [comment]
I have added this before and then it was removed in the great removal of features many updates ago, which means it won't be coming back.

I didn't have then, and I still don't have now, any idea why anyone would want this. I simply don't see the utility in it. If you don't want autoplay, then just click on the next episode to play and the results will show after searching.

Surely it can't be that you just don't like pressing your OK button to get the results for the next episode? Tell me that's not why you want this feature? Please someone tell me how this would even be used?

**Comment by deyooluv** [comment]
With source select in the context menu one can manually select streams. For instance when autoplay is enable in settings stream are auto selected(play) by the add-on. Sometimes the streams auto selected does not fit our preference (wrong audio streams for example). With source select one can manually select streams instead of going to the settings of the add-on and then disable autoplay.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter, actually this feature is very helpful. I earlier used it in Seren until I switched to Fen which I feel is a much better add-on. The utility of this feature is that once an episode ends we have the option to select our preferable source be it 4k, HDR or full HD instead of the addon selecting a random source on its own. Now coming to the question on why we can't select it from the Next Episodes page. The thing is that I use several widgets on my Arctic Horizon Skin and the Next Episodes is one such widget. So once an episode ends it takes few seconds to few minutes to refresh the widgets on my Nvidia Shield TV Pro's Kodi. Hence, having a source select option just after the episode ends will save me the hassle of waiting for the widgets to refresh. Especially since I use Fen widgets in combination with the TMDB Helper widgets so it makes the widgets loading painfully slow sometimes. Hope I could explain the situation. Currently, I've disabled the Fen auto play fearure and select the next episode manually from the widget as I don't like the automatic source selection procedure all the time. However, even if you don't agree with me and don't add the requested feature still I'll say that Fen is the best Kodi addon hands down. Keep up the good work @Tikipeter. Hope @Baubascat agrees with me.

**Comment by Tikipeter** [comment]
@deyooluv 
Context Menu->Options->Rescrape & Select Source.

@ShibajiCh 
Way too many widgets by the sounds of things. This is not a good reason.

**Comment by ShibajiCh** [comment]
> @deyooluv
> Context Menu->Options->Rescrape & Select Source.
> 
> @ShibajiCh
> Way too many widgets by the sounds of things. This is not a good reason.

Hi @Tikipeter, actually not too many widgets. The thing is that majority of my widgets are inside the hub. However, the ones which are openly there in Kodi are from TMDB Helper combined with Fen, and the TMDB Helper addon is quite slow to load widgets. Nevertheless, that is another great addon and I just can't let it go. Anyways, thanks for your super fast responses. You, jurialmunkey, nixgates and drinfernoo are great addon developers. I respect you all for the great work that you're doing for us. Thanks a lot! Hope sometime in future you might think about this requested feature and do the needful to add it to your amazing Fen addon. Until then keep up the good work! 🙂

**Comment by Tikipeter** [comment]
Oh well, I just had it brought to my attention that this Issue ticket has been posted on the Addons4Kodi reddit page, requesting others to spam this issue with requests for this feature.

This issue will now be closed and no consideration for adding this feature will be entered into. I won't be strong armed into adding features in Fen. Don't like the current feature set?.. Use another addon that has what you want.

This kind of internet "mob" mentality is a cancer on society in general, and will not be tolerated here.
