### ISSUE TITLE
Fen Next Episodes error after latest update (Revised)

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#543]
Hi @Tikipeter,

Few days ago I raised this issue (#537) here and resolved it myself by reinstalling Fen. However, the issue happened again yesterday. I also noticed that other users posted similar issues here (#541). So I investigated little further this time around and found the cause of the issue.

The issue is happening when we enable the option "Include In Progress First Episodes" under Next Episodes settings in Fen. I guess this might be happening because I don't have any In Progress First Episodes in my list currently. However, you will be the best judge for the cause of this issue. I'm just trying to help you resolve it. As soon as I disabled that option the error vanished immediately. Again when I enabled it the error re-occured. So I've disabled it for now and Next Episodes list is working fine. May be you can try to replicate the situation at your end and see what might be causing the issue. I'd suggest you to check by adding an In Progress First Episode to your list first and then by removing it. See if you get the error at your end as well. That might help you understand what is causing the issue.

Thanks again for the great work that you're doing!

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Good job on this Issue.
I'll check what's happening when I get home from work.

**Comment by ShibajiCh** [comment]
> Good job on this Issue.
> I'll check what's happening when I get home from work.

Hi @Tikipeter,

Fine. Thank you! 🙂 
I shall look forward to your update.

Thanks,
ShibajiCh.

**Comment by jigoop1** [comment]
@Tikipeter 
in file next_episode.py line # 102 instead of 
`threads.extend(list(make_thread_list(process_in_progress_eps, _progress_eps, Thread)))`
should be 
`threads = list(make_thread_list(process_in_progress_eps, in_progress_eps, Thread))`

and in file in_progress.py line # 79 instead of
`episode_list.append({'tmdb_id': int(_id), 'season': int(item[1]), 'episode': int(item[2]), 'curr_time': float(item[3]), 'resume_point': item[4]})`
should be
`episode_list.append((int(_id), int(item[1]), int(item[2]), float(item[3])))`
that should work i have tested the mode file here i have attached the same for time saving.
[addons.zip](https://github.com/Tikipeter/repository.tikipeter/files/6984421/addons.zip)

**Comment by Tikipeter** [comment]
Thanks @jigoop1 

Problem was I made some changes to get ready for using trakt resume points and forgot that I wasn't quite ready to implement them yet.

I need to go the other way and change the `next_episode` code to work with the new `in_progress` code, instead of the other way around. But you did a great job there. You're python must really be coming along! You'll have an addon out soon enough I suppose!

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter and @jigoop1,

Fine. Thanks a lot to you both!
Looking forward to the next update of Fen. 🙂

Thanks and Regards,
ShibajiCh.

**Comment by jigoop1** [comment]
> Thanks @jigoop1
> 
> Problem was I made some changes to get ready for using trakt resume points and forgot that I wasn't quite ready to implement them yet.
> 
> I need to go the other way and change the next_episode code to work with the new in_progress code, instead of the other way around. But you did a great job there. You're python must really be coming along! You'll have an addon out soon enough I suppose!

i still learning the inner working of addon, i don't get the web scraping for  links and resolving to play in kodi. no i do not have addon, btw your addon is the great one with all bell and whistle i need. 
yeah i guess my python coming along little by little.
thanks.
