### ISSUE TITLE
Inaccessible repository

### ISSUE THREAD

**Issue by baltzis** [Tikipeter/repository.tikipeter#545]
I'd like very much to keep using this addon, but for some reason, the address "https://tikipeter.github.io/" produces an error in Kodi (it says "unable to connect"). The repository cannot be installed. I tried the address through a web browser and I get a "404" error ("There isn't a GitHub Pages site here."). Unfortunately, I don't know how to resolve this.

**Comment by Tikipeter** [comment]
Download the repository zip from here-
https://github.com/Tikipeter/repository.tikipeter/tree/master/zip/repository.tikipeter
and install the Tikipeter repository using that.

The github.io source to install from has been removed.

**Comment by baltzis** [comment]
Many thanks! So, I guess that I can't install it from within Kodi using "Add source" from "File manager"...

**Comment by Tikipeter** [comment]
Correct. Old fashioned way only from now on.

**Comment by baltzis** [comment]
Thanks again for your response. So, how do we get notified about updates?

**Comment by Tikipeter** [comment]
Nothing changes with regard to update notifications. You are still installing the repo the same way (via zip file). The only difference now is the zip file is installed locally, rather than from a browsed website address.

No difference to anything else. Repo will update when needed, Fen and dependencies will update when needed.
