### ISSUE TITLE
Issue / request 

### ISSUE THREAD

**Issue by Russty123** [Tikipeter/repository.tikipeter#552]
Im finding that im needing to reset cache alot to bring up new episodes.  I was wondering if we can get an option to clear cache on start up.  I tend to use the “clear all cache “ option.  Hope this is where i was suppose to post this.  Btw this is by far the best addon ive used keep up the good work buddy!

**Comment by Tikipeter** [comment]
Please name the show where this issue is happening.

You should not EVER clear the cache manually if it can be helped. All of these addons put a huge strain on the metadata providers, and clearing all the caches is terrible for the metadata providers.

Fen will cache the metadata for a tv show for 4 days if it is still in production, and for half a year if it is no longer airing new episodes. So the show info in question SHOULD be cached for 4 days. Perhaps the show has incorrect data on it's airing status, or perhaps those 4 days of caching are coinciding with the time the next episode becomes available in the metadata info.

The very most you should ever do with regards to clearing caches, is clear the cache for that particular show if it is not showing new episodes in a timely fashion. You do this by navigating to the show in question, bringing up the context menu, and selecting Options->Re-cache TV Shows Info. That will draw new info for that particular show.

Adding an option to clear cache on startup is very irresponsible on my part and is not something that I would be willing to do. Plus it will make Fen a LOT slower if you do that all the time.

**Comment by Russty123** [comment]
Thank you i will try that.   My latest example was the latest naked and afraid episode.  episode 4 came out i checked it in kodi and wasnt there.it only listed 1-3 no other episodes.    I then cleared it , the method  i said previously and it then appeared.

**Comment by Tikipeter** [comment]
Closing/not closing Kodi will make no difference to this.

The main issue nowadays is any addon going forward needs to use TMDb for metadata for TV Shows. Whilst it has definitely improved in the last 6 months, there are still often times when the episode list for a show will only include episodes that have aired, and it is only updated at the last minute to include a newly aired episode. The provider widely used in the past, TVDb, often had the next 4 or 5 unaired episodes already in the data, so when a new episode aired we were not dependent on an updated set of data from them. TMDb is Ok for the most popular of shows, but lags behind with many even slightly more obscure shows.

I have this issue with The Challenge, which I like to watch each week. The new episode is only added a day or two before it airs, so I need to refresh the metadata for it sometimes to get that new episode. There's nothing I can do about that except for only caching the data for a day, but as I said that puts undue pressure on the metadata providers so I can't do that.

You have to remember every piece of using Kodi in this way - Kodi itself, the addon you are using, the metadata that addon uses to display movies/tv shows ALL come from people doing it for free, in their own time. None of this process has a commercial aspect, meaning we have to take what we can get and be happy with it. There is some person out there, week in and week out, adding a new episode to TMDb for Naked and Afraid. They are doing it for free with no credit.

**Comment by Russty123** [comment]
Thx for yr help.  Keep up the good work.
