### ISSUE TITLE
Attribute Error on Play

### ISSUE THREAD

**Issue by DaisyF8** [Tikipeter/repository.tikipeter#571]
I can't say for sure when this started (recent update or not) since I watch a lot of local files.

https://paste.kodi.tv/okozajowem

**Comment by Tikipeter** [comment]
You are MANY versions behind for `script.tikiskins`. You are at version `1.1.13` and the latest version is `1.1.28`. I'm suprised anything is working.

Uninstall Fen (but keep settings), uninstall script.tikiskins and then re-install Fen from the repository. That should install the latest version of both and fix your issue.

**Comment by DaisyF8** [comment]
Yes that solved it thx. 

Does Tikiskins normally show up under Available Updates (since it lives under System/Add-ons/Manage Dependencies) ? I've had this type of 'desync' once before with Fen. Strange that Tikiskins sometimes gets left behind.

**Comment by Tikipeter** [comment]
It won't show up under Available updates, or as a dependency when installing. But it should update whenever it is needed from the repo. There are various accounts of tikiskins not updating when needed, but I don't know why it is happening. Just because it's happened to you this time does not mean it will continue to happen though. As long as you only install Fen from the repo, there will be no issues.

**Comment by DaisyF8** [comment]
Okay. Thanks again.

**Comment by DaisyF8** [comment]
Just as additional info : Tiki Skins Module showing up in Available Updates

![20210909_093835](https://user-images.githubusercontent.com/10348988/132644464-0d4e0465-068d-4086-9a7d-09bb73cf1eb8.jpg)
