### ISSUE TITLE
Artefact progress window

### ISSUE THREAD

**Issue by DaisyF8** [Tikipeter/repository.tikipeter#575]
Main progress bar starts half-way and has a grey full bar progressing a bit back.

...and (let me also get on the -you can't please everyone train- :) ) have you thaught about mainaining aspect-ratio for the background art of the progress window ? With centering in the section to the right and adding black bars ? The effect now is already wow so no complaints.

https://user-images.githubusercontent.com/10348988/132289277-1b796f80-542a-436d-af27-f0447b9b2030.mp4

**Comment by Tikipeter** [comment]
I am aware of the issue with the progress bar. It only seems to be happening on Arctic based skins (or Jurial based skins).
I need to find a solution because I'm quite liking the new Cosmic skin that's being worked on at the moment, and it has this issue as well due to using a loot of textures from Jurial.

I'll check out the fanart as well.

**Comment by DaisyF8** [comment]
😮 Co... Co... Cosmic skin ? 😁 I need to go browse the Kodi Forums fast and try it out.

**Comment by Tikipeter** [comment]
Not Jurial's, but the textures are from his skins. Not a bad skin really. Base used was Estuary.

This will be fixed/changed for next update.
