### ISSUE TITLE
Issue with stream results, finding shows from other release years

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#578]
I have been hhaving some issues with two shows

1. Titans 2018 - I get results for that as well as Teen Titans 2003
2. What If...? 2021 - I get results for What / If 2019

In the External Scrapers I have also enabled `Check Year Before Search` but I'm not sure what that should do.

**Comment by Tikipeter** [comment]
In general, the year is not used in tv show searches. So don't think the year of the show will have any impact on filtering incorrect results.

With that in mind, I want you to take a good look at the 2 examples you are having "some issues" with. Try and think of a way that they could be correctly filtered using code.

The results screen has the full filename of every result. There will be occasions like this where the last filter needs to be your own 2 eyes.

**Comment by 123Venom** [comment]
The source results and title matching is more from the scrapers doing their job and passing the matching links back to the addon.  This is more a question for FenomScrapers so hopefully @Tikipeter doesn't object to me chiming in on the matter.
With the default scrapers enabled I did 2 out of 96 cached torrents that were **Teen Titans**.  I had to scroll down to item 26 before I hit one.  How many scrapers do you have enabled?  I'm looking into it and our title matching is rather aggressive so this surprises me some.  Your 2nd item my initial hunch is this title will be difficult to deal with.  Once the non alpha characters are parsed off those titles are going to match in the query...might not be able to do anything with that one but I'll think further on it.

<img width="910" alt="fen_teen titans" src="https://user-images.githubusercontent.com/46383815/132762857-a13ddf90-b09c-41b3-bfab-cc71405f940e.PNG">

**Comment by 123Venom** [comment]
Here's the problem.  Both TMDb and Trakt are returning INCORRECT aliases from the wrong show. You can test the api's and see for yourself their meta is wrong.  imdb_id=tt1043813, tmdb_id=75450.  I've logged the responses and it's rubbish.  Nothing we can do about this problem.  The meta providers need to fix it.  Trakt indexed the bad data from TMDb and that's why they are also messed up.  I would post an issue to both providers and they're pretty good about fixing it. 

<img width="1328" alt="aliases" src="https://user-images.githubusercontent.com/46383815/132766747-08a2e0ac-9e06-423c-9be9-879df8b63458.PNG">

**Comment by 123Venom** [comment]
I went ahead and reported it to trakt.

<img width="649" alt="trakt_aliases" src="https://user-images.githubusercontent.com/46383815/132769003-762979d3-ee3f-406a-a88c-cd2c1a5f6896.PNG">

**Comment by 123Venom** [comment]
>     2\. What If...? 2021 - I get results for What / If 2019

You really need to understand how a query works.  We can not query `?` and `/` characters so the query becomes ex. `What+if+S01E01`  Then the torrents also can not use those special characters in their file names so both titles become a magnet like `What.if.S01E01.1080p.WEB.X264-METCON[rarbg]` and how do you know what show you are getting?  Some uploaders are smart enough to use the year in the title for reboots or duplicate shows, but most do not do this!  We could add the year to the query but in doing so non reboots would take a massive hit and return no sources and more complaints.  That title is a real shit show!!

**Comment by KalAvroniev** [comment]
Thanks for all the info, it all makes sense now.
For shows we mostly rely on title, season and episode and it is doing wildcard match since it cold be sligtly different format hence the Teen Titans, and possibly the meta issue.

Does that mean `Check Year Before Search` is only used for movies?

**Comment by KalAvroniev** [comment]
> The source results and title matching is more from the scrapers doing their job and passing the matching links back to the addon. This is more a question for FenomScrapers so hopefully @Tikipeter doesn't object to me chiming in on the matter.
> With the default scrapers enabled I did 2 out of 96 cached torrents that were **Teen Titans**. I had to scroll down to item 26 before I hit one. How many scrapers do you have enabled? I'm looking into it and our title matching is rather aggressive so this surprises me some. Your 2nd item my initial hunch is this title will be difficult to deal with. Once the non alpha characters are parsed off those titles are going to match in the query...might not be able to do anything with that one but I'll think further on it.
> 
> <img alt="fen_teen titans" width="910" src="https://user-images.githubusercontent.com/46383815/132762857-a13ddf90-b09c-41b3-bfab-cc71405f940e.PNG">

In FenomScrapers I have all providers enabled, as well as Easy News. 
The results I have ordered by Quality, Provider, Size.
In the settings for `Provider Accounts` I also have priority 10 for Easy News and priority 5 for Real Debrid.

I'd get Teen Titans as the first result, comming from Easy News. 
Maybe the issue is in combination of the above, even though I would have thought that the Easy News results should be at the bottom.

P.S. Changing the provider priorities did nothind to the order.

**Comment by 123Venom** [comment]
> Does that mean `Check Year Before Search` is only used for movies?

Yes..that's for Movies because that we do scrape title and year as a query string and if that year is wrong..nada results.  I've seen so many titles that IMDb and TMDb do not seem to agree on the year release...but..since scene releases favor to use IMDb's year it's best that addons check it before scraping and flip the year to use what IMDb reports.

**Comment by 123Venom** [comment]
How about simply..."Do not pick the Team Titan links"? lol  Not allot we can do when the meta is fried and as time goes on I'm doing less and less workaround cases due to messed up shit.  I'd have to keep some form of db of incorrect aliases to ignore the meta, which would fix this problem but it's way more hassle than it's worth.

I got a response from TYrakt on the matter.  Here's the sort of stuff we have to deal with, which is making me also not want to even bother reporting this stuff.

<img width="561" alt="reply" src="https://user-images.githubusercontent.com/46383815/132820603-89b6a330-467e-4473-aa6a-f3c31d5ee9c6.PNG">

I removed names but read that.  WRONG!!  Teen Titans is a cartoon show from 2003 and both IMDb and TMDb have different ids and links to each show.  How can you tell me it's the same show?  If I can't convince them they're wrong it ain't getting fixed.  Maybe I was not thorough enough in my explanation...that 2nd reply is cut and dry proof they are not the same and aliases should not be referencing that cartoon.

**Comment by KalAvroniev** [comment]
Looks like pain in the behind. Thanks for spending some time to explain this to me.
I still think there might be some issue with the sorting. I'm having same with latest episode of See. Even though I have given Easy News priority of 10 and RealDebrid priority of 5 It is showing easy news above the real debrid sources.

Could this be because Easy News results come as Hoster: Direct and RealDebrid as Hoster: Cached?
File sizes and quality are same, even the name is the same, only difference is the hoster and the site.
Is there a way to swith the order or not so easy?

**Comment by Tikipeter** [comment]
It looks like the sorting issues are due to inconsistencies with the sizing being reported. For example, the Easynews 2.40GB result above is likely something like 2.387948GB, whereas the real debrid result might be the 2.40GB. So the sort will put that Easynews result before the RD, even though they are really the same size. I'll round all sizes to 2 decimal places for next update and that will likely fix the issue.

**Comment by KalAvroniev** [comment]
I'll do some tests and update once the update is out.

**Comment by KalAvroniev** [comment]
I did some tests after the update and now Easy News ressults are pushed to the bottom for each quality group.
Thanks for the quick fix.
