### ISSUE TITLE
Suggestion for Results when Auto Play in Playback is off or when Options -> Rescrape & Select Source

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#579]
Is it possible to keep the source list open until we navigate back from it.

Example I want to pick the source that I want to play but the first pick was incorrect.
In this case I have to go again and Rescrape to get the sources and then to choose a new one.

If the list is kept on then I do not have to go through the scrape process every time I pick the wrong stream source

**Comment by Tikipeter** [comment]
No, not possible.

**Comment by KalAvroniev** [comment]
Scrapping takes between few seconds to `Scraper Timeout` which I have at 90 seconds.
When you go from Options -> Rescrape doesn't that ignore the cache and starts all providers as if there were no results?

Also, I thought from usability point of view with the current setup you have:

- With `Auto Play` on 
    1. Select what you want t watch
    2. Show the custom menu 
    3. Select Options
    4. Select Rescrape
    5. Wait for the list of sources (rescrape could be slower)
    6. Choose a source
    7. Play
    8. Stop, if source was wrong
    9. Repeat from step 2 (that's 7 actions)
- With `Auto Play` off
    1. Select what you want to watch
    2. Wait for the list of sources (initial scrape would take a bit longer)
    3. Choose a source 
    4. Play
    5. Stop, if source was wrong
    5. Repeat from step 2 (that's 4 actions)

Whit what I was asking then the process would be same steps as above but then if the source was wrong you will be taken back to the list which means choose a new source and play (only 2 actions)

But if it is not possible than all good, it was just a suggesstion. I kind of remember the Kodi dialog, I think, was able to stay behind so when the video finished or was stopped user was taken back to the source list.

Thanks for all your great work and sorry for asking more of you.

**Comment by Tikipeter** [comment]
>I kind of remember the Kodi dialog, I think, was able to stay behind so when the video finished or was stopped user was taken back to the source list.

Not exactly, and that's the issue. If you don't have a custom results window (which Fen does), then the previous WINDOW is as it was before playback begins. But we are not using a Kodi WINDOW, we are using a Kodi DIALOG to display results. Dialogs must be closed before playback starts, otherwise the video WINDOW for playback will open behind the results DIALOG. That's just the way it is I'm afraid.

**Comment by KalAvroniev** [comment]
I see

**Comment by 123Venom** [comment]
@KalAvroniev you'll notice the same behavior with any addon using a custom window xml to display the source select...Seren, Venom, Shadow.  They all do this and there's no choice.  Personally it doesn't bother me one bit because a custom window xml is far easier on my eyes than the old cramped Kodi directory list.  It's one quick button press and well worth the difference.
