### ISSUE TITLE
No result when using tvOS

### ISSUE THREAD

**Issue by dnkidd** [Tikipeter/repository.tikipeter#583]
Fen and Venom are both returning no results when the addon is loaded on Kodi 19.1 using Apple tvOS.  Verified RD is loaded correctly and returning results.  It appears the resolverURL is not returning back account syncs on tvOS platform.  Not able to debug between plugin and resolverURL

**Comment by Tikipeter** [comment]
Fen doesn't use "resolverURL". I'm assuming you mean ResolveURL, and Fen doesn't use that either.
To get meaningful support you need to post a log, but likely your issue is to do with an out of date tikiskins dependency. If so, uninstall Fen (keep settings), uninstall script.tikiskins and then reinstall Fen from the Tikipeter repository.
