### ISSUE TITLE
Tikiskins and tikiart missing from repo in Kodi and fresh installs fail.

### ISSUE THREAD

**Issue by cgcgcgcgcg** [Tikipeter/repository.tikipeter#600]
Installed those manually from here, and then Fen installs fine.

![k_20210918-152014](https://user-images.githubusercontent.com/38960370/133888990-b4691c56-4777-4a16-a2e3-f7b87563f76e.png)

**Comment by Tikipeter** [comment]
That's not going to work in the long run. Kodi (v19 onwards) needs to link them to the repository they belong to, otherwise they won't update in the future.

The fact you installed them from here means they are certainly not missing from the repo. That's where you got them from.

I would uninstall Fen, then uninstall tikiskins and tikiart, then reinstall Fen from the repo. That should link them all to the repo correctly and ensure they are all updated when needed in the future.

**Comment by cgcgcgcgcg** [comment]
Thank you, it was resolved.
