### ISSUE TITLE
NZBS

### ISSUE THREAD

**Issue by jjred1977** [Tikipeter/repository.tikipeter#61]
Hey Tikipeter,

Doc, me, and a few others have been talking about trying find a way to play NZBs through kodi on the A4K discord.  We have a guy who is trying to build an addon to do it but its coming along slowly.  I wondered since Fen works with Easynews if you had any ideas that could help?  Several of us have NZB indexer subscriptions or will have subscriptions after black friday and we wanted to use NZBs as a replacement for the larger free hosters that are going down on a more regular basis.  Also FYI, I go by JamesJB on discord.

**Comment by Tikipeter** [comment]
I'm afraid Fen only gets Easynews results from their web service, so there are no scraping of nzb sites, and I know nothing about them. :( :(

If the .nzb's would be used for playback through Premiumize, I would have a look through Gaia's code. I'd love to help with this when I have the time. It would be fairly easy to just set up a few nzb site scrapers and use Premiumize's API for playback (either get ResolveURL to add support, or do it in house).

If you mean to start playing the incomplete nzb donwload immediately, then I can't really help at all. I did find this link: https://forum.kodi.tv/showthread.php?tid=97657 to an old add-on called Pneumatic, which used to be able to do this. So that would be worth a look for sure. I doubt the add-on still works in Kodi now, but there might be a lot of useful stuff in there.

I might have a look at this Discord, and see whether I've signed up for it already, and have a chat.. :)

**Comment by jjred1977** [comment]
Sorry to just not get back with you Tikipeter.  Any help would be appreciated even just spitballing ideas.  Your addon gets a lot of praise on our discord.  I'll provide you think invite link.  https://discord.gg/DnJNZ6  

"If the .nzb's would be used for playback through Premiumize, I would have a look through Gaia's code. I'd love to help with this when I have the time. It would be fairly easy to just set up a few nzb site scrapers and use Premiumize's API for playback (either get ResolveURL to add support, or do it in house)."

There is a person that goes by ruiner_nin and he is the predominant developer so far who is trying to tackle this.  The last time I heard he was thinking along the same lines as you stated above.  I contacted JSergio and he said that he does not want to involve ResolveUrl in it, "resolveurl is designed to resolve or validate one link only when passed to it. I plan to keep it that way. Any batch processing for building/filtering lists of sources from another add-on should be handled by that add-on itself. I must stay neutral and can not involve myself in any piracy." 

Anyway, come join the discord so you can get all the fanboy praise you deserve, lol.
