### ISSUE TITLE
Still Struggling with FEN Extras

### ISSUE THREAD

**Issue by textroynado** [Tikipeter/repository.tikipeter#618]
I've started over completely with a fresh install of the current Kodi release v19.3.  Installed current version of FEN and configured the accounts in My Accounts as well as FenomScrapers. Still can't get "reviews, trivia, blunders,or parental guidance" to show anything under Fen Extras. The only one I really care about is the PG. I did check FEN settings>general>FEN Extras List and everything is enabled. Still no luck. Any thoughts or advice? Most recent log included
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7430988/kodi.log)
.

**Comment by textroynado** [comment]
So based on your info, I took one of my boxes and did a fresh install of Ubuntu 20.04 instead of the latest stable version I was running of 21.10. Reinstalled FEN etc and everything works fine. So it has something to do with the OS version I was running. Given that, I'm sticking with the LTS version of 20.04 and everything seems to be working fine now. Thanks for your help and for all the work you do keeping FEN current and the best Kodi add-on available!

**Comment by Tikipeter** [comment]
Good to hear you got it sorted, but it's worrying that there is a problem with the latest Ubuntu version like you say.

**Comment by Tikipeter** [comment]
@textroynado 

I'm seeing reports of python version 3.10 causing certain issues. Perhaps Ubuntu 21.10 ships with python 3.10?
If so you may be able to run it if you prefer, but also install python 3.7-3.9. One of those. And then set the python path to Kodi from one of those python installs. Many years since I've run Linux though, so I can't remember how....
