### ISSUE TITLE
Appreciation and some suggestions

### ISSUE THREAD

**Issue by host505** [Tikipeter/repository.tikipeter#62]
First let me express my appreciation for you takings things forward with this add-on.

Now some suggestions, first one in regards to cached torrs: current logic is you either get a list of cached only (marked as cached) or a list with all, cached/uncached with no cached marks.
I'd like to have a list of all, but with the cached ones marked. Reason is, I want to have uncached on, for these obscurities/oldies that chances are slim for them to be cached, so I can do it on my own on the fly, if no other option is available.

Secondly, I really liked your new 'Clean Settings' function, I was looking for a way to reduce log spamming with obsolete settings entries, I hope you don't mind that I took the liberty and adjusted it to my add-on (thank God func was pretty much stand-alone, unlike most of your other code :)).
But I adjusted it to also be able to run for different add-ons. Wanted to make it work for my scraper module as well, and that is my suggestion - to be able to clean your other supplementary add-ons too (well basically the scraper pack, because scrapers come and go and settings are left behind).
Fwiw here's what I came up with to make it like this:
https://github.com/host505/plugin.video.theoath/blob/master/resources/lib/modules/control.py#L348-#L389

Thanks again!

**Comment by Tikipeter** [comment]
I like both of those ideas. I REALLY like the torrent suggestion.

I do have a clear settings function in tikiscrapers' settings dialog, but it simply deletes the settings so a fresh one can be made. I really only needed this because tikiscrapers doesn't even have an addon settings.xml file, all the settings are set on the fly. This way I don't need to keep up with the scrapers that are in the addon and add them to settings; they will simply show up to enable when they are put into one of the source folders. To be honest, if Openscrapers would do it this way, I would switch over to using their module and get rid of Tikiscrapers altogether. I like using the multiselect dialog to choose the scrapers. :)

The torrents I'm going to do exactly the way you suggested, with a setting to show uncached torrents or not. My problem is that the external scrapers are still using much of the code from the sources.py file of Exodus forks, as I'm sure you would have seen if you're checking out the code. I did this because I added the external scrapers after I had a functioning add-on with Furk and Easynews, so I was just adding it into the mix. I'd really like to try and re-write it to suit Fen's needs more, at the moment I'm really just adding stuff in as I need it, but the core is still Exodus based for External Scrapers. It was a pain adding the torrent cache checks.

Even though I'm still a novice at Python, I do have my own writing style/logic style now, and it's a fair bit different to lambda's. Whilst he was a MUCH better coder than I likely ever will be, I just don't feel at home doing things the way he did things. It's not natural to me. Do you know what I mean??

Anyway, I'll extend the 'Clear Settings' to cover the 2 tiki modules, and will get to work on the torrents change when I get a break from working (4 days away).

I appreciate the suggestions host505. :) :)

**Comment by host505** [comment]
Oh, didn't realize that individual scrapers don't have settings entries on your tikiscrapers module - haven't really dug to this multi-select dialog settings func. So I guess you won't need to clean settings for it, I mean log isn't spammed by non-existent settings entries.
I don't know how obsolete addon_data settings.xml affect performance though.
And your other modules didn't have much changes regarding settings iirc, so, I guess you don't need to expand the cleaning function.

As for cached torrs, I guess the 'exodus' way of doing it would be a source_utils function that checks your cached/uncached result, which then would be checked on each scraper and modify the 'host' element accordingly, but I don't want to confuse you, you sure have your way of doing it :)

**Comment by Tikipeter** [comment]
I was able to speed up Fen quite a bit by trying to remove all calls to settings when iterating through lists. I realized then that that is quite a slow process for Kodi to do; parse the settings.xml file over and over. Whilst it would make miniscule differences on most setups, I thought a smaller (even slightly) settings.xml file will be quicker for Kodi to parse for the setting I'm asking for.

Plus, I hated having obselete settings in the settings.xml file. It really annoyed me. :)

The changes you suggested will be in the next release (v.1.5.73).

**Comment by host505** [comment]
That's great thanks!
Noticed 2 issues though, not sure if they existed prior to this release:
- Some are mark as 'rd unchecked', why's that? Is it funky magnet form and can't get the infohash correctly?
- Uncached ones seem to skip, resolveurl's caching process never seems to get initiated (yes I have 'cached only' turned off on resolveurl)

**Comment by Tikipeter** [comment]
Issue 1 will be fixed next update. Thanks for that.

Issue 2 I did purposely, so there weren't uncached torrents in the list of results ready to be resolved. I figured no one wanted uncached torrents there. It was meant to work so if you purposely clicked on an uncached torrent from the results, it would send it to resolveURL for caching, but all other uncached torrents were removed from the resolve list.

I will reverse this change also on next update. :)

**Comment by Converted007** [comment]
> Issue 1 will be fixed next update. Thanks for that.
> 
> Issue 2 I did purposely, so there weren't uncached torrents in the list of results ready to be resolved. I figured no one wanted uncached torrents there. It was meant to work so if you purposely clicked on an uncached torrent from the results, it would send it to resolveURL for caching, but all other uncached torrents were removed from the resolve list.
> 
> I will reverse this change also on next update. :)

I still have issue 1: (Some are mark as 'rd unchecked', why's that? Is it funky magnet form and can't get the infohash correctly?)

Can you solve this issue?
Thanks:)
