### ISSUE TITLE
Getting 0 results from internal scrapers on any show, also Failure to Resolve Specific Cached RD Torrent

### ISSUE THREAD

**Issue by TrillaG** [Tikipeter/repository.tikipeter#627]
I'm getting 0 results from internal scrapers, even though I know my RD is authorized and its set to scrape my cloud. All the settings are correct and I have cached files in my RD cloud for that show (DragonBall Z) that it is unable to resolve. I have cleaned the cache of all scrapers. Something is obviously not working correctly if I get 0 from int. scrapers, right? The external scrapers work fine, and can play every show in my collection except DBZ. It is bugging the absolute shit out of me (pun intended). I have also tried to link the cached torrent file in my cloud to the DBZ show but it still wouldn't play. Also unrelated note, the next/previous episodes buttons are not functional, it does nothing if you click on them. And the autoplay feature seems to not be working now since the latest update. Kodi 19.3, Fen 2.5.03. 

log file: https://paste.kodi.tv/yotirehuve.kodi

**Comment by Tikipeter** [comment]
Alright, this is tough to debug because there are some ambiguities in what you have written, and this is really 4 potential issues.
Please answer the following to clear my confusion.....
* Your title for this issue says `Getting 0 results from internal scrapers on any show`, but then in your description you have written `and I have cached files in my RD cloud for that show (DragonBall Z) that it is unable to resolve` implying the issue is with one particular show. Please let me know if this is ONE show you have issues with as written in your description, or MULTIPLE shows you have issues with, as written in your Issue title. This is not semantics, it is important for me to know which of the two is true for debugging.
* Can you access and play the DBZ files from My Services->Real-debrid->Cloud Storage?
* `The external scrapers work fine, and can play every show in my collection except DBZ` Are you saying you also cannot get ANY link from the external scraper results to play ANY result for DBZ? Absolutely nothing plays if it is a DBZ result?
* `I have also tried to link the cached torrent file in my cloud to the DBZ show but it still wouldn't play` OK, but did it now display as a result from the Cloud Scraper?
* `It is bugging the absolute shit out of me (pun intended)` I don't get the pun, but I also haven't watched this anime...
* `the next/previous episodes buttons are not functional, it does nothing if you click on them` I don't know what this means. What are the "next/previous episodes buttons"? Do you mean the buttons for next/previous in the Kodi player? If so, they won't work because there is no playlist playing, just a single episode or movie.
* `And the autoplay feature seems to not be working now since the latest update` Works for me. Mind you, the latest Fen is 2.5.04, so I'm using that. I need WAY more (relevant) info to know what's going on with this. But try 2.5.04 first.

Additionally, I need from you the following information:
* The filename structure of the DBZ files. How are they named? Give me an example i.e. `dragonball.z.s01e01.720p.hevc.mp4`
* The status of the 3 subsettings for your RD Cloud scraper - `Filter Results by Name`, `Check Before Full Search`, `Show Results at Top`.

Mind you, if the DBZ files have some funky season/episode naming convention, then there may be nothing that can be done. That is one big reason as to why Anime specific addons exist in the first place.

**Comment by TrillaG** [comment]
I am getting 0 results from internal scrapers on ANY show, however, the
only show that won't play at all is DBZ, the rest of my collection the
external scrapers can find them, but I cannot get DBZ to play at all. Yes,
I can go to the cloud storage RD and play it from there, but it won't play
from my collection. Correct, absolutely no link from external scrapers will
play any result for DBZ. The pun is that it is bugging me, and it is a bug.
Yes, I am referring to the next/previous in the Kodi player. In Seren it
will autoplay the next episode in the season if I click next, does Fen not
work that way? I will try updating and see if that helps. Filename
structure is: Dragonball Z S01 E001 The New Threat (1080p bluray quad
audio) mkv. I have all 3 of those subsettings turned on. Hope that helps.

**Comment by Tikipeter** [comment]
>Dragonball Z S01 E001

This is why it will never play. That is garbage season/episode naming from whoever released these files. Fen does not search for `S## E###` when parsing the filename for a relevant result. This includes results from cloud or external scrapers. Fen must still detect the season/episode number for playback, so it will fail to play everywhere except for playback from your cloud directly.

It's the reason the cloud scraper won't display it as a result and it's the reason you can't play it back when external sources are found. Fen looks for many different combinations of S/E when parsing the filename, but this idiotic naming is unfortunately not one of them. Why Anime releases have screwed up naming is beyond me, but it seems there is no other reason than to make it hard on people who want to watch it.

The only other option (if the External Result is a pack file) would be to right click on the result, select "Browse Pack" and then select the episode you wish to play from there. But then you won't get the watched status updated, so how much use it would be I can't say.

>In Seren it will autoplay the next episode in the season if I click next, does Fen not work that way?

No. Fen does not work that way.

**Comment by TrillaG** [comment]
Okay, that makes sense. Thanks for letting me know. I think I can do a workaround where I download it to my backup HDD and then set the download location as one of folders 1-5 for it to scrape. For now I have just removed DBZ from my collection.

**Comment by TrillaG** [comment]
Now I am having the same problem with Matlock not being able to resolve the cached torrent from my collection. It worked fine before today. It has the correct format S00 E00. It finds 1 cached torrent on scraping, which works if I go into it and 'browse pack', but will not work if I click on the source or if it tries to automatically resolve it. Also since the update (2.5.04) I seem to get less files found when scraping, about half in multiple cases.

**Comment by Tikipeter** [comment]
Give me the name of the Matlock torrent that isn't resolving.

**Comment by TrillaG** [comment]
Matlock All Episodes Seasons 1-9. I cached it to RD myself.

Link to torrent:
https://thepiratebay10.org/torrent/33581632/Matlock_All_Episodes_seasons_1-9

**Comment by TrillaG** [comment]
Nevermind, just tried it again today and it is working now. Sorry for bothering you, thanks for everything!

**Comment by Tikipeter** [comment]
RD is having a few issues with their API intermittently over the last day or two I think. I've been having them timeout occasionally.
