### ISSUE TITLE
No results for Asian shows

### ISSUE THREAD

**Issue by Sourcedine** [Tikipeter/repository.tikipeter#637]
I use Fen with the language of the metadata in french.
I noticed that I don't have any results for Asian shows, I have the same observation for all other languages except English.

I get results using 'Scrape with Custom Values'.
Maybe you are using the original title for the search?
Would it be possible to use the english title by default for this kind of shows?

Thank's :)

**Comment by omaramiromo** [comment]
It's because there is no torrent available for Asian shows or cached at debrid service.. i am Asian 😀

**Comment by Sourcedine** [comment]
As a matter of fact, I get results using 'Scrape with Custom Values' or using Fen with English metadata.

I’m talking about animes or tv shows like 🐙game :)

**Comment by Tikipeter** [comment]
I've grappled with this issue a few times now. Unfortunately, there seems to be no way to get the English title of media from TMDb when another language is set. They offer the original title and the "translated" title only. That is one of the reasons I added the `Scrape with Custom Values` feature in the first place.

I'll look into this more/again, but last time I did I couldn't find a solution.

**Comment by Sourcedine** [comment]
I know this is not the best method but maybe in this particular case you can make an additional request to Trakt? If I'm not mistaken the title is always in English?

**Comment by Tikipeter** [comment]
I can't rely on Trakt for something like that (won't really), their API is too fragile. I can make another call to TMDb with English set as the language, and that will give me the English title. I don't want to do that, because it would double the calls to TMDb for each movie/show.

I think a solution is to only ask for the English title when you go to scrape a movie/episode. Because 90% won't get selected for playback, that means I only need to make that extra call to TMDb when necessary. I already do this to get English language trailers when you select trailers in the Extras menu and your language isn't English, because again TMDb don't supply trailers not in the chosen language.

I can do the same thing for playback, and cache the result so it's only needed to be fetched once (not each episode etc).

I think that could solve the problem without doubling the calls to TMDb.

**Comment by Sourcedine** [comment]
I think this is a great idea!
And this additional request will only be made if the movie / show is Korean or Japanese, it should be quite limited.

**Comment by host505** [comment]
@Tikipeter, if that helps, the way I dealt with it is to append `,translations` to the api url when user lang isn't en (assuming you already use `&append_to_response=` on the url), and grab the en title from `response['translations']['translations']`.
But probably grabbing it on demand per scrape as you pointed out is better.

**Comment by Tikipeter** [comment]
Great help @host505 . My brain's not with it lately, so I never even thought about using `translations`.
I've added it to the main meta call, and have a fallback for items in the meta cache that don't currently have that info cached.

@Sourcedine  this means all new info cached for movies/tvshows will have the info for english title included, and if that's not the case, I'll run a fetch for that info when you go to scrape a movie/episode.

**Comment by Sourcedine** [comment]
Great! Thanks to both of you, this will make the addon even more complete for all other users who don't use English.
