### ISSUE TITLE
Not marking as watched in Trakt

### ISSUE THREAD

**Issue by sabre6** [Tikipeter/repository.tikipeter#647]
I have logged into Trakt, revoked and logged back in a few times.  But Fen does not mark a show as watched in Trakt (I do it manually on the website).  I read prior some folks do see this, and suggesting to revoke and log back in.  Is there anything else I should check/try.  Sorry for the hassle. Thank you! 

**I will need to play around w/ the Trakt add-on, and mark as exclude HTTPS, which will prob fix it.

**Comment by Tikipeter** [comment]
Having the Trakt addon installed and functioning when you are using Kodi addons to watch your media will often cause issues. You need to do what you say at the end of your post for sure, but also think about WHY you have the trakt addon installed. 

Most addons (Fen included) have their own trakt integration, and do not rely on the official trakt addon at all. And using it in conjunction with Kodi addons serves no real purpose, except in edge cases of people using library integration and wanting to utilize resume points from trakt.

**Comment by sabre6** [comment]
Yes, thank you. exclude HTTPS for sure fixes this issue when the Trakt addon is installed.  

So the only reason to keep the Trakt app would be to scrobble across devices?

**Comment by Tikipeter** [comment]
>So the only reason to keep the Trakt app would be to scrobble across devices?

Yes, but only in a specific circumstance where you are using library integration and using Fen to play back the library item through TMDbHelper. Otherwise the trakt addon is pretty well useless for you. It is used by people with a Kodi library, the way Kodi is meant to be used. You get pretty much nothing out of it if using an addon for your viewing.

You can DISABLE it and see what effect it has, and then remove it if you realize it's not actually doing anything for you. All I've ever seen it do is cause trouble for people using addons for their viewing, as usually an addon will skip marking watched to trakt if you have the trakt addon installed and don't have the exclude http setting enabled. The addon will skip marking as watched in these instances as the trakt addon will also mark it as watched, therefore it will be marked as watched twice, which needs to be avoided.
