### ISSUE TITLE
Latest update breaks "choose languages to include" for easynews

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#666]
With the latest update when you try to select languages to include under Provider Accounts>Easynews FEN throws an error.
Going back to 2.5.15 fixes it.
No log provided as it should be easily reproducible error.

**Comment by ReaLx3m** [comment]
Also noticed there is some regression in seach results. ' symbol is a problem again.
Namely no results displayed for "Don't Look Up" if "Filter Results by name" is checked.
Not sure when it started being a problem again, but i had 2.0.44 laying around, and going back to it works ok and displays results for the movie in question and also other affected items, like Schitt's Creek or It's Always Sunny in Philadelphia

**Comment by Tikipeter** [comment]
Languages error fixed for next update.

**Comment by ReaLx3m** [comment]
Thanks, much appreciated.
Do you need me to open another issue regarding the search results problem with ' symbol, or its ok reporting it here?

**Comment by Tikipeter** [comment]
I've started a new issue for the title match issue, because the number of this current issue is unlucky (`666`), and also I've spent some time recently with the Fenomscrapers dev looking at title matching, so I am completely over it at this moment.

It will have to wait until next update more than likely.
