### ISSUE TITLE
[Question on Reloading Widgets]

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#670]
Hi,

Was wondering if it can be changed to load widgets as first priority or is this up to kodi to choose?

When I turn on my box usually my PVR spools up and at the end widgets reload. This is slow if since I use Trakt Scrobble and make sure I am watching correct episode. I usually goto context menu and use fen refresh widget. Just wondering if it can be set up to refresh as soon as kodi is booted up? 

Thank you. Really appreciate Fen it is amazing add on.  👍

**Comment by Tikipeter** [comment]
This is nearly impossible to solve adequately I'm afraid.

The code is there in Fen to refresh the widgets when there is new trakt data (which happens at startup and then at intervals set through the addon). So I do include code to refresh widgets after a trakt sync if something has changed. Unfortunately I can't do anymore than that.

The issue is likely one of a race condition. When you turn on Kodi fresh, most addons have things in their code that needs to run. Fen has 10 different things it does on startup. When they're all doing that at once, and you may have other addons causing a widget refresh too, then things can get messy pretty quickly.

Unfortunately, it is something you are just going to have to live with.

The good news is Fen will update the widgets if needed after every sync with Trakt. And the ones after the original on startup should work just fine. But the one on startup is vying for attention amongst any number of other services code running.

**Comment by derrgoo** [comment]
Thanks for the detailed explanation. Makes sense.
