### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by AT5Pin** [Tikipeter/repository.tikipeter#677]
I hope this isn't inappropriate to make this comment in here but I know of no other way to say what I need to say.  
So very sad to read your latest comment in change log. 
I truly hope, at worst, you take a much deserved break and continue on with the very best addon out there. 
I know its' selfish of me to ask for you to continue on, but I can only have hope that you do keep on keeping on for those of us enjoy your work, your efforts and absolutely appreciate the hundreds of hours you've put into Fen. 
Since you first discussed creating Fen I have been a fan of your creation and how much it has evolved since then. 
Again, Thank You for doing your do for us and sincerely my best wish's for you and yours. 
M

**Comment by JC253** [comment]
I agree. Just read the news. So sad to read. FEN has been my #1 since release. Nothing comes close to it. I do hope it doesn't go anywhere but I understand that you also have to have a life. I want to thank you for your continued work with FEN and giving thousands of people such a great option. I hope you stick around, but if you do choose to leave the scene, I wish you nothing but the best of luck with whatever you do. I'm searching for the tip jar right now to say thanks. 🤜🏼🤛🏼

**Comment by rishisss23** [comment]
Truly shocked after reading the latest change log. Never needed another addon when we had fen.Always the best.. Like everyone said;best wishes from my part too whatever you decide.. 

Really grateful for all your hardwork.. Sincere Regards

**Comment by JFG1000** [comment]
I also would like to thank you for all your hard work, honestly FEN is the best addon going, and I really do hope you decide to continue on it, there's nothing out there that beats it, I completely respect the choice you make though. Will it still continue to work if Fenomscrapers is maintained?

**Comment by tundrablasen** [comment]
Agreed. Hope you can recharge and finally create a tip jar 😊

**Comment by Liquidrag** [comment]
Thank you from my family. Fen is a wonderful addon and I think it’s great the way it is. You’ve worked so hard to give us this wonderful gift and you have a much deserved break. Just know that your addon is much appreciated in my household as I’m sure with many others. A sincerest thank you and best wishes.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I was really shocked and sad to read the latest changelog in Fen today. However, I guess you too need to relax a bit, but I'm still hopeful that you might change your decision some day.

Thank you for all the hard work behind one of the best Kodi addon - Fen! I'll really miss all the updates! Good luck for all your future endeavours!

Thanks again!

Regards,
ShibajiCh.

**Comment by JFG1000** [comment]
@ShibajiCh he hasn't officially stated he's quitting it yet mate, he's taking a break and a think

**Comment by ShibajiCh** [comment]
@JFG1000, Yes, that's fine. I'm just expressing my thanks to him and hope that he changes his decision and keeps continuing this great addon. 🙂

**Comment by sasagr** [comment]
It was fun ride indeed.. since the beginning it was fun to see the baby furkit developing and becoming FEN, a mature addon that eventually is requiring too much attention. I do wish Tiki the best from his choices whatever they are. I have been seeing him as a passionate person for many years, who spent so much time (maybe too much eventually) on this creature like maybe no other developer has never done. If we have to blame somebody for the end of FEN it is ourself that we did not take the opportunity to learn in all these years from him such passion and support him. At least I do blame myself that I did not do it when I had the chance. All the best, my old furkit-friend. Take care and thanks!

**Comment by Tikipeter** [comment]
Thanks all for the well wishes. Maybe I can restart Fen someday.

**Comment by AT5Pin** [comment]
I do hope we see more of your work with FEN and again, I Thank You for all you've given us and the years of enjoyment you provided to the many with your efforts in creating one of the very best addons to hit the world. 
Take cares and I truly, absolutely truly wish the best for you in whatever it is you do for yourself. 
Thank You Tikipeter!
M
