### ISSUE TITLE
Playback Monitoring Hangs With EN

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#68]
Had this happen few times these last 2 days.
Fen will try playing a link, and while not being successful, (Retry) will not show and will be stuck at the spinning wheel. Sometimes it will work correctly by retrying the first link, and then go to second and get stuck at the second with no retry and not going to the next.
I have left it like that for more than 5 minutes and nothing happens, kodi isnt frozen but back button doesnt do anything, only way to get out is closing kodi either by calling the power menu and pressing exit, or killing the process.

As not playing from first time mostly happens with older stuff, you might be able to reproduce with some older show. I have been experiencing this pretty consistently with "Planet Earth" release year 2006. I have set "Filter Results by size" as line speed of 15Mbit, so you might want to set that the same so you get same files like i do.

**Comment by Tikipeter** [comment]
Gee Easynews really sucks at the moment. How come you always have to bring me bad news?! :)

I'll push an update in a bit that will hopefully at the very least allow the code to be receptive to closing the resolve window under all circumstances. That's the most important thing to get fully right first. You need to be able to cancel the playback successfully always.

As for Easynews, I've added an extra check on whether playback has failed which will hopefully help. But it's getting to the point where I'm running out of ideas. And Kodi's running out of tools I can use.

I don't use autoplay, but if I did I doubt I'd include Easynews results at all at the moment. Their playback is even worse than normal for me.

**Comment by ReaLx3m** [comment]
> How come you always have to bring me bad news?! :)

Hahaha, ok in the future ill make sure to open new tickets every time something works :P

> I don't use autoplay, but if I did I doubt I'd include Easynews results at all at the moment. Their playback is even worse than normal for me.

Ive had this behavior with autoplay disabled, havent used autoplay for some time now. God knows what ill find if i do start using it :P :)

**Comment by Tikipeter** [comment]
>Hahaha, ok in the future ill make sure to open new tickets every time something works :P

I'm not too worried about the number of open tickets going up if that's the proviso. :)

I'm sneaking in a little "press right to skip to next file" feature into this update about to happen. It's not going to be advertised on screen that it's possible, because I just put it in and it needs testing. It will be handy possibly for Easynews because Kodi has a 28 second timeout for trying each playback file. If you get sick of waiting then hopefully you'll be able to press right and it will abandon that attempted resolve and move to the next. Originally I thought I need to take out the Easynews(Retry) if you press right, but I got a couple of Easynews links to play by pressing right on their first attempt, and then letting it try to resolve on the retry. So for the minute I'm going to leave it like that. So if you press right on the first attempt it will try again with the retry. If that proves worthless then I'll need to not do a retry if you've pressed right.

**Comment by ReaLx3m** [comment]
I dont know how to tell you this, and believe me it really breaks my heart... :)
But when that hang happens, pressing right does nothing, and also back still not working.

Sniffed bit of network traffic, and saw something that looks like its common when those hangs happen.
So a connection is established to EN and it has some transfer going in, jumps to about 80-90KB/s for maybe a second, and then that connection gets killed and play monitoring hangs at spinning wheel. Saw this happen the last 3 times it hanged.
Though ill look into it more tomorrow to make sure it happens every time, if you think it might bring some insight ofcourse and help with figuring the issue. Let me know if it wouldnt help you so i dont do a fools errand.

**Comment by Tikipeter** [comment]
I wouldn't bother to be honest.

I might need to rethink this whole thing.

**Comment by ReaLx3m** [comment]
Ok, thank you, wont bother then.
Forgot to add, that i noticed when retry actually works, connections to en are being established but no transfer going in. So i assume when it hangs its kodi being dumb and trying to hold on to that killed connection that got some transfer in.
Downgraded to .18y and hangs are an issue there also.

**Comment by revanth98** [comment]
I see exact same issue with AllDebrid and using external VLC player to play the file. I select the file and it plays on VLC and when vlc is exited, it comes back to fen and it tries to move to next file in allDebrid results. Sometimes if I press back, it comes out with notification "fen: playback failed". But, mostly it just keeps spinning and stuck there. 

If I play local file, this issue is not present.

Version: 3.0.22

**Comment by Tikipeter** [comment]
Looks like you can't use external players with Fen. You will need to use a different addon.
