### ISSUE TITLE
Add Trakt for chasing up metadata

### ISSUE THREAD

**Issue by thomfam** [Tikipeter/repository.tikipeter#689]
Love the addon especially the ability to include my own files in Fen Search.  However the TMDB database can be limited in its search capabilities.  For example House Hunters International (HHI) TV reality series only goes to Series 142 in TMDB.  The most recent series of HHI is now up to series 174.  So when I try to use Fen to search and then watch HHI series 174 (files which I already have downloaded)  the search doesn't include this series because TMDB cuts out around series 142.  I have a Trakt TV account and I see it has TV information for much more than TMDB has including my wife's beloved HHI!

**Comment by Tikipeter** [comment]
>Add Trakt for chasing up metadata....

Firstly, you seem like a logical person so take a step back for a minute and ask yourself "how" this would be achieved. How would Fen know when the data given by TMDb is incomplete, so as to decide when to fall back to using another service to complement that data? There'd be no way to know, meaning every call for data would need to include an extra call to the chosen "backup" service, just so the 2 sets of data could be compared. Not going to happen.

Secondly, I would never use Trakt for metadata like this. Their API is too fragile. So that would mean relying on TVDb for "backup" data. TVDb stated they are going behind a paywall (they still haven't done it), so they are out as a service to use. Their data was curated for free over many, many years by users and they cannot be supported by me if they are then going to lock that data behind a paywall and charge users to access it. Not going to happen. That service needs to die as quickly as possible.

The only other option is what should have popped into your head the minute you saw this was an issue..... "This show I need has insufficient info on the TMDb website, I best get over there and fill in the missing data, because I need it to be more up to date". Go to the TMDb website, and fill in the missing seasons of this show yourself, and then yourself and anyone else using the data for this show will profit from your actions.
