### ISSUE TITLE
Skin problems since new changes - Auramod 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#69]
Hi mate whenever playback the skin is having to reload widgets which was never the case before, I've messaged you on Keybase in more detail along with a video.

Kind regards

**Comment by ReaLx3m** [comment]
Can confirm this happening on my side too. Not sure when it started but, its there with .18y and .21.
Not that big of an issue on fast systems, as a bonus it will refresh the list :), but will pose a problem for slower systems.

Using Aeon Nox Silvo skin here.

**Comment by JFG1000** [comment]
I've had several crashes this afternoon on the latest update since the new scraper window change to the point where I've reverted back to update 3.0.18, I've requested that we have the scraper box setting back so we can choose as personally I prefer the dialogue one and it caused no crashes or reloads of widgets with Auramod, just keeping my fingers crossed Tiki approves

**Comment by Tikipeter** [comment]
Kodi refreshes widgets on playback start and playback end. I cannot stop this.

I can however control WHAT Kodi loads inside the widgets. And the automatic widget refresh on playback start now loads an empty list. You're seeing an empty widget refresh into a populated widget now because of this. In the past you saw (but didn't realize) a pre-populated widget refresh.

There was always a widget refresh at end of playback.

So it's essentially less widget (with content) refreshes, not more.

**Comment by JFG1000** [comment]
Fair enough mate thanks for explaining, i was getting crashes so wasn't sure, would it please be possible to add the option to use the previous scraper dialogue box? I really liked that one it would be massively appreciated

Kind regards
