### ISSUE TITLE
"No content" After Finding Many Links 

### ISSUE THREAD

**Issue by TrillaG** [Tikipeter/repository.tikipeter#693]
Fresh install on a Firestick. Kodi 19.3. Updated Fenomscrapers and Fen to the latest versions with Real Debrid. Still getting a "no content" popup after it scrapes and finds many links. I think that might suggest a resolver error?

**Comment by xyzfre** [comment]
If you can please post a log that will be very helpful for Tikipeter

**Comment by TrillaG** [comment]
https://paste.kodi.tv/micoqiguco

**Comment by TrillaG** [comment]
Just fresh installed again, and it's working now. I will close this for now. If anyone else has this issue to fix it just do a fresh installation.

**Comment by TrillaG** [comment]
Okay I am having this same issue happen again. On firestick. Re-opening this issue.

**Comment by Tikipeter** [comment]
I have no real way to debug this situation.
The log you posted 8 days ago is simply of Kodi starting up (it's little more than a minute). So that is no help to me. Also there's no guarantee there'd be anything in the log even if you provided a useful one (i.e. performed the action in Fen that wasn't working and then upload the log).

Uninstalling an addon NEVER fixes problems, so there's no point doing that over and over. The thing that may have fixed the issue last time is hitting OK when Kodi asks if you want to delete the settings etc when you uninstalled. That might cause it to work when reinstalled and having a fresh settings file.

Otherwise I'm going to need much more specific info from you. All your relevant settings. The scrapers you have active. Posting screenshots of the debrid settings and Results settings that you have on your setup.

From the info that a scrape is performed but then no results are displayed it could be your debrid is not set up correctly, or you have filters enabled and/or set that are removing all the results. But it could be any number of other things as well.

**Comment by TrillaG** [comment]
Okay, sorry about that. Weirdly enough, I booted it up today, and now it's working perfectly again. I will close this issue as it is no longer happening, but I have a feeling it will come up again in the future with someone else, as it has happened to me multiple times now and I've read another reddit post that had the same thing.
