### ISSUE TITLE
Tv shows seasons pack?

### ISSUE THREAD

**Issue by vinkop** [Tikipeter/repository.tikipeter#7]
hello, i miss tv shows season packs from torrents with RD or Premiumize account....I think this is possible to add in Fen addon..Seren and Gaia finding cached seasons pack as well

**Comment by Tikipeter** [comment]
I have a feeling this would be a lot of work.

I assume you mean to check your debrid services for cached season packs?

I'm game to look into it. Hopefully I can do it, but don't get your hopes up. I'll try my best. :(

**Comment by vinkop** [comment]
Thanks...i am sure you can do it.....

**Comment by vinkop** [comment]
any update yet?

**Comment by Tikipeter** [comment]
I am working on it as we speak. I am slow with new things like this, so perhaps within 7 days. Hopefully.

**Comment by Tikipeter** [comment]
Progress report:
Real Debrid Cloud Scraper is finished and appears to be working well.
I can hopefully finish up with Premiumize.me Cloud Scraper tomorrow and then test some more and then release an update including them.

**Comment by Tikipeter** [comment]
RD and PM cache scraping will be in next update to test (v.1.5.39). Any issues let me know.
Of course, results are entirely dependent on the file naming structure of the folders/files.

**Comment by vinkop** [comment]
hmm, i testing now but still not get cached tv shows seasons pack like seren or gaia do as well...

**Comment by Tikipeter** [comment]
Have you enabled the scrapers in Settings->Search?

**Comment by vinkop** [comment]
yes, i have enabled...

**Comment by Tikipeter** [comment]
I'm going to have to try and replicate your issue, as I can't really release a version with the specific logging I'd need because it would be too verbose.
If you let me know of a couple of torrents you have in your cloud that aren't getting scraped properly, and which debrid service, then I can try and get the same situation and see what results I get. If Seren and Gaia are picking them up, then I hope Fen should too, although I did end up writing my own code for it, so some logic may be flawed (I'm nowhere near as good a coder as nixgates or the Gaia team!).

**Comment by vinkop** [comment]
no, i do not have any torrent files in my cloud...i am asking to get cached torrents tv shows seasons pack in one file....seren and gaia finding it as well...you can try to search tv show Friends with seren or gaia and then try to search with Fen...you will see the difference....

**Comment by Tikipeter** [comment]
So that I'm clear, you're saying Seren and Gaia will find a cached torrent for an episode of Friends that is part of a larger 'season pack' torrent?
If yes, I've been misinterpreting what you wanted from the very start of this thread! I assumed you meant you had a season pack in your debrid cloud, and wanted Fen to scrape that cloud and find it.
Leave it with me and I'll see what's possible through Fen, as currently Fen uses Exodus style scrapers to find torrents to query against debrid (RD/PM) cache's, and they don't seem to find such results.

**Comment by vinkop** [comment]
Yes, there was misunderstanding....i want Fen to scrape cached complete seasons tv shows pack with RD/PM debrid service....

**Comment by dm2912** [comment]
Its working for me with RD.

Z-Nation Season 4 was pulling up no sources, so I added the Z-Nation Season 4 torrent to my RD cloud

Its immediately detecting it and playing when doing a cloud scrape

**Comment by Tinuz97** [comment]
complete seasons tv shows would be awesome (Gaia does that indeed) :)

**Comment by Tikipeter** [comment]
This, unfortunately, will not be happening. Eventually, Fen will use Openscrapers, so there is no use in implementing this in Tikiscrapers.
