### ISSUE TITLE
Dolby vision sources

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#700]
Hi it seems dolby vision sources are still appearing with the exclude setting checked in fen settings, would it be possible to take a look, many thanks 
![20220308_202449](https://user-images.githubusercontent.com/76907836/157319085-c61d16d4-9410-4621-b50e-bcaf260a2635.jpg)

**Comment by Tikipeter** [comment]
I'll give it a look now.
Is it only since this most recent update (v.2.6.01)?

**Comment by Tikipeter** [comment]
Well, I didn't even touch anything to do with this in the recent update, but it certainly has broken.
I'll fix it for next update. Might have to turn off HEVC sources or something in the meantime.

**Comment by JFG1000** [comment]
No I noticed it prior to the recent update just wanted to see if the newest update had any possibility of it being fixed, many thanks for your hard work!

**Comment by Tikipeter** [comment]
I think they may be showing because they are "Hybrid" sources. This means they will play as HDR if they can't be played as D/Vision.
I changed code to recognize these "Hybrid" files a few updates ago. They are meant to play either way.
Can you check whether you can play that `D/VISION | HDR` link for me?

**Comment by JFG1000** [comment]
Check your Keybase mate

**Comment by Tikipeter** [comment]
Solved via KB.
