### ISSUE TITLE
Settings (Results tab) - Check Year Before Search - Not Enabled Gives No Debrid Results

### ISSUE THREAD

**Issue by supafyn** [Tikipeter/repository.tikipeter#712]
Hi,

I had seen recently in the closed issue log someone had brought up this setting issue where when they had it enabled they were not getting debrid results:

https://github.com/Tikipeter/repository.tikipeter/issues/701

Seeing the latest update where this was fixed, I am now experiencing the opposite where unless you have this option selected you do not get any debrid results... was this intended behavior?

I know I don't have a log attached, however, if additional information is needed from a log please let me know what and I will certainly add it.

**Comment by Tikipeter** [comment]
Try clearing the External Scrapers Cache and try again.
As far as I can see it is working now.

**Comment by supafyn** [comment]
Yes, I can confirm that doing that as well also works for me.

Generally I always hit the Tools --> Clear Databases and Clean Settings Files --> CLEAR ALL CACHE option after doing a FEN update and so does that no longer than hit the External Scrapers Cache clearing like in the past?

I do notice that when doing that option the pop up display behaves differently after these recent updates than it did before.

**Comment by Tikipeter** [comment]
I'll check into that. Somebody else mentioned there may be a problem there.

Generally it's not a good idea to clear all the cache after each update. Addons put strain on all the resources we use to collect metadata and scraper results etc, and when the cache is cleared all those things need to be refetched from online. It also will slow the addon because it takes much more time to fetch the data from online and then cache it rather than just fetching it directly from the cache.

Up to you of course what you do with your install. I'd be more inclined to only clear caches if you find a problem after updates, and then only clear the caches that seem to be providing an issue.

**Comment by Tikipeter** [comment]
The cache clear in this situation was only needed because Fen had cached the info that there were no results from when the year check issue was present. You could have scraped a new movie title and there would have been results.

**Comment by supafyn** [comment]
Appreciate you looking into this for me and helping me resolve my immediate issue.

Hopefully the CLEAR ALL CACHE bug is a quick one to resolve... thanks again!

**Comment by Tikipeter** [comment]
Clear All Cache fixed for next update.
