### ISSUE TITLE
Blank thumbnails in Trakt TV Collection

### ISSUE THREAD

**Issue by Cloudman999** [Tikipeter/repository.tikipeter#720]
Hi @Tikipeter 
I seem to have 3 blank thumbnails showing up in my Trakt TV Collection list. I have tried to remove these from Trakt TV Collection but Fen will not allow me to do this from the context menu.

Things I have already tried:

Deleted the thumbnails folder
Revoked Trakt and reauthorized in my accounts
Re-synced my accounts with Fen
Cleared all cache (except Favorites and Search)

Accessed Trakt.tv outside Fen and looked through TV Show collection - do not see any blank thumbnails of TV shows.

I authorised Trakt in another add-on (Shadow) and Trakt TV Collection does not show any of the blank thumbnails I can see but cannot get rid of in Fen.

Kodi 19.3 Fen 2.6.07

I would appreciate any help @Tikipeter .

Thank you so much for Fen and all the work you do. It is very much appreciated.

**Comment by Tikipeter** [comment]
I need real info, such as:
* The names of the TV Shows showing blank thumbnails.

Well, that's basically it really. please give me the shows so I can check myself and fix something if it's needed.

>Deleted the thumbnails folder

I hope you also deleted the Textures13.db if you did this. Otherwise you've just screwed up your install of Kodi.

Also please note, Fen doesn't get any meta data from Trakt regarding info or artwork for Movies or TV Shows, so it makes no difference whether Trakt has a thumbnail (poster?) or not. Fen exclusively gets info for Movies and TV Shows from TMDb. That is it's only source. If enabled in settings, Fen will also get artwork from fanart.tv.

**Comment by Cloudman999** [comment]
Thanks for your suggestions @Tikipeter . 
Yes I did delete the Textures13.db file.

Unfortunately, I can't tell you what TV shows the blank thumbnails are, because there is no information about them from the context menu in Fen.

Also when I try to access them, I just get the spinning wheel.

**Comment by Tikipeter** [comment]
Can you post a screenshot of these blank shows?

**Comment by Cloudman999** [comment]
> Can you post a screenshot of these blank shows?

I can - but am not @home right now. Will be later on today.

**Comment by Cloudman999** [comment]
Hi @Tikipeter 

Here are the three screenshots as requested from my Trakt TV:Collection with the blank thumbnails with no information. May need to upload individually.


![Screenshot 2022-03-14 142603](https://user-images.githubusercontent.com/82195999/158100571-3a9f6c27-d9e5-47e4-ad02-3a65e9851a2e.png)

**Comment by Cloudman999** [comment]
![Screenshot 2022-03-14 142740](https://user-images.githubusercontent.com/82195999/158101075-f772adb6-29d8-4e2f-a856-3127c8c765ad.png)

**Comment by Cloudman999** [comment]
![Screenshot 2022-03-14 142818](https://user-images.githubusercontent.com/82195999/158101232-ff6418bc-e583-4772-9807-697d0e291ed2.png)

**Comment by Cloudman999** [comment]
Hi @Tikipeter 
I have tried to recreate another instance of where Trakt returns a blank thumbnail with no information from Fen.

![Screenshot 2022-03-14 154048](https://user-images.githubusercontent.com/82195999/158106269-22512cc1-2e47-418b-a87d-5f4d0400fcd8.png)

Steps to recreate the above from within Fen on Kodi 19.3 Fen 2.6.07:

1. My Lists
2. TRAKT:Lists
3. TRAKT:Popular User Lists
4. Latest Releases (x300) - giladg

**Comment by 123Venom** [comment]
@Tikipeter in his first posted pic I checked it also and the missing title is that Monster Family 2.  Prob something hosed in the meta from Trakt causing the break.

<img width="1388" alt="Fen_2" src="https://user-images.githubusercontent.com/46383815/158110815-5cd0dfbe-ce93-42a1-a5b8-2b8a33b3c634.PNG">

**Comment by 123Venom** [comment]
https://www.themoviedb.org/movie/851112-monster-family-2

BOOM!  Trakt has wrong ID!

**Comment by Cloudman999** [comment]
Hi @Tikipeter @123Venom 

Thank you for investigating the issue. It is much appreciated.

I do not have a  Trakt VIP account. Is this something that I cannot fix myself my end?

**Comment by 123Venom** [comment]
Unfortunately nothing you can easily fix.  Sometimes when the ID's are correct you can refresh the Trakt meta on the main page and it forces a refresh with TMDb.  You'll see the date even flip when you refresh the web page.  In this case the date is not changing therefore that wrong ID is attempting to refresh a bad link so it won't do anything.  You'd have to report it with the button below the refresh meta.  I usually give them the link that is wrong then the link that is right.  In this case the real title is found here

https://www.themoviedb.org/movie/823609-happy-family-2

You can see the ID in the url is different.  Unfortunately it means someone would have to chase down the broken cases from Trakt in that **Latest Releases** list and report them.  I suspect every case is a bad ID.  I did just report this title since I had all the info to provide them with.

Wish they gave us the ability to fix ID's like TMDb does.  We can edit that meta and even fuck shit up..lol

**Comment by Cloudman999** [comment]
Thank you for the explanation @123Venom 
It is much appreciated. I haven't got a Trakt.tv VIP member account and not going to be able to refresh the Trakt meta on the main page.

As I have no idea what the blank thumbnail TV shows that appear in my Fen TV Shows collection actually are called I am at a loss to see how I can report them...

Maybe I will stop using Trakt all together in Fen and just add my TV show: Collection list (without these blank thumbnails) to Fen TV show favorites - but that's going to be a long process unless there is a quick way of doing that?

**Comment by 123Venom** [comment]
Sorry..I read your first reply to fast and thought you said you did have a VIP account.  No worries you just won't be able to use the **Refresh Data** button is all and my hunch is these cases are all going to be bad ID's which that button can't fix anyway.  So what you'd do to trace the broken items is find an occurrence of a missing info item in Fen...then review the trakt site data here...

https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc

and find the gap of what the item is against the before/after item, that's  exactly what I did to find your first item.  Then on the Trakt site right click and open that item in a new tab to preserve your spot on the list, I love new tabs.  Now you can cross check the TMDb ID right there and report it if broken.  I did the first one..it's not hard it's just time consuming but the more that contribute to these efforts the better for all.  Meta is a major pita and trying to put it all together with 3 providers is not fun at all when they have their own amount of broken stuff like this condition.

Your Shows is prob more of the same and bad ID's...you'd had to repeat the process to report

**Comment by Cloudman999** [comment]
> Sorry..I read your first reply to fast and thought you said you did have a VIP account. No worries you just won't be able to use the **Refresh Data** button is all and my hunch is these cases are all going to be bad ID's which that button can't fix anyway. So what you'd do to trace the broken items is find an occurrence of a missing info item in Fen...then review the trakt site data here...
> 
> https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc
> 
> and find the gap of what the item is against the before/after item, that's exactly what I did to find your first item. Then on the Trakt site right click and open that item in a new tab to preserve your spot on the list, I love new tabs. Now you can cross check the TMDb ID right there and report it if broken. I did the first one..it's not hard it's just time consuming but the more that contribute to these efforts the better for all. Meta is a major pita and trying to put it all together with 3 providers is not fun at all when they have their own amount of broken stuff like this condition.
> 
> Your Shows is prob more of the same and bad ID's...you'd had to repeat the process to report

@123Venom Thank you once again for clarifying that I said I did NOT have a Trakt VIP membership lol!

I think I understand your reply... but completely wiped out right now 🤪 It's been a long day and I've spent ages on this, and need to spend some quality family time.

I will try and follow your step by step instructions tomorrow reporting blank thumbnails from my  Fen Trakt TV Shows: Collection as you have done.

If this is the only way to solve this blank thumbnails issue I definately agree with you it is a real pia when IDs don't match up from Trakt with TMDB 😡!

I thank you and @Tikipeter once again for 'going the extra mile' to help me (and probably others who get this problem with blank thumbnails).

With this in mind I guess I will try my best to report the issues. Goodnight now.

**Comment by Cloudman999** [comment]
@Tikipeter @123Venom 
I fixed the problem with the blank thumbnails in my Trakt TV Show Collection.

Steps:
Went into my Trakt.tv account (on my phone)
Sorted my Trakt TV collected shows alphabetical
Compared the position of the blank thumbnail in my Fen Trakt TV:Shows Collection and identified what show the blank thumbnail ones were
Removed all episodes of the blank thumbnail shows from the collection
Used Tools:Clear Databases and Clean Settings Files

Boom (fixed) - blank thumbnails no longer appear in Fen TV Shows:Collection 😀👍

I could not have worked this out without the excellent steps provided by @123Venom .

Thank you guys soooooo much. 




Followed

**Comment by Tikipeter** [comment]
Great job by Venom dev helping out here whilst I was away. Doesn't hurt that he knows his stuff so well. 🥇 

Glad you got it sorted for now @Cloudman999 . Finding that entry in the giladg list would have been a great help to me in sorting out what was happening here. Originally I just thought you were asking about an entry that simply didn't have a poster (which some movies just don't have one in TMDb).

123Venom is right, it's inaccurate info from one meta provider to another.

I'll add a check so that these "blank" entries don't show up anymore in the final list of items.

**Comment by Cloudman999** [comment]
Thank you @Tikipeter  glad this all happened, as you will now get a chance to put in place a check (pending update) so it doesn't happen to anyone else in future! Great stuff 😀👍
