### ISSUE TITLE
Kodi menu cache messing with Trakt refresh?

### ISSUE THREAD

**Issue by MehBlorg** [Tikipeter/repository.tikipeter#737]
RPi 4
Mar 2022 OSMC / Kodi 19.4
Latest Fen
Estuary skin
Default views / no widgets. Basically stock.

Enable new 'cache Kodi menu' option. Watch a show from the Trakt progress list. When show finishes and returns to the progress list (autoplay next is off btw) the list doesn't refresh: the next episode listed for the series just watched, is the episode I just watched.

Do it again with the 'cache Kodi menus' option disabled and another show and it refreshes fine: the ep I just watched is gone from the list, as expected.

I acknowledge that the release notes say to leave this new Kodi menu cache option on unless it causes issues, so I have turned it off. 😁 Figured I'd report it still, though.

Refreshed fine before introduction of this new option.

Easy to repro I think, but if you'd like logs please let me know.

Thanks for the wonderful addon!!

**Comment by 123Venom** [comment]
Not sure what you think you are reporting here.  The changelog was very well stated why the new setting was introduced, and I concur with what was the dev has done on the matter because I've seen how different skinners elect to handle refreshes, and some not handle it at all, so things get messed up because THEY can not seem to adhere to the same system of standards between them!  Seren has had this EXACT same setting for years because of this EXACT reason.  In Seren the setting is called 

`Disable Kodi Menu Caching`

The setting turns off Kodi's `cacheToDisc` feature and sometimes cures the issues form one skin to another and now Fen has chosen to implement the same.  Just because the new setting does not suit you does not mean it was solely meant for you and your skin of choice either.

This posts should be closed and ignored!!

**Comment by JFG1000** [comment]
@MehBlorg the reason this was changed as it was causing several hard crashes to homescreen with certain skins, I use auramod and was one experiencing it, I do not experience the same issue you are

**Comment by MehBlorg** [comment]
Not complaining about the new setting @123Venom. Just reporting a side effect of it I observed. I've turned it off and I'm fine with that. Glad it's helping others, like you @JFG1000.

Just trying to help out. Closing as ordered.

**Comment by Tikipeter** [comment]
Next Episodes will be hardcoded with `cacheToDisc=False` for next update. So you can set the setting to True and still have the Next Episodes refresh properly.

**Comment by JFG1000** [comment]
@Tikipeter just to keep you updated mate having kodi caching to disk enabled no longer causes me crashes like it did before, strange how it suddenly ok now though, many thanks for your hard work

**Comment by Tikipeter** [comment]
It's really a strange happening. The whole Kodi cachetodisc is a bit buggy from what I can tell.

**Comment by MehBlorg** [comment]
> Next Episodes will be hardcoded with `cacheToDisc=False` for next update

Thank you @Tikipeter. I'm glad my contribution had value after all and wasn't just "_**...closed and ignored!!**_".  I appreciate that change.
