### ISSUE TITLE
Announcement...Trakt

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#758]
Anyone having trouble with Trakt or any Trakt related menus, it is time to use a different addon.

I am sick to death of looking into these issues. I have no trouble with any of the Trakt functions, so I know they work.

No one provides a log. No one explains the problem effectively. No one does any trouble shooting of their own.

So, I'm done with it.

**Comment by xyzfre** [comment]
I understand @Tikipeter and there are many things that users can do to troubleshoot these issues ,, really hope everyone respects✊🏼 your wishes your work is amazing always very thankful and grateful for what you do ,,on my end as well everything in my Trakt section is working perfectly as it should.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

It's really a sad truth. 🙁
People lately have stopped doing R&D / troubleshooting on their own. I've noticed so many similar issue tickets in Github recently regarding the same kind of problems which could've been solved if they did little research on their own. Instead they started bothering the developer to solve it, who they should understand is a very busy person and is doing this work as a kind gesture for free. I, myself as a developer can feel your pain. I've also tried to provide fixes to many issues here in Github but majority of them went in vain as most of them have very little knowledge. I don't disrespect anyone but people should really try to learn and use their brain instead of disturbing the developers unless it's a real issue. Also, without the log how can a developer solve the issue.

I can completely understand how you feel. However, it's my kind request to you that because of these people don't feel angry/sad and stop helping people like us with genuine issues. Please continue the great work that you're doing. We're also here to help you whenever we can. Thanks a lot for making our everyday lives better with this amazing addon called "Fen"! 🙂

Thanks and Regards,
ShibajiCh.
