### ISSUE TITLE
Clearart

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#79]
I noticed clear art stop working has it been removed used to look so nice on the OSD screen ,,I know for Seren it had stopped working for a couple days but I noticed yesterday clearart came back for Seren ,it’s a really nice feature to display ,, Appreciate all the help and thank you for all your amazing work with Fen

**Comment by Tikipeter** [comment]
Clearart is still working, but there is a problem with tikimeta where if you have grabbed metadata with extra art off, then it won't fetch it and add it automatically when you turn extra art back on in tikimeta's settings. I wanted it to do this because then you don't have to clear the meta cache if you turn on extra art and want it to appear. At the moment that isn't working. I'll fix that and push an update a bit later.

In the meantime, if you want extra art to appear, make sure first you still have it enabled in tikimeta settings. Then, clear the meta cache and clearart etc should start appearing for you.

But if you can hold off until the update, then you won't need to clear the meta cache.  Tikimeta will simply add the extra art to each items metadata.

My advice, hold off until tikimeta is updated, and then your clearart should re-appear without having to clear the cache.

**Comment by xyzfre** [comment]
Ok thanks for the info ,I see you push the update going to check it out I will keep you posted and thanks again I appreciate your response and for sorting things out lots of respect for your work

**Comment by xyzfre** [comment]
Yep ClearArt is working again GREAT job ,,Big thanks for keeping up with Fen it’s really an amazing addon 👏🏼👏🏼
