### ISSUE TITLE
Enchantment, not a issue. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#8]
Hi, first thx again for this great addon, working wonderful and fast.
Is it possible to add Multi Line like Venom addon has (and a option in the setting menu to turn this on, default off for people who do not like it). 

This 'Multi Line' is great for people (like me) that use the aeon nox skin. 
Because after the Addon shows the links for available streams is 2 lines, everything much better to read. 

Thx :+1:

**Comment by Tinuz97** [comment]
*enhancement, typo

**Comment by Tinuz97** [comment]
With Multi Line it looks like this in Aeon nox silvo mod :+1:

https://imgur.com/a/J68AiLx

**Comment by Tikipeter** [comment]
Hi Tinuz97.

User @Sovilor needed something similar due to the Aeon Nox skin. I have finally had the time to implement it.

It will be available in the next release (v1.5.27). Access the setting in Settings->Search->Display Results as Multi Line.

Either of you let me know if there are any issues with this.

**Comment by Tinuz97** [comment]
Wow great, if the update goes online, I report back,thx 😍

**Comment by Tinuz97** [comment]
It does work nice with Aeon Nox mod skin, thx!  
Realy like this

**Comment by Tikipeter** [comment]
Thanks for reporting back Tinuz97.

I'll close th

**Comment by Sovilor** [comment]
Thanks man, you found a solution for a better looking on Aeon Nox Silvo skin.
