### ISSUE TITLE
More subtitle language options

### ISSUE THREAD

**Issue by LITUATUI** [Tikipeter/repository.tikipeter#80]
Hi.

I love your addon. Fen and Umbrella are by far the best streaming addons for Kodi.

The only thing I miss in Fen is that we can only choose one language for subs. In Umbrella we can choose two (primary and secondary).

If possible, two or three languages would be awesome. 

As a Portuguese speaker I would like to configure it like this:

Primary language: Portuguese (Portugal) - PT-PT
Secondary language: Portuguese (Brazil) - PT-BR
Tertiary language: English - EN

Thanks!

**Comment by pyro12** [comment]
@LITUATUI 
I know it isn't what you requested, but you might find this addon useful.  It allows one subtitle to be played along the top of the screen and another along the bottom.  I believe Tikipeter said that subtitle services will soon be removed from Fen because of changes opensubtitles is making.  This might be a good alternative for you.

I use it more for browsing to local subtitles (kodi's built in function freezes for a few minutes before working) because I frequently rewatch shows and often get the 'rate limited' error from opensubtitles due to using a shared IP with my VPN.  I was going to request TikiPeter update Fen to check for already downloaded subs until I saw that he planned on removing the subtitle service altogether.

https://github.com/peno64/service.subtitles.localsubtitle

**Comment by LITUATUI** [comment]
Thanks for the suggestion @pyro12.

Yeah, that's not what I want. I just want the addon to download/use the subtitle in another language if the primary isn't available, just like Umbrella does.

For example, with Umbrella if the subtitle isn't available in Portuguese (Portugal), it tries to find it in Portuguese (Brazil) from Opensubtitles.

Regarding Opensubtitles, yes the service sucks, but it's still the best we have right now.

Anyway, I wonder if it would be possible to create a subtitle service alternative to Opensubtitles by using a GitHub repo. It would then be easy for the GitHub community to commit changes to the subs and improve them. This is a thing that I need to think about.

**Comment by Tikipeter** [comment]
Unfortunately, I've deleted the email Opensubtitles sent me letting me know they were going behind a paywall.

I thought it was December of this year, but it may be December of next year. I'm finding it hard to find any info about it online.

If it's December of next year, then it makes sense to still make changes/improvements to the subtitle code. If it's December of this year, then there's no point.

I'll keep looking online to try and find the info again.

**Comment by Tikipeter** [comment]
I'll add this for next update. It's not even a dozen lines of code overall, and it can work for as long as the Opensubtitles still works.
