### ISSUE TITLE
Tracking progress

### ISSUE THREAD

**Issue by realcopacetic** [Tikipeter/repository.tikipeter#88]
Hi, I've been asked to add support for progress tracking to my skin when a container is populated using Fen.

Right now, I use the following infolabels to show progress bars for movies/episodes/tvshows/seasons:

ListItem.IsResumable
ListItem.PercentPlayed
ListItem.Overlay
ListItem.Property(WatchedEpisodePercent) (added in Nexus to track watched percent for tvshows or seasons)

Where can I see if your plugin supports these infolabels or if there are others I should be using to show progress on Fen-specific lists? Or is this something that is not possible? Thanks

**Comment by Tikipeter** [comment]
I'm using `overlay` set to `0` or `1` depending on watched status.

I'm not using the default Kodi properties `IsResumable` or `PercentPlayed` because they will trigger a resume prompt when first selecting the listitem, which I don't want to have happen.

I am however using `WatchedProgress` & `resumetime`, both of which I set the watched percentage. One or both of these (I can't remember) were incorporated into Jurial's AH2 skin so the progress percent could be displayed successfully on addons like Fen.

The Venom dev arranged it for us both, so I would assume the Umbrella addon has that code carried over as well. I use those properties for Movies and episodes.

**Comment by realcopacetic** [comment]
Great thanks for the info!

**Comment by Tikipeter** [comment]
No problem. Upon closer inspection, I use the `WatchedProgress` for TV Shows and Seasons containers too.

**Comment by realcopacetic** [comment]
Thanks, I'll hopefully have this up and running for my skin in a few days
