### ISSUE TITLE
Are there any benefits to empty list loading on widget refresh?

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#99]
So this has been annoying me since it was implemented, every time you end a movie you need to wait few second for the widget to repopulate, and loose your position in the list if youre just checking out some movies and playing short clips from them.
And the worst part is with low powered devices, it already takes pretty long for the widgets to populate when you first boot up, probably around a minute on a raspberry 3B, which is bearable as it used to happen just one time when you initially boot, but going through that over and over its pretty excruciating.
In the way im using the addon, i really havent seen any benefit of doing it this way, pre-populated refresh was working perfectly.
Is there something im missing, and emtpy list is crucial/beneficial for some function that i dont seem to use/notice?

**Comment by Tikipeter** [comment]
> [WIDGET RELOAD].....used to happen just one time when you initially boot,

Despite what it looks like, widgets are reloading every time you START a movie/episode, and every time you END a movie/episode.

Kodi performs these refreshes, and there is no way to stop it from happening.

Kodi also periodically refreshes all widgets during an open session. Meaning there are many widget refreshes happening whilst Kodi is running, not just one when it starts up.

To mitigate this, I am stopping the widgets from reloading with full list items when a movie/episode STARTS.

The benefits are:

* It stops an unnecessary full reload of all the listitems in the widgets when playback starts. Doing that puts less strain on your device whilst it's also trying to resolve a link for playback.
* It greatly diminishes the amount of crashes seen due to refreshing widgets when the reuselanguageinvoker is ON. A theory that this may be the case was the the original reason to implement an empty list.

**Comment by Tikipeter** [comment]
Having had a few conversations with you in the past, I'm making a prediction that my reply above is likely not going to quench your desire to have the widgets behave how they used to. Call it intuition. You've come around to my way of thinking before, but I don't think you're going to this time. :)

It's one thing for me to know it is better not to refresh the widgets with a full list when playback starts (it's a worthless refresh), It's another to understand why visually and practically it may be preferred to not inhibit that reload, as the pre-loaded list can be accessed even whilst it's reloading after playback ends.

So anticipating the above situation, I will add a setting for the next update (due within a day or so) that wil enable you to disable loading an empty list on the playback start widget refresh.

I'm only doing this because I like your face.

**Comment by ReaLx3m** [comment]
> I'm only doing this because I like your face.

I saw you replying to my post on reddit, and figured you missed me, and an issue is bound to be opened. Also i guess im lucky being the pretty one in this relationship :P hahaha. And thank you.

So were clear, as you mention refreshing on playback start, what im witnesing and having problem with is the refresh at playback end. Or maybe im misinterpreting something?
When video is stopped, youre greeted with empty widget and wait time for it to repopulate.
Like this video shows - https://www.youtube.com/watch?v=BkVpDS_XHTE

**Comment by Tikipeter** [comment]
Yep, we're on the same page. It's empty immediate after the end of playback because I stop it reloading the full listitems at the beginning of playback. It sits like that all during playback.

When playback ends the widgets reload, and this time there's no suppression of the listitems.

The setting will stop this from happening.

I'll let you know here what the setting will be called and where it will be.

**Comment by xyzfre** [comment]
This is GREAT news because I used to like the old way as well when the widgets will refresh in the background on home screen widgets but it wasn’t visual to us users if that makes sense lol thank you @Tikipeter for all your hard work Fen is amazing 💯

**Comment by Tikipeter** [comment]
Yep, makes total sense.

Maybe I'll have the default stay the old way when I do this setting.

**Comment by ReaLx3m** [comment]
> Yep, we're on the same page. It's empty immediate after the end of playback because I stop it reloading the full listitems at the beginning of playback.

Ok, clear now.

**Comment by ReaLx3m** [comment]
One more thing while were here. Official Trailer gets sorted at the bottom of the list, and i assume thats the one entry most people want to click, i know i do at least. 
Often there are movies/shows with plenty of other videos like teasers, behind the scenes, bloopers etc, and it takes plenty of clicking down to get where you want to. I know i know, you can cllick up once, but that part almost always escapes me for some reason :) and i do it the hard way.   
Not really a big deal, but Official Trailer would look better at the top position and just one click away imo, so if possible consider sorting it to top. 
Its all about the flow, and doing least work for most results :).

**Comment by xyzfre** [comment]
> 

Really looking forward For this next update @Tikipeter THANK YOU 💯💯

**Comment by xyzfre** [comment]
> Yep, makes total sense.
> 
> 
> 
> Maybe I'll have the default stay the old way when I do this setting.

Really looking forward For this next update @Tikipeter THANK YOU 💯💯

**Comment by ambulancePilot** [comment]
Looking forward to this as well, can't wait to see how it works out!

**Comment by Tikipeter** [comment]
I'll need to hold off the update for 24 hours as the Umbrella dev got in first with quite a large update. Meaning there could be issues. No good having both addons go down on the same day if we both screwed up.

New setting ended up landing in Playback->Playback Utilities.->`Load Empty Widget Container on Playback Start`.

Because I was being altogether too nice in this thread, I am going to default it to `ON` though.

I need to live with myself giving in so easily.

**Comment by ReaLx3m** [comment]
> I need to live with myself giving in so easily.

DAMNIT, HE WINS AGAIN. Drats and double drats. :)

**Comment by Tikipeter** [comment]
>DAMNIT, HE WINS AGAIN. Drats and double drats. :)

Aahhhh, that's what I needed.
